set(sources_rnd
    ${PROJECT_SOURCE_DIR}/src/main.c
    ${PROJECT_SOURCE_DIR}/src/conf_gfx.c 
    ${PROJECT_SOURCE_DIR}/src/conf_snd.c 
    ${PROJECT_SOURCE_DIR}/src/conf_mus.c 
    ${PROJECT_SOURCE_DIR}/src/conf_hlp.c  
    ${PROJECT_SOURCE_DIR}/src/init.c 
    ${PROJECT_SOURCE_DIR}/src/config.c 
    ${PROJECT_SOURCE_DIR}/src/events.c
    ${PROJECT_SOURCE_DIR}/src/tools.c 
    ${PROJECT_SOURCE_DIR}/src/screens.c 
    ${PROJECT_SOURCE_DIR}/src/game.c 
    ${PROJECT_SOURCE_DIR}/src/editor.c 
    ${PROJECT_SOURCE_DIR}/src/files.c 
    ${PROJECT_SOURCE_DIR}/src/tape.c 
    ${PROJECT_SOURCE_DIR}/src/anim.c 
    ${PROJECT_SOURCE_DIR}/src/network.c 
    ${PROJECT_SOURCE_DIR}/src/netserv.c
    ${PROJECT_SOURCE_DIR}/src/libgame/system.c 
    ${PROJECT_SOURCE_DIR}/src/libgame/gadgets.c 
    ${PROJECT_SOURCE_DIR}/src/libgame/text.c 
    ${PROJECT_SOURCE_DIR}/src/libgame/sound.c
    ${PROJECT_SOURCE_DIR}/src/libgame/snapshot.c
    ${PROJECT_SOURCE_DIR}/src/libgame/joystick.c 
    ${PROJECT_SOURCE_DIR}/src/libgame/image.c 
    ${PROJECT_SOURCE_DIR}/src/libgame/random.c
    ${PROJECT_SOURCE_DIR}/src/libgame/hash.c 
    ${PROJECT_SOURCE_DIR}/src/libgame/setup.c 
    ${PROJECT_SOURCE_DIR}/src/libgame/misc.c 
    ${PROJECT_SOURCE_DIR}/src/libgame/sdl.c  
    ${PROJECT_SOURCE_DIR}/src/libgame/zip/ioapi.c
    ${PROJECT_SOURCE_DIR}/src/libgame/zip/iowin32.c 
    ${PROJECT_SOURCE_DIR}/src/libgame/zip/unzip.c 
    ${PROJECT_SOURCE_DIR}/src/libgame/zip/miniunz.c
    ${PROJECT_SOURCE_DIR}/src/game_em/cave.c 
    ${PROJECT_SOURCE_DIR}/src/game_em/convert.c 
    ${PROJECT_SOURCE_DIR}/src/game_em/graphics.c   
    ${PROJECT_SOURCE_DIR}/src/game_em/init.c
    ${PROJECT_SOURCE_DIR}/src/game_em/input.c
    ${PROJECT_SOURCE_DIR}/src/game_em/main.c 
    ${PROJECT_SOURCE_DIR}/src/game_em/sound.c 
    ${PROJECT_SOURCE_DIR}/src/game_em/synchro_1.c 
    ${PROJECT_SOURCE_DIR}/src/game_em/synchro_2.c
    ${PROJECT_SOURCE_DIR}/src/game_em/synchro_3.c 
    ${PROJECT_SOURCE_DIR}/src/game_em/tab_generate.c 
    ${PROJECT_SOURCE_DIR}/src/game_em/ulaw_generate.c
    ${PROJECT_SOURCE_DIR}/src/game_mm/mm_init.c 
    ${PROJECT_SOURCE_DIR}/src/game_mm/mm_main.c 
    ${PROJECT_SOURCE_DIR}/src/game_mm/mm_game.c 
    ${PROJECT_SOURCE_DIR}/src/game_mm/mm_files.c
    ${PROJECT_SOURCE_DIR}/src/game_mm/mm_tools.c
    ${PROJECT_SOURCE_DIR}/src/game_sp/init.c 
    ${PROJECT_SOURCE_DIR}/src/game_sp/file.c 
    ${PROJECT_SOURCE_DIR}/src/game_sp/main.c 
    ${PROJECT_SOURCE_DIR}/src/game_sp/vb_lib.c 
    ${PROJECT_SOURCE_DIR}/src/game_sp/ASM.c
    ${PROJECT_SOURCE_DIR}/src/game_sp/BugsTerminals.c 
    ${PROJECT_SOURCE_DIR}/src/game_sp/DDScrollBuffer.c 
    ${PROJECT_SOURCE_DIR}/src/game_sp/DDSpriteBuffer.c
    ${PROJECT_SOURCE_DIR}/src/game_sp/Display.c 
    ${PROJECT_SOURCE_DIR}/src/game_sp/DoGameStuff.c 
    ${PROJECT_SOURCE_DIR}/src/game_sp/Electrons.c 
    ${PROJECT_SOURCE_DIR}/src/game_sp/Explosions.c
    ${PROJECT_SOURCE_DIR}/src/game_sp/Globals.c 
    ${PROJECT_SOURCE_DIR}/src/game_sp/Infotrons.c 
    ${PROJECT_SOURCE_DIR}/src/game_sp/InitGameConditions.c 
    ${PROJECT_SOURCE_DIR}/src/game_sp/Input.c
    ${PROJECT_SOURCE_DIR}/src/game_sp/MainForm.c 
    ${PROJECT_SOURCE_DIR}/src/game_sp/MainGameLoop.c 
    ${PROJECT_SOURCE_DIR}/src/game_sp/Murphy.c 
    ${PROJECT_SOURCE_DIR}/src/game_sp/OrangeDisk.c
    ${PROJECT_SOURCE_DIR}/src/game_sp/SnikSnaks.c  
    ${PROJECT_SOURCE_DIR}/src/game_sp/Sound.c 
    ${PROJECT_SOURCE_DIR}/src/game_sp/Zonk.c
)

set(sources_ai
    ${PROJECT_SOURCE_DIR}/src/ai/ai_entry.cpp
    ${PROJECT_SOURCE_DIR}/src/ai/controller/controller.cpp
    ${PROJECT_SOURCE_DIR}/src/ai/controller/default/default.cpp
    ${PROJECT_SOURCE_DIR}/src/ai/controller/mcts/mcts.cpp
    ${PROJECT_SOURCE_DIR}/src/ai/controller/mcts/tree_node.cpp
    ${PROJECT_SOURCE_DIR}/src/ai/controller/options/option_factory.cpp
    ${PROJECT_SOURCE_DIR}/src/ai/controller/options/base_option.cpp
    ${PROJECT_SOURCE_DIR}/src/ai/controller/options/option_single_step.cpp
    ${PROJECT_SOURCE_DIR}/src/ai/controller/options/option_collectible_sprite.cpp
    ${PROJECT_SOURCE_DIR}/src/ai/controller/options/option_to_exit.cpp
    ${PROJECT_SOURCE_DIR}/src/ai/controller/options/option_door.cpp
    ${PROJECT_SOURCE_DIR}/src/ai/controller/replay/replay.cpp
    ${PROJECT_SOURCE_DIR}/src/ai/controller/simple_pathing/simple_pathing.cpp
    ${PROJECT_SOURCE_DIR}/src/ai/controller/two_level_search/two_level_search.cpp
    ${PROJECT_SOURCE_DIR}/src/ai/controller/two_level_search/tls_highlevel.cpp
    ${PROJECT_SOURCE_DIR}/src/ai/controller/two_level_search/tls_node_policy.cpp
    ${PROJECT_SOURCE_DIR}/src/ai/controller/two_level_search/tls_constraint_detection.cpp
    ${PROJECT_SOURCE_DIR}/src/ai/controller/two_level_search/util/tls_combinatorial_node.cpp
    ${PROJECT_SOURCE_DIR}/src/ai/controller/two_level_search/util/tls_feature.cpp
    ${PROJECT_SOURCE_DIR}/src/ai/controller/two_level_search/tls_log.cpp
    ${PROJECT_SOURCE_DIR}/src/ai/engine/engine_types.cpp
    ${PROJECT_SOURCE_DIR}/src/ai/engine/engine_action_info.cpp
    ${PROJECT_SOURCE_DIR}/src/ai/engine/engine_element_property.cpp
    ${PROJECT_SOURCE_DIR}/src/ai/engine/engine_grid_action.cpp
    ${PROJECT_SOURCE_DIR}/src/ai/engine/engine_grid_info.cpp
    ${PROJECT_SOURCE_DIR}/src/ai/engine/engine_hash.cpp
    ${PROJECT_SOURCE_DIR}/src/ai/engine/engine_level_info.cpp
    ${PROJECT_SOURCE_DIR}/src/ai/engine/engine_status_info.cpp
    ${PROJECT_SOURCE_DIR}/src/ai/engine/game_state.cpp
    ${PROJECT_SOURCE_DIR}/src/ai/level_programming/level_programming.cpp
    ${PROJECT_SOURCE_DIR}/src/ai/util/config_reader.cpp
    ${PROJECT_SOURCE_DIR}/src/ai/util/file_dir_naming.cpp
    ${PROJECT_SOURCE_DIR}/src/ai/util/timer.cpp
    ${PROJECT_SOURCE_DIR}/src/ai/util/rng.cpp
    ${PROJECT_SOURCE_DIR}/src/ai/util/logger.cpp
    ${PROJECT_SOURCE_DIR}/src/ai/util/statistics.cpp
)

set(sources_tests
    ${PROJECT_SOURCE_DIR}/src/ai/tests/engine_action_info_test.cpp
    ${PROJECT_SOURCE_DIR}/src/ai/tests/engine_element_property_test.cpp
    ${PROJECT_SOURCE_DIR}/src/ai/tests/engine_grid_action_test.cpp
    ${PROJECT_SOURCE_DIR}/src/ai/tests/engine_grid_info_test.cpp
    ${PROJECT_SOURCE_DIR}/src/ai/tests/engine_level_info_test.cpp
    ${PROJECT_SOURCE_DIR}/src/ai/tests/test_util.cpp
    ${PROJECT_SOURCE_DIR}/src/ai/tests/tls/tls_hash_test.cpp
)

set(AUTOCONF
    ${PROJECT_SOURCE_DIR}/src/conf_gfx.h
    ${PROJECT_SOURCE_DIR}/src/conf_snd.h
    ${PROJECT_SOURCE_DIR}/src/conf_mus.h
)
set(AUTOCONF_DEPS
        ${PROJECT_SOURCE_DIR}/src/conf_gfx.c
        ${PROJECT_SOURCE_DIR}/src/conf_snd.c
        ${PROJECT_SOURCE_DIR}/src/conf_mus.c
)

set(CNFS
    conf_gfx.h
    conf_snd.h
    conf_mus.h
    conf_chr.c
    conf_chr.h
    conf_cus.c
    conf_cus.h
    conf_grp.c
    conf_grp.h
    conf_e2g.c
    conf_esg.c
    conf_e2s.c
    conf_fnt.c
    conf_g2s.c
    conf_g2m.c
    conf_var.c
    conf_act.c
)