set(sources src/main.c
    src/conf_gfx.c 
    src/conf_snd.c 
    src/conf_mus.c 
    src/conf_hlp.c  
    src/init.c 
    src/config.c 
    src/events.c
    src/tools.c 
    src/screens.c 
    src/game.c 
    src/editor.c 
    src/files.c 
    src/tape.c 
    src/anim.c 
    src/network.c 
    src/netserv.c
    src/libgame/system.c 
    src/libgame/gadgets.c 
    src/libgame/text.c 
    src/libgame/sound.c
    src/libgame/snapshot.c
    src/libgame/joystick.c 
    src/libgame/image.c 
    src/libgame/random.c
    src/libgame/hash.c 
    src/libgame/setup.c 
    src/libgame/misc.c 
    src/libgame/sdl.c  
    src/libgame/zip/ioapi.c
    src/libgame/zip/iowin32.c 
    src/libgame/zip/unzip.c 
    src/libgame/zip/miniunz.c
    src/game_em/cave.c 
    src/game_em/convert.c 
    src/game_em/graphics.c   
    src/game_em/init.c
    src/game_em/input.c
    src/game_em/main.c 
    src/game_em/sound.c 
    src/game_em/synchro_1.c 
    src/game_em/synchro_2.c
    src/game_em/synchro_3.c 
    src/game_em/tab_generate.c 
    src/game_em/ulaw_generate.c
    src/game_mm/mm_init.c 
    src/game_mm/mm_main.c 
    src/game_mm/mm_game.c 
    src/game_mm/mm_files.c
    src/game_mm/mm_tools.c
    src/game_sp/init.c 
    src/game_sp/file.c 
    src/game_sp/main.c 
    src/game_sp/vb_lib.c 
    src/game_sp/ASM.c
    src/game_sp/BugsTerminals.c 
    src/game_sp/DDScrollBuffer.c 
    src/game_sp/DDSpriteBuffer.c
    src/game_sp/Display.c 
    src/game_sp/DoGameStuff.c 
    src/game_sp/Electrons.c 
    src/game_sp/Explosions.c
    src/game_sp/Globals.c 
    src/game_sp/Infotrons.c 
    src/game_sp/InitGameConditions.c 
    src/game_sp/Input.c
    src/game_sp/MainForm.c 
    src/game_sp/MainGameLoop.c 
    src/game_sp/Murphy.c 
    src/game_sp/OrangeDisk.c
    src/game_sp/SnikSnaks.c  
    src/game_sp/Sound.c 
    src/game_sp/Zonk.c
    src/ai/ai_entry.cpp
    src/ai/hash_table.cpp
    src/ai/controller/controller.cpp
    src/ai/controller/default/default.cpp
    src/ai/controller/mcts/mcts.cpp
    src/ai/controller/mcts/tree_node.cpp
    src/ai/controller/options/option_factory.cpp
    src/ai/controller/options/base_option.cpp
    src/ai/controller/options/option_single_step.cpp
    src/ai/controller/options/option_to_sprite.cpp
    src/ai/controller/options/option_collectible_sprite.cpp
    src/ai/controller/options/option_to_exit.cpp
    src/ai/controller/options/option_to_rock.cpp
    src/ai/controller/options/option_wait_rock.cpp
    src/ai/controller/options/option_push_rock.cpp
    src/ai/controller/replay/replay.cpp
    src/ai/controller/two_level_search/two_level_search.cpp
    src/ai/engine/action.cpp
    src/ai/engine/engine_helper.cpp
    src/ai/engine/game_state.cpp
    src/ai/engine/game_state_abstract.cpp
    src/ai/level_programming/level_programming.cpp
    src/ai/util/timer.cpp
    src/ai/util/rng.cpp
    src/ai/util/logger.cpp
    src/ai/util/statistics.cpp
    src/ai/util/summary_window.cpp
    src/ai/tests/test_engine_speed.cpp
    src/ai/tests/test_rng.cpp 
)

set(AUTOCONF src/conf_gfx.h
    src/conf_snd.h
    src/conf_mus.h
)

set(CNFS src/conf_gfx.h
    src/conf_snd.h
    src/conf_mus.h
    src/conf_chr.c
    src/conf_chr.h
    src/conf_cus.c
    src/conf_cus.h
    src/conf_grp.c
    src/conf_grp.h
    src/conf_e2g.c
    src/conf_esg.c
    src/conf_e2s.c
    src/conf_fnt.c
    src/conf_g2s.c
    src/conf_g2m.c
    src/conf_var.c
    src/conf_act.c
)