/***********************************************************
* Rocks'n'Diamonds -- McDuffin Strikes Back!               *
*----------------------------------------------------------*
* (c) 1995-2002 Artsoft Entertainment                      *
*               Holger Schemel                             *
*               Detmolder Strasse 189                      *
*               33604 Bielefeld                            *
*               Germany                                    *
*               e-mail: info@artsoft.org                   *
*----------------------------------------------------------*
* conf_esg.c                                               *
***********************************************************/

/* ----- this file was automatically generated -- do not edit by hand ----- */

#ifndef CONF_ESG_C
#define CONF_ESG_C

/* values for element/graphics mapping configuration (special) */

static struct
{
  int element;
  int special;

  int graphic;
}
element_to_special_graphic[] =
{
  {
    EL_BD_WALL,					GFX_SPECIAL_ARG_EDITOR,
    IMG_BD_WALL_EDITOR
  },
  {
    EL_BD_ROCK,					GFX_SPECIAL_ARG_EDITOR,
    IMG_BD_ROCK_EDITOR
  },
  {
    EL_BD_AMOEBA,				GFX_SPECIAL_ARG_EDITOR,
    IMG_BD_AMOEBA_EDITOR
  },
  {
    EL_SP_INFOTRON,				GFX_SPECIAL_ARG_EDITOR,
    IMG_SP_INFOTRON_EDITOR
  },
  {
    EL_SP_ELECTRON,				GFX_SPECIAL_ARG_EDITOR,
    IMG_SP_ELECTRON_EDITOR
  },
  {
    EL_SP_TERMINAL,				GFX_SPECIAL_ARG_EDITOR,
    IMG_SP_TERMINAL_EDITOR
  },
  {
    EL_SP_BUGGY_BASE,				GFX_SPECIAL_ARG_EDITOR,
    IMG_SP_BUGGY_BASE_EDITOR
  },
  {
    EL_SOKOBAN_OBJECT,				GFX_SPECIAL_ARG_EDITOR,
    IMG_SOKOBAN_OBJECT_EDITOR
  },
  {
    EL_DYNAMITE,				GFX_SPECIAL_ARG_EDITOR,
    IMG_DYNAMITE_EDITOR
  },
  {
    EL_DYNAMITE_ACTIVE,				GFX_SPECIAL_ARG_EDITOR,
    IMG_DYNAMITE_ACTIVE_EDITOR
  },
  {
    EL_QUICKSAND_FULL,				GFX_SPECIAL_ARG_EDITOR,
    IMG_QUICKSAND_FULL_EDITOR
  },
  {
    EL_AMOEBA_WET,				GFX_SPECIAL_ARG_EDITOR,
    IMG_AMOEBA_WET_EDITOR
  },
  {
    EL_AMOEBA_FULL,				GFX_SPECIAL_ARG_EDITOR,
    IMG_AMOEBA_FULL_EDITOR
  },
  {
    EL_AMOEBA_DEAD,				GFX_SPECIAL_ARG_EDITOR,
    IMG_AMOEBA_DEAD_EDITOR
  },
  {
    EL_EM_GATE_1_GRAY,				GFX_SPECIAL_ARG_EDITOR,
    IMG_EM_GATE_1_GRAY_EDITOR
  },
  {
    EL_EM_GATE_2_GRAY,				GFX_SPECIAL_ARG_EDITOR,
    IMG_EM_GATE_2_GRAY_EDITOR
  },
  {
    EL_EM_GATE_3_GRAY,				GFX_SPECIAL_ARG_EDITOR,
    IMG_EM_GATE_3_GRAY_EDITOR
  },
  {
    EL_EM_GATE_4_GRAY,				GFX_SPECIAL_ARG_EDITOR,
    IMG_EM_GATE_4_GRAY_EDITOR
  },
  {
    EL_INVISIBLE_STEELWALL,			GFX_SPECIAL_ARG_EDITOR,
    IMG_INVISIBLE_STEELWALL_EDITOR
  },
  {
    EL_INVISIBLE_WALL,				GFX_SPECIAL_ARG_EDITOR,
    IMG_INVISIBLE_WALL_EDITOR
  },
  {
    EL_INVISIBLE_SAND,				GFX_SPECIAL_ARG_EDITOR,
    IMG_INVISIBLE_SAND_EDITOR
  },
  {
    EL_KEY_1,					GFX_SPECIAL_ARG_EDITOR,
    IMG_KEY_1_EDITOR
  },
  {
    EL_KEY_2,					GFX_SPECIAL_ARG_EDITOR,
    IMG_KEY_2_EDITOR
  },
  {
    EL_KEY_3,					GFX_SPECIAL_ARG_EDITOR,
    IMG_KEY_3_EDITOR
  },
  {
    EL_KEY_4,					GFX_SPECIAL_ARG_EDITOR,
    IMG_KEY_4_EDITOR
  },
  {
    EL_GATE_1_GRAY,				GFX_SPECIAL_ARG_EDITOR,
    IMG_GATE_1_GRAY_EDITOR
  },
  {
    EL_GATE_2_GRAY,				GFX_SPECIAL_ARG_EDITOR,
    IMG_GATE_2_GRAY_EDITOR
  },
  {
    EL_GATE_3_GRAY,				GFX_SPECIAL_ARG_EDITOR,
    IMG_GATE_3_GRAY_EDITOR
  },
  {
    EL_GATE_4_GRAY,				GFX_SPECIAL_ARG_EDITOR,
    IMG_GATE_4_GRAY_EDITOR
  },
  {
    EL_LAMP,					GFX_SPECIAL_ARG_EDITOR,
    IMG_LAMP_EDITOR
  },
  {
    EL_EXPANDABLE_WALL_HORIZONTAL,		GFX_SPECIAL_ARG_EDITOR,
    IMG_EXPANDABLE_WALL_HORIZONTAL_EDITOR
  },
  {
    EL_EXPANDABLE_WALL_VERTICAL,		GFX_SPECIAL_ARG_EDITOR,
    IMG_EXPANDABLE_WALL_VERTICAL_EDITOR
  },
  {
    EL_EXPANDABLE_WALL_ANY,			GFX_SPECIAL_ARG_EDITOR,
    IMG_EXPANDABLE_WALL_ANY_EDITOR
  },
  {
    EL_PENGUIN,					GFX_SPECIAL_ARG_EDITOR,
    IMG_PENGUIN_EDITOR
  },
  {
    EL_PLAYER_1,				GFX_SPECIAL_ARG_EDITOR,
    IMG_PLAYER_1_EDITOR
  },
  {
    EL_PLAYER_2,				GFX_SPECIAL_ARG_EDITOR,
    IMG_PLAYER_2_EDITOR
  },
  {
    EL_PLAYER_3,				GFX_SPECIAL_ARG_EDITOR,
    IMG_PLAYER_3_EDITOR
  },
  {
    EL_PLAYER_4,				GFX_SPECIAL_ARG_EDITOR,
    IMG_PLAYER_4_EDITOR
  },
  {
    EL_STEELWALL_TOPLEFT,			GFX_SPECIAL_ARG_EDITOR,
    IMG_STEELWALL_TOPLEFT_EDITOR
  },
  {
    EL_STEELWALL_TOPRIGHT,			GFX_SPECIAL_ARG_EDITOR,
    IMG_STEELWALL_TOPRIGHT_EDITOR
  },
  {
    EL_STEELWALL_BOTTOMLEFT,			GFX_SPECIAL_ARG_EDITOR,
    IMG_STEELWALL_BOTTOMLEFT_EDITOR
  },
  {
    EL_STEELWALL_BOTTOMRIGHT,			GFX_SPECIAL_ARG_EDITOR,
    IMG_STEELWALL_BOTTOMRIGHT_EDITOR
  },
  {
    EL_STEELWALL_HORIZONTAL,			GFX_SPECIAL_ARG_EDITOR,
    IMG_STEELWALL_HORIZONTAL_EDITOR
  },
  {
    EL_STEELWALL_VERTICAL,			GFX_SPECIAL_ARG_EDITOR,
    IMG_STEELWALL_VERTICAL_EDITOR
  },
  {
    EL_INVISIBLE_STEELWALL_TOPLEFT,		GFX_SPECIAL_ARG_EDITOR,
    IMG_INVISIBLE_STEELWALL_TOPLEFT_EDITOR
  },
  {
    EL_INVISIBLE_STEELWALL_TOPRIGHT,		GFX_SPECIAL_ARG_EDITOR,
    IMG_INVISIBLE_STEELWALL_TOPRIGHT_EDITOR
  },
  {
    EL_INVISIBLE_STEELWALL_BOTTOMLEFT,		GFX_SPECIAL_ARG_EDITOR,
    IMG_INVISIBLE_STEELWALL_BOTTOMLEFT_EDITOR
  },
  {
    EL_INVISIBLE_STEELWALL_BOTTOMRIGHT,		GFX_SPECIAL_ARG_EDITOR,
    IMG_INVISIBLE_STEELWALL_BOTTOMRIGHT_EDITOR
  },
  {
    EL_INVISIBLE_STEELWALL_HORIZONTAL,		GFX_SPECIAL_ARG_EDITOR,
    IMG_INVISIBLE_STEELWALL_HORIZONTAL_EDITOR
  },
  {
    EL_INVISIBLE_STEELWALL_VERTICAL,		GFX_SPECIAL_ARG_EDITOR,
    IMG_INVISIBLE_STEELWALL_VERTICAL_EDITOR
  },
  {
    EL_CUSTOM_1,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_1_EDITOR
  },
  {
    EL_CUSTOM_2,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_2_EDITOR
  },
  {
    EL_CUSTOM_3,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_3_EDITOR
  },
  {
    EL_CUSTOM_4,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_4_EDITOR
  },
  {
    EL_CUSTOM_5,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_5_EDITOR
  },
  {
    EL_CUSTOM_6,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_6_EDITOR
  },
  {
    EL_CUSTOM_7,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_7_EDITOR
  },
  {
    EL_CUSTOM_8,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_8_EDITOR
  },
  {
    EL_CUSTOM_9,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_9_EDITOR
  },
  {
    EL_CUSTOM_10,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_10_EDITOR
  },
  {
    EL_CUSTOM_11,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_11_EDITOR
  },
  {
    EL_CUSTOM_12,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_12_EDITOR
  },
  {
    EL_CUSTOM_13,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_13_EDITOR
  },
  {
    EL_CUSTOM_14,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_14_EDITOR
  },
  {
    EL_CUSTOM_15,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_15_EDITOR
  },
  {
    EL_CUSTOM_16,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_16_EDITOR
  },
  {
    EL_CUSTOM_17,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_17_EDITOR
  },
  {
    EL_CUSTOM_18,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_18_EDITOR
  },
  {
    EL_CUSTOM_19,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_19_EDITOR
  },
  {
    EL_CUSTOM_20,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_20_EDITOR
  },
  {
    EL_CUSTOM_21,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_21_EDITOR
  },
  {
    EL_CUSTOM_22,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_22_EDITOR
  },
  {
    EL_CUSTOM_23,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_23_EDITOR
  },
  {
    EL_CUSTOM_24,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_24_EDITOR
  },
  {
    EL_CUSTOM_25,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_25_EDITOR
  },
  {
    EL_CUSTOM_26,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_26_EDITOR
  },
  {
    EL_CUSTOM_27,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_27_EDITOR
  },
  {
    EL_CUSTOM_28,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_28_EDITOR
  },
  {
    EL_CUSTOM_29,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_29_EDITOR
  },
  {
    EL_CUSTOM_30,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_30_EDITOR
  },
  {
    EL_CUSTOM_31,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_31_EDITOR
  },
  {
    EL_CUSTOM_32,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_32_EDITOR
  },
  {
    EL_CUSTOM_33,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_33_EDITOR
  },
  {
    EL_CUSTOM_34,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_34_EDITOR
  },
  {
    EL_CUSTOM_35,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_35_EDITOR
  },
  {
    EL_CUSTOM_36,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_36_EDITOR
  },
  {
    EL_CUSTOM_37,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_37_EDITOR
  },
  {
    EL_CUSTOM_38,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_38_EDITOR
  },
  {
    EL_CUSTOM_39,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_39_EDITOR
  },
  {
    EL_CUSTOM_40,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_40_EDITOR
  },
  {
    EL_CUSTOM_41,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_41_EDITOR
  },
  {
    EL_CUSTOM_42,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_42_EDITOR
  },
  {
    EL_CUSTOM_43,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_43_EDITOR
  },
  {
    EL_CUSTOM_44,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_44_EDITOR
  },
  {
    EL_CUSTOM_45,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_45_EDITOR
  },
  {
    EL_CUSTOM_46,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_46_EDITOR
  },
  {
    EL_CUSTOM_47,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_47_EDITOR
  },
  {
    EL_CUSTOM_48,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_48_EDITOR
  },
  {
    EL_CUSTOM_49,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_49_EDITOR
  },
  {
    EL_CUSTOM_50,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_50_EDITOR
  },
  {
    EL_CUSTOM_51,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_51_EDITOR
  },
  {
    EL_CUSTOM_52,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_52_EDITOR
  },
  {
    EL_CUSTOM_53,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_53_EDITOR
  },
  {
    EL_CUSTOM_54,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_54_EDITOR
  },
  {
    EL_CUSTOM_55,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_55_EDITOR
  },
  {
    EL_CUSTOM_56,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_56_EDITOR
  },
  {
    EL_CUSTOM_57,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_57_EDITOR
  },
  {
    EL_CUSTOM_58,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_58_EDITOR
  },
  {
    EL_CUSTOM_59,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_59_EDITOR
  },
  {
    EL_CUSTOM_60,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_60_EDITOR
  },
  {
    EL_CUSTOM_61,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_61_EDITOR
  },
  {
    EL_CUSTOM_62,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_62_EDITOR
  },
  {
    EL_CUSTOM_63,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_63_EDITOR
  },
  {
    EL_CUSTOM_64,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_64_EDITOR
  },
  {
    EL_CUSTOM_65,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_65_EDITOR
  },
  {
    EL_CUSTOM_66,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_66_EDITOR
  },
  {
    EL_CUSTOM_67,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_67_EDITOR
  },
  {
    EL_CUSTOM_68,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_68_EDITOR
  },
  {
    EL_CUSTOM_69,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_69_EDITOR
  },
  {
    EL_CUSTOM_70,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_70_EDITOR
  },
  {
    EL_CUSTOM_71,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_71_EDITOR
  },
  {
    EL_CUSTOM_72,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_72_EDITOR
  },
  {
    EL_CUSTOM_73,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_73_EDITOR
  },
  {
    EL_CUSTOM_74,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_74_EDITOR
  },
  {
    EL_CUSTOM_75,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_75_EDITOR
  },
  {
    EL_CUSTOM_76,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_76_EDITOR
  },
  {
    EL_CUSTOM_77,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_77_EDITOR
  },
  {
    EL_CUSTOM_78,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_78_EDITOR
  },
  {
    EL_CUSTOM_79,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_79_EDITOR
  },
  {
    EL_CUSTOM_80,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_80_EDITOR
  },
  {
    EL_CUSTOM_81,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_81_EDITOR
  },
  {
    EL_CUSTOM_82,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_82_EDITOR
  },
  {
    EL_CUSTOM_83,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_83_EDITOR
  },
  {
    EL_CUSTOM_84,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_84_EDITOR
  },
  {
    EL_CUSTOM_85,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_85_EDITOR
  },
  {
    EL_CUSTOM_86,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_86_EDITOR
  },
  {
    EL_CUSTOM_87,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_87_EDITOR
  },
  {
    EL_CUSTOM_88,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_88_EDITOR
  },
  {
    EL_CUSTOM_89,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_89_EDITOR
  },
  {
    EL_CUSTOM_90,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_90_EDITOR
  },
  {
    EL_CUSTOM_91,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_91_EDITOR
  },
  {
    EL_CUSTOM_92,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_92_EDITOR
  },
  {
    EL_CUSTOM_93,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_93_EDITOR
  },
  {
    EL_CUSTOM_94,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_94_EDITOR
  },
  {
    EL_CUSTOM_95,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_95_EDITOR
  },
  {
    EL_CUSTOM_96,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_96_EDITOR
  },
  {
    EL_CUSTOM_97,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_97_EDITOR
  },
  {
    EL_CUSTOM_98,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_98_EDITOR
  },
  {
    EL_CUSTOM_99,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_99_EDITOR
  },
  {
    EL_CUSTOM_100,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_100_EDITOR
  },
  {
    EL_CUSTOM_101,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_101_EDITOR
  },
  {
    EL_CUSTOM_102,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_102_EDITOR
  },
  {
    EL_CUSTOM_103,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_103_EDITOR
  },
  {
    EL_CUSTOM_104,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_104_EDITOR
  },
  {
    EL_CUSTOM_105,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_105_EDITOR
  },
  {
    EL_CUSTOM_106,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_106_EDITOR
  },
  {
    EL_CUSTOM_107,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_107_EDITOR
  },
  {
    EL_CUSTOM_108,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_108_EDITOR
  },
  {
    EL_CUSTOM_109,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_109_EDITOR
  },
  {
    EL_CUSTOM_110,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_110_EDITOR
  },
  {
    EL_CUSTOM_111,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_111_EDITOR
  },
  {
    EL_CUSTOM_112,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_112_EDITOR
  },
  {
    EL_CUSTOM_113,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_113_EDITOR
  },
  {
    EL_CUSTOM_114,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_114_EDITOR
  },
  {
    EL_CUSTOM_115,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_115_EDITOR
  },
  {
    EL_CUSTOM_116,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_116_EDITOR
  },
  {
    EL_CUSTOM_117,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_117_EDITOR
  },
  {
    EL_CUSTOM_118,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_118_EDITOR
  },
  {
    EL_CUSTOM_119,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_119_EDITOR
  },
  {
    EL_CUSTOM_120,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_120_EDITOR
  },
  {
    EL_CUSTOM_121,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_121_EDITOR
  },
  {
    EL_CUSTOM_122,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_122_EDITOR
  },
  {
    EL_CUSTOM_123,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_123_EDITOR
  },
  {
    EL_CUSTOM_124,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_124_EDITOR
  },
  {
    EL_CUSTOM_125,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_125_EDITOR
  },
  {
    EL_CUSTOM_126,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_126_EDITOR
  },
  {
    EL_CUSTOM_127,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_127_EDITOR
  },
  {
    EL_CUSTOM_128,				GFX_SPECIAL_ARG_EDITOR,
    IMG_CUSTOM_128_EDITOR
  },
  {
    -1,						-1,
    -1
  },
};

#endif	/* CONF_ESG_C */
