/***********************************************************
* Rocks'n'Diamonds -- McDuffin Strikes Back!               *
*----------------------------------------------------------*
* (c) 1995-2002 Artsoft Entertainment                      *
*               Holger Schemel                             *
*               Detmolder Strasse 189                      *
*               33604 Bielefeld                            *
*               Germany                                    *
*               e-mail: info@artsoft.org                   *
*----------------------------------------------------------*
* conf_esg.c                                               *
***********************************************************/

/* ----- this file was automatically generated -- do not edit by hand ----- */

#ifndef CONF_ESG_C
#define CONF_ESG_C

/* values for element/graphics mapping configuration (special) */

static struct
{
  int element;
  int special;

  int graphic;
}
element_to_special_graphic[] =
{
  {
    EL_BD_WALL,					GFX_SPECIAL_ARG_EDITOR,
    IMG_BD_WALL_EDITOR
  },
  {
    EL_BD_ROCK,					GFX_SPECIAL_ARG_EDITOR,
    IMG_BD_ROCK_EDITOR
  },
  {
    EL_BD_AMOEBA,				GFX_SPECIAL_ARG_EDITOR,
    IMG_BD_AMOEBA_EDITOR
  },
  {
    EL_SP_INFOTRON,				GFX_SPECIAL_ARG_EDITOR,
    IMG_SP_INFOTRON_EDITOR
  },
  {
    EL_SP_ELECTRON,				GFX_SPECIAL_ARG_EDITOR,
    IMG_SP_ELECTRON_EDITOR
  },
  {
    EL_SP_TERMINAL,				GFX_SPECIAL_ARG_EDITOR,
    IMG_SP_TERMINAL_EDITOR
  },
  {
    EL_SOKOBAN_OBJECT,				GFX_SPECIAL_ARG_EDITOR,
    IMG_SOKOBAN_OBJECT_EDITOR
  },
  {
    EL_DYNAMITE,				GFX_SPECIAL_ARG_EDITOR,
    IMG_DYNAMITE_EDITOR
  },
  {
    EL_DYNAMITE_ACTIVE,				GFX_SPECIAL_ARG_EDITOR,
    IMG_DYNAMITE_ACTIVE_EDITOR
  },
  {
    EL_QUICKSAND_FULL,				GFX_SPECIAL_ARG_EDITOR,
    IMG_QUICKSAND_FULL_EDITOR
  },
  {
    EL_AMOEBA_WET,				GFX_SPECIAL_ARG_EDITOR,
    IMG_AMOEBA_WET_EDITOR
  },
  {
    EL_AMOEBA_FULL,				GFX_SPECIAL_ARG_EDITOR,
    IMG_AMOEBA_FULL_EDITOR
  },
  {
    EL_AMOEBA_DEAD,				GFX_SPECIAL_ARG_EDITOR,
    IMG_AMOEBA_DEAD_EDITOR
  },
  {
    EL_EM_GATE_1_GRAY_CLOSED,			GFX_SPECIAL_ARG_EDITOR,
    IMG_EM_GATE_1_GRAY_CLOSED_EDITOR
  },
  {
    EL_EM_GATE_2_GRAY_CLOSED,			GFX_SPECIAL_ARG_EDITOR,
    IMG_EM_GATE_2_GRAY_CLOSED_EDITOR
  },
  {
    EL_EM_GATE_3_GRAY_CLOSED,			GFX_SPECIAL_ARG_EDITOR,
    IMG_EM_GATE_3_GRAY_CLOSED_EDITOR
  },
  {
    EL_EM_GATE_4_GRAY_CLOSED,			GFX_SPECIAL_ARG_EDITOR,
    IMG_EM_GATE_4_GRAY_CLOSED_EDITOR
  },
  {
    EL_INVISIBLE_STEELWALL,			GFX_SPECIAL_ARG_EDITOR,
    IMG_INVISIBLE_STEELWALL_EDITOR
  },
  {
    EL_INVISIBLE_WALL,				GFX_SPECIAL_ARG_EDITOR,
    IMG_INVISIBLE_WALL_EDITOR
  },
  {
    EL_INVISIBLE_SAND,				GFX_SPECIAL_ARG_EDITOR,
    IMG_INVISIBLE_SAND_EDITOR
  },
  {
    EL_KEY_1,					GFX_SPECIAL_ARG_EDITOR,
    IMG_KEY_1_EDITOR
  },
  {
    EL_KEY_2,					GFX_SPECIAL_ARG_EDITOR,
    IMG_KEY_2_EDITOR
  },
  {
    EL_KEY_3,					GFX_SPECIAL_ARG_EDITOR,
    IMG_KEY_3_EDITOR
  },
  {
    EL_KEY_4,					GFX_SPECIAL_ARG_EDITOR,
    IMG_KEY_4_EDITOR
  },
  {
    EL_GATE_1_GRAY_CLOSED,			GFX_SPECIAL_ARG_EDITOR,
    IMG_GATE_1_GRAY_CLOSED_EDITOR
  },
  {
    EL_GATE_2_GRAY_CLOSED,			GFX_SPECIAL_ARG_EDITOR,
    IMG_GATE_2_GRAY_CLOSED_EDITOR
  },
  {
    EL_GATE_3_GRAY_CLOSED,			GFX_SPECIAL_ARG_EDITOR,
    IMG_GATE_3_GRAY_CLOSED_EDITOR
  },
  {
    EL_GATE_4_GRAY_CLOSED,			GFX_SPECIAL_ARG_EDITOR,
    IMG_GATE_4_GRAY_CLOSED_EDITOR
  },
  {
    EL_LAMP,					GFX_SPECIAL_ARG_EDITOR,
    IMG_LAMP_EDITOR
  },
  {
    EL_EXPANDABLE_WALL_HORIZONTAL,		GFX_SPECIAL_ARG_EDITOR,
    IMG_EXPANDABLE_WALL_HORIZONTAL_EDITOR
  },
  {
    EL_EXPANDABLE_WALL_VERTICAL,		GFX_SPECIAL_ARG_EDITOR,
    IMG_EXPANDABLE_WALL_VERTICAL_EDITOR
  },
  {
    EL_EXPANDABLE_WALL_ANY,			GFX_SPECIAL_ARG_EDITOR,
    IMG_EXPANDABLE_WALL_ANY_EDITOR
  },
  {
    EL_PENGUIN,					GFX_SPECIAL_ARG_EDITOR,
    IMG_PENGUIN_EDITOR
  },
  {
    EL_PLAYER_1,				GFX_SPECIAL_ARG_EDITOR,
    IMG_PLAYER_1_EDITOR
  },
  {
    EL_PLAYER_2,				GFX_SPECIAL_ARG_EDITOR,
    IMG_PLAYER_2_EDITOR
  },
  {
    EL_PLAYER_3,				GFX_SPECIAL_ARG_EDITOR,
    IMG_PLAYER_3_EDITOR
  },
  {
    EL_PLAYER_4,				GFX_SPECIAL_ARG_EDITOR,
    IMG_PLAYER_4_EDITOR
  },
  {
    EL_STEELWALL_TOPLEFT,			GFX_SPECIAL_ARG_EDITOR,
    IMG_STEELWALL_TOPLEFT_EDITOR
  },
  {
    EL_STEELWALL_TOPRIGHT,			GFX_SPECIAL_ARG_EDITOR,
    IMG_STEELWALL_TOPRIGHT_EDITOR
  },
  {
    EL_STEELWALL_BOTTOMLEFT,			GFX_SPECIAL_ARG_EDITOR,
    IMG_STEELWALL_BOTTOMLEFT_EDITOR
  },
  {
    EL_STEELWALL_BOTTOMRIGHT,			GFX_SPECIAL_ARG_EDITOR,
    IMG_STEELWALL_BOTTOMRIGHT_EDITOR
  },
  {
    EL_STEELWALL_HORIZONTAL,			GFX_SPECIAL_ARG_EDITOR,
    IMG_STEELWALL_HORIZONTAL_EDITOR
  },
  {
    EL_STEELWALL_VERTICAL,			GFX_SPECIAL_ARG_EDITOR,
    IMG_STEELWALL_VERTICAL_EDITOR
  },
  {
    EL_INVISIBLE_STEELWALL_TOPLEFT,		GFX_SPECIAL_ARG_EDITOR,
    IMG_INVISIBLE_STEELWALL_TOPLEFT_EDITOR
  },
  {
    EL_INVISIBLE_STEELWALL_TOPRIGHT,		GFX_SPECIAL_ARG_EDITOR,
    IMG_INVISIBLE_STEELWALL_TOPRIGHT_EDITOR
  },
  {
    EL_INVISIBLE_STEELWALL_BOTTOMLEFT,		GFX_SPECIAL_ARG_EDITOR,
    IMG_INVISIBLE_STEELWALL_BOTTOMLEFT_EDITOR
  },
  {
    EL_INVISIBLE_STEELWALL_BOTTOMRIGHT,		GFX_SPECIAL_ARG_EDITOR,
    IMG_INVISIBLE_STEELWALL_BOTTOMRIGHT_EDITOR
  },
  {
    EL_INVISIBLE_STEELWALL_HORIZONTAL,		GFX_SPECIAL_ARG_EDITOR,
    IMG_INVISIBLE_STEELWALL_HORIZONTAL_EDITOR
  },
  {
    EL_INVISIBLE_STEELWALL_VERTICAL,		GFX_SPECIAL_ARG_EDITOR,
    IMG_INVISIBLE_STEELWALL_VERTICAL_EDITOR
  },
  {
    EL_BUG,					GFX_SPECIAL_ARG_EDITOR,
    IMG_BUG_RIGHT
  },
  {
    EL_BUG,					GFX_SPECIAL_ARG_PREVIEW,
    IMG_BUG_RIGHT
  },
  {
    EL_PACMAN,					GFX_SPECIAL_ARG_EDITOR,
    IMG_PACMAN_RIGHT
  },
  {
    EL_PACMAN,					GFX_SPECIAL_ARG_PREVIEW,
    IMG_PACMAN_RIGHT
  },
  {
    EL_SPACESHIP,				GFX_SPECIAL_ARG_EDITOR,
    IMG_SPACESHIP_RIGHT
  },
  {
    EL_SPACESHIP,				GFX_SPECIAL_ARG_PREVIEW,
    IMG_SPACESHIP_RIGHT
  },
  {
    -1,						-1,
    -1
  },
};

#endif	/* CONF_ESG_C */
