/***********************************************************
* Rocks'n'Diamonds -- McDuffin Strikes Back!               *
*----------------------------------------------------------*
* (c) 1995-2002 Artsoft Entertainment                      *
*               Holger Schemel                             *
*               Detmolder Strasse 189                      *
*               33604 Bielefeld                            *
*               Germany                                    *
*               e-mail: info@artsoft.org                   *
*----------------------------------------------------------*
* conf_cus.h                                               *
***********************************************************/

/* ----- this file was automatically generated -- do not edit by hand ----- */

#ifndef CONF_CUS_H
#define CONF_CUS_H

/* values for elements configuration (custom elements) */

#define EL_CUSTOM_1			(EL_CUSTOM_START + 0)
#define EL_CUSTOM_2			(EL_CUSTOM_START + 1)
#define EL_CUSTOM_3			(EL_CUSTOM_START + 2)
#define EL_CUSTOM_4			(EL_CUSTOM_START + 3)
#define EL_CUSTOM_5			(EL_CUSTOM_START + 4)
#define EL_CUSTOM_6			(EL_CUSTOM_START + 5)
#define EL_CUSTOM_7			(EL_CUSTOM_START + 6)
#define EL_CUSTOM_8			(EL_CUSTOM_START + 7)
#define EL_CUSTOM_9			(EL_CUSTOM_START + 8)
#define EL_CUSTOM_10			(EL_CUSTOM_START + 9)
#define EL_CUSTOM_11			(EL_CUSTOM_START + 10)
#define EL_CUSTOM_12			(EL_CUSTOM_START + 11)
#define EL_CUSTOM_13			(EL_CUSTOM_START + 12)
#define EL_CUSTOM_14			(EL_CUSTOM_START + 13)
#define EL_CUSTOM_15			(EL_CUSTOM_START + 14)
#define EL_CUSTOM_16			(EL_CUSTOM_START + 15)
#define EL_CUSTOM_17			(EL_CUSTOM_START + 16)
#define EL_CUSTOM_18			(EL_CUSTOM_START + 17)
#define EL_CUSTOM_19			(EL_CUSTOM_START + 18)
#define EL_CUSTOM_20			(EL_CUSTOM_START + 19)
#define EL_CUSTOM_21			(EL_CUSTOM_START + 20)
#define EL_CUSTOM_22			(EL_CUSTOM_START + 21)
#define EL_CUSTOM_23			(EL_CUSTOM_START + 22)
#define EL_CUSTOM_24			(EL_CUSTOM_START + 23)
#define EL_CUSTOM_25			(EL_CUSTOM_START + 24)
#define EL_CUSTOM_26			(EL_CUSTOM_START + 25)
#define EL_CUSTOM_27			(EL_CUSTOM_START + 26)
#define EL_CUSTOM_28			(EL_CUSTOM_START + 27)
#define EL_CUSTOM_29			(EL_CUSTOM_START + 28)
#define EL_CUSTOM_30			(EL_CUSTOM_START + 29)
#define EL_CUSTOM_31			(EL_CUSTOM_START + 30)
#define EL_CUSTOM_32			(EL_CUSTOM_START + 31)
#define EL_CUSTOM_33			(EL_CUSTOM_START + 32)
#define EL_CUSTOM_34			(EL_CUSTOM_START + 33)
#define EL_CUSTOM_35			(EL_CUSTOM_START + 34)
#define EL_CUSTOM_36			(EL_CUSTOM_START + 35)
#define EL_CUSTOM_37			(EL_CUSTOM_START + 36)
#define EL_CUSTOM_38			(EL_CUSTOM_START + 37)
#define EL_CUSTOM_39			(EL_CUSTOM_START + 38)
#define EL_CUSTOM_40			(EL_CUSTOM_START + 39)
#define EL_CUSTOM_41			(EL_CUSTOM_START + 40)
#define EL_CUSTOM_42			(EL_CUSTOM_START + 41)
#define EL_CUSTOM_43			(EL_CUSTOM_START + 42)
#define EL_CUSTOM_44			(EL_CUSTOM_START + 43)
#define EL_CUSTOM_45			(EL_CUSTOM_START + 44)
#define EL_CUSTOM_46			(EL_CUSTOM_START + 45)
#define EL_CUSTOM_47			(EL_CUSTOM_START + 46)
#define EL_CUSTOM_48			(EL_CUSTOM_START + 47)
#define EL_CUSTOM_49			(EL_CUSTOM_START + 48)
#define EL_CUSTOM_50			(EL_CUSTOM_START + 49)
#define EL_CUSTOM_51			(EL_CUSTOM_START + 50)
#define EL_CUSTOM_52			(EL_CUSTOM_START + 51)
#define EL_CUSTOM_53			(EL_CUSTOM_START + 52)
#define EL_CUSTOM_54			(EL_CUSTOM_START + 53)
#define EL_CUSTOM_55			(EL_CUSTOM_START + 54)
#define EL_CUSTOM_56			(EL_CUSTOM_START + 55)
#define EL_CUSTOM_57			(EL_CUSTOM_START + 56)
#define EL_CUSTOM_58			(EL_CUSTOM_START + 57)
#define EL_CUSTOM_59			(EL_CUSTOM_START + 58)
#define EL_CUSTOM_60			(EL_CUSTOM_START + 59)
#define EL_CUSTOM_61			(EL_CUSTOM_START + 60)
#define EL_CUSTOM_62			(EL_CUSTOM_START + 61)
#define EL_CUSTOM_63			(EL_CUSTOM_START + 62)
#define EL_CUSTOM_64			(EL_CUSTOM_START + 63)
#define EL_CUSTOM_65			(EL_CUSTOM_START + 64)
#define EL_CUSTOM_66			(EL_CUSTOM_START + 65)
#define EL_CUSTOM_67			(EL_CUSTOM_START + 66)
#define EL_CUSTOM_68			(EL_CUSTOM_START + 67)
#define EL_CUSTOM_69			(EL_CUSTOM_START + 68)
#define EL_CUSTOM_70			(EL_CUSTOM_START + 69)
#define EL_CUSTOM_71			(EL_CUSTOM_START + 70)
#define EL_CUSTOM_72			(EL_CUSTOM_START + 71)
#define EL_CUSTOM_73			(EL_CUSTOM_START + 72)
#define EL_CUSTOM_74			(EL_CUSTOM_START + 73)
#define EL_CUSTOM_75			(EL_CUSTOM_START + 74)
#define EL_CUSTOM_76			(EL_CUSTOM_START + 75)
#define EL_CUSTOM_77			(EL_CUSTOM_START + 76)
#define EL_CUSTOM_78			(EL_CUSTOM_START + 77)
#define EL_CUSTOM_79			(EL_CUSTOM_START + 78)
#define EL_CUSTOM_80			(EL_CUSTOM_START + 79)
#define EL_CUSTOM_81			(EL_CUSTOM_START + 80)
#define EL_CUSTOM_82			(EL_CUSTOM_START + 81)
#define EL_CUSTOM_83			(EL_CUSTOM_START + 82)
#define EL_CUSTOM_84			(EL_CUSTOM_START + 83)
#define EL_CUSTOM_85			(EL_CUSTOM_START + 84)
#define EL_CUSTOM_86			(EL_CUSTOM_START + 85)
#define EL_CUSTOM_87			(EL_CUSTOM_START + 86)
#define EL_CUSTOM_88			(EL_CUSTOM_START + 87)
#define EL_CUSTOM_89			(EL_CUSTOM_START + 88)
#define EL_CUSTOM_90			(EL_CUSTOM_START + 89)
#define EL_CUSTOM_91			(EL_CUSTOM_START + 90)
#define EL_CUSTOM_92			(EL_CUSTOM_START + 91)
#define EL_CUSTOM_93			(EL_CUSTOM_START + 92)
#define EL_CUSTOM_94			(EL_CUSTOM_START + 93)
#define EL_CUSTOM_95			(EL_CUSTOM_START + 94)
#define EL_CUSTOM_96			(EL_CUSTOM_START + 95)
#define EL_CUSTOM_97			(EL_CUSTOM_START + 96)
#define EL_CUSTOM_98			(EL_CUSTOM_START + 97)
#define EL_CUSTOM_99			(EL_CUSTOM_START + 98)
#define EL_CUSTOM_100			(EL_CUSTOM_START + 99)
#define EL_CUSTOM_101			(EL_CUSTOM_START + 100)
#define EL_CUSTOM_102			(EL_CUSTOM_START + 101)
#define EL_CUSTOM_103			(EL_CUSTOM_START + 102)
#define EL_CUSTOM_104			(EL_CUSTOM_START + 103)
#define EL_CUSTOM_105			(EL_CUSTOM_START + 104)
#define EL_CUSTOM_106			(EL_CUSTOM_START + 105)
#define EL_CUSTOM_107			(EL_CUSTOM_START + 106)
#define EL_CUSTOM_108			(EL_CUSTOM_START + 107)
#define EL_CUSTOM_109			(EL_CUSTOM_START + 108)
#define EL_CUSTOM_110			(EL_CUSTOM_START + 109)
#define EL_CUSTOM_111			(EL_CUSTOM_START + 110)
#define EL_CUSTOM_112			(EL_CUSTOM_START + 111)
#define EL_CUSTOM_113			(EL_CUSTOM_START + 112)
#define EL_CUSTOM_114			(EL_CUSTOM_START + 113)
#define EL_CUSTOM_115			(EL_CUSTOM_START + 114)
#define EL_CUSTOM_116			(EL_CUSTOM_START + 115)
#define EL_CUSTOM_117			(EL_CUSTOM_START + 116)
#define EL_CUSTOM_118			(EL_CUSTOM_START + 117)
#define EL_CUSTOM_119			(EL_CUSTOM_START + 118)
#define EL_CUSTOM_120			(EL_CUSTOM_START + 119)
#define EL_CUSTOM_121			(EL_CUSTOM_START + 120)
#define EL_CUSTOM_122			(EL_CUSTOM_START + 121)
#define EL_CUSTOM_123			(EL_CUSTOM_START + 122)
#define EL_CUSTOM_124			(EL_CUSTOM_START + 123)
#define EL_CUSTOM_125			(EL_CUSTOM_START + 124)
#define EL_CUSTOM_126			(EL_CUSTOM_START + 125)
#define EL_CUSTOM_127			(EL_CUSTOM_START + 126)
#define EL_CUSTOM_128			(EL_CUSTOM_START + 127)

#endif	/* CONF_CUS_C */
