// ============================================================================
// Rocks'n'Diamonds - McDuffin Strikes Back!
// ----------------------------------------------------------------------------
// (c) 1995-2014 by Artsoft Entertainment
//                  Holger Schemel
//                  info@artsoft.org
//                  http://www.artsoft.org/
// ----------------------------------------------------------------------------
// conf_cus.c
// ============================================================================

/* ----- this file was automatically generated -- do not edit by hand ----- */

#ifndef CONF_CUS_C
#define CONF_CUS_C

/* values for graphics configuration (custom elements) */

  { "custom_1",					"RocksCE.png"		},
  { "custom_1.xpos",				"0"			},
  { "custom_1.ypos",				"0"			},
  { "custom_1.frames",				"1"			},
  { "custom_1.EDITOR",				"RocksCE.png"		},
  { "custom_1.EDITOR.xpos",			"16"			},
  { "custom_1.EDITOR.ypos",			"0"			},

  { "custom_2",					"RocksCE.png"		},
  { "custom_2.xpos",				"1"			},
  { "custom_2.ypos",				"0"			},
  { "custom_2.frames",				"1"			},
  { "custom_2.EDITOR",				"RocksCE.png"		},
  { "custom_2.EDITOR.xpos",			"17"			},
  { "custom_2.EDITOR.ypos",			"0"			},

  { "custom_3",					"RocksCE.png"		},
  { "custom_3.xpos",				"2"			},
  { "custom_3.ypos",				"0"			},
  { "custom_3.frames",				"1"			},
  { "custom_3.EDITOR",				"RocksCE.png"		},
  { "custom_3.EDITOR.xpos",			"18"			},
  { "custom_3.EDITOR.ypos",			"0"			},

  { "custom_4",					"RocksCE.png"		},
  { "custom_4.xpos",				"3"			},
  { "custom_4.ypos",				"0"			},
  { "custom_4.frames",				"1"			},
  { "custom_4.EDITOR",				"RocksCE.png"		},
  { "custom_4.EDITOR.xpos",			"19"			},
  { "custom_4.EDITOR.ypos",			"0"			},

  { "custom_5",					"RocksCE.png"		},
  { "custom_5.xpos",				"4"			},
  { "custom_5.ypos",				"0"			},
  { "custom_5.frames",				"1"			},
  { "custom_5.EDITOR",				"RocksCE.png"		},
  { "custom_5.EDITOR.xpos",			"20"			},
  { "custom_5.EDITOR.ypos",			"0"			},

  { "custom_6",					"RocksCE.png"		},
  { "custom_6.xpos",				"5"			},
  { "custom_6.ypos",				"0"			},
  { "custom_6.frames",				"1"			},
  { "custom_6.EDITOR",				"RocksCE.png"		},
  { "custom_6.EDITOR.xpos",			"21"			},
  { "custom_6.EDITOR.ypos",			"0"			},

  { "custom_7",					"RocksCE.png"		},
  { "custom_7.xpos",				"6"			},
  { "custom_7.ypos",				"0"			},
  { "custom_7.frames",				"1"			},
  { "custom_7.EDITOR",				"RocksCE.png"		},
  { "custom_7.EDITOR.xpos",			"22"			},
  { "custom_7.EDITOR.ypos",			"0"			},

  { "custom_8",					"RocksCE.png"		},
  { "custom_8.xpos",				"7"			},
  { "custom_8.ypos",				"0"			},
  { "custom_8.frames",				"1"			},
  { "custom_8.EDITOR",				"RocksCE.png"		},
  { "custom_8.EDITOR.xpos",			"23"			},
  { "custom_8.EDITOR.ypos",			"0"			},

  { "custom_9",					"RocksCE.png"		},
  { "custom_9.xpos",				"8"			},
  { "custom_9.ypos",				"0"			},
  { "custom_9.frames",				"1"			},
  { "custom_9.EDITOR",				"RocksCE.png"		},
  { "custom_9.EDITOR.xpos",			"24"			},
  { "custom_9.EDITOR.ypos",			"0"			},

  { "custom_10",				"RocksCE.png"		},
  { "custom_10.xpos",				"9"			},
  { "custom_10.ypos",				"0"			},
  { "custom_10.frames",				"1"			},
  { "custom_10.EDITOR",				"RocksCE.png"		},
  { "custom_10.EDITOR.xpos",			"25"			},
  { "custom_10.EDITOR.ypos",			"0"			},

  { "custom_11",				"RocksCE.png"		},
  { "custom_11.xpos",				"10"			},
  { "custom_11.ypos",				"0"			},
  { "custom_11.frames",				"1"			},
  { "custom_11.EDITOR",				"RocksCE.png"		},
  { "custom_11.EDITOR.xpos",			"26"			},
  { "custom_11.EDITOR.ypos",			"0"			},

  { "custom_12",				"RocksCE.png"		},
  { "custom_12.xpos",				"11"			},
  { "custom_12.ypos",				"0"			},
  { "custom_12.frames",				"1"			},
  { "custom_12.EDITOR",				"RocksCE.png"		},
  { "custom_12.EDITOR.xpos",			"27"			},
  { "custom_12.EDITOR.ypos",			"0"			},

  { "custom_13",				"RocksCE.png"		},
  { "custom_13.xpos",				"12"			},
  { "custom_13.ypos",				"0"			},
  { "custom_13.frames",				"1"			},
  { "custom_13.EDITOR",				"RocksCE.png"		},
  { "custom_13.EDITOR.xpos",			"28"			},
  { "custom_13.EDITOR.ypos",			"0"			},

  { "custom_14",				"RocksCE.png"		},
  { "custom_14.xpos",				"13"			},
  { "custom_14.ypos",				"0"			},
  { "custom_14.frames",				"1"			},
  { "custom_14.EDITOR",				"RocksCE.png"		},
  { "custom_14.EDITOR.xpos",			"29"			},
  { "custom_14.EDITOR.ypos",			"0"			},

  { "custom_15",				"RocksCE.png"		},
  { "custom_15.xpos",				"14"			},
  { "custom_15.ypos",				"0"			},
  { "custom_15.frames",				"1"			},
  { "custom_15.EDITOR",				"RocksCE.png"		},
  { "custom_15.EDITOR.xpos",			"30"			},
  { "custom_15.EDITOR.ypos",			"0"			},

  { "custom_16",				"RocksCE.png"		},
  { "custom_16.xpos",				"15"			},
  { "custom_16.ypos",				"0"			},
  { "custom_16.frames",				"1"			},
  { "custom_16.EDITOR",				"RocksCE.png"		},
  { "custom_16.EDITOR.xpos",			"31"			},
  { "custom_16.EDITOR.ypos",			"0"			},

  { "custom_17",				"RocksCE.png"		},
  { "custom_17.xpos",				"0"			},
  { "custom_17.ypos",				"1"			},
  { "custom_17.frames",				"1"			},
  { "custom_17.EDITOR",				"RocksCE.png"		},
  { "custom_17.EDITOR.xpos",			"16"			},
  { "custom_17.EDITOR.ypos",			"1"			},

  { "custom_18",				"RocksCE.png"		},
  { "custom_18.xpos",				"1"			},
  { "custom_18.ypos",				"1"			},
  { "custom_18.frames",				"1"			},
  { "custom_18.EDITOR",				"RocksCE.png"		},
  { "custom_18.EDITOR.xpos",			"17"			},
  { "custom_18.EDITOR.ypos",			"1"			},

  { "custom_19",				"RocksCE.png"		},
  { "custom_19.xpos",				"2"			},
  { "custom_19.ypos",				"1"			},
  { "custom_19.frames",				"1"			},
  { "custom_19.EDITOR",				"RocksCE.png"		},
  { "custom_19.EDITOR.xpos",			"18"			},
  { "custom_19.EDITOR.ypos",			"1"			},

  { "custom_20",				"RocksCE.png"		},
  { "custom_20.xpos",				"3"			},
  { "custom_20.ypos",				"1"			},
  { "custom_20.frames",				"1"			},
  { "custom_20.EDITOR",				"RocksCE.png"		},
  { "custom_20.EDITOR.xpos",			"19"			},
  { "custom_20.EDITOR.ypos",			"1"			},

  { "custom_21",				"RocksCE.png"		},
  { "custom_21.xpos",				"4"			},
  { "custom_21.ypos",				"1"			},
  { "custom_21.frames",				"1"			},
  { "custom_21.EDITOR",				"RocksCE.png"		},
  { "custom_21.EDITOR.xpos",			"20"			},
  { "custom_21.EDITOR.ypos",			"1"			},

  { "custom_22",				"RocksCE.png"		},
  { "custom_22.xpos",				"5"			},
  { "custom_22.ypos",				"1"			},
  { "custom_22.frames",				"1"			},
  { "custom_22.EDITOR",				"RocksCE.png"		},
  { "custom_22.EDITOR.xpos",			"21"			},
  { "custom_22.EDITOR.ypos",			"1"			},

  { "custom_23",				"RocksCE.png"		},
  { "custom_23.xpos",				"6"			},
  { "custom_23.ypos",				"1"			},
  { "custom_23.frames",				"1"			},
  { "custom_23.EDITOR",				"RocksCE.png"		},
  { "custom_23.EDITOR.xpos",			"22"			},
  { "custom_23.EDITOR.ypos",			"1"			},

  { "custom_24",				"RocksCE.png"		},
  { "custom_24.xpos",				"7"			},
  { "custom_24.ypos",				"1"			},
  { "custom_24.frames",				"1"			},
  { "custom_24.EDITOR",				"RocksCE.png"		},
  { "custom_24.EDITOR.xpos",			"23"			},
  { "custom_24.EDITOR.ypos",			"1"			},

  { "custom_25",				"RocksCE.png"		},
  { "custom_25.xpos",				"8"			},
  { "custom_25.ypos",				"1"			},
  { "custom_25.frames",				"1"			},
  { "custom_25.EDITOR",				"RocksCE.png"		},
  { "custom_25.EDITOR.xpos",			"24"			},
  { "custom_25.EDITOR.ypos",			"1"			},

  { "custom_26",				"RocksCE.png"		},
  { "custom_26.xpos",				"9"			},
  { "custom_26.ypos",				"1"			},
  { "custom_26.frames",				"1"			},
  { "custom_26.EDITOR",				"RocksCE.png"		},
  { "custom_26.EDITOR.xpos",			"25"			},
  { "custom_26.EDITOR.ypos",			"1"			},

  { "custom_27",				"RocksCE.png"		},
  { "custom_27.xpos",				"10"			},
  { "custom_27.ypos",				"1"			},
  { "custom_27.frames",				"1"			},
  { "custom_27.EDITOR",				"RocksCE.png"		},
  { "custom_27.EDITOR.xpos",			"26"			},
  { "custom_27.EDITOR.ypos",			"1"			},

  { "custom_28",				"RocksCE.png"		},
  { "custom_28.xpos",				"11"			},
  { "custom_28.ypos",				"1"			},
  { "custom_28.frames",				"1"			},
  { "custom_28.EDITOR",				"RocksCE.png"		},
  { "custom_28.EDITOR.xpos",			"27"			},
  { "custom_28.EDITOR.ypos",			"1"			},

  { "custom_29",				"RocksCE.png"		},
  { "custom_29.xpos",				"12"			},
  { "custom_29.ypos",				"1"			},
  { "custom_29.frames",				"1"			},
  { "custom_29.EDITOR",				"RocksCE.png"		},
  { "custom_29.EDITOR.xpos",			"28"			},
  { "custom_29.EDITOR.ypos",			"1"			},

  { "custom_30",				"RocksCE.png"		},
  { "custom_30.xpos",				"13"			},
  { "custom_30.ypos",				"1"			},
  { "custom_30.frames",				"1"			},
  { "custom_30.EDITOR",				"RocksCE.png"		},
  { "custom_30.EDITOR.xpos",			"29"			},
  { "custom_30.EDITOR.ypos",			"1"			},

  { "custom_31",				"RocksCE.png"		},
  { "custom_31.xpos",				"14"			},
  { "custom_31.ypos",				"1"			},
  { "custom_31.frames",				"1"			},
  { "custom_31.EDITOR",				"RocksCE.png"		},
  { "custom_31.EDITOR.xpos",			"30"			},
  { "custom_31.EDITOR.ypos",			"1"			},

  { "custom_32",				"RocksCE.png"		},
  { "custom_32.xpos",				"15"			},
  { "custom_32.ypos",				"1"			},
  { "custom_32.frames",				"1"			},
  { "custom_32.EDITOR",				"RocksCE.png"		},
  { "custom_32.EDITOR.xpos",			"31"			},
  { "custom_32.EDITOR.ypos",			"1"			},

  { "custom_33",				"RocksCE.png"		},
  { "custom_33.xpos",				"0"			},
  { "custom_33.ypos",				"2"			},
  { "custom_33.frames",				"1"			},
  { "custom_33.EDITOR",				"RocksCE.png"		},
  { "custom_33.EDITOR.xpos",			"16"			},
  { "custom_33.EDITOR.ypos",			"2"			},

  { "custom_34",				"RocksCE.png"		},
  { "custom_34.xpos",				"1"			},
  { "custom_34.ypos",				"2"			},
  { "custom_34.frames",				"1"			},
  { "custom_34.EDITOR",				"RocksCE.png"		},
  { "custom_34.EDITOR.xpos",			"17"			},
  { "custom_34.EDITOR.ypos",			"2"			},

  { "custom_35",				"RocksCE.png"		},
  { "custom_35.xpos",				"2"			},
  { "custom_35.ypos",				"2"			},
  { "custom_35.frames",				"1"			},
  { "custom_35.EDITOR",				"RocksCE.png"		},
  { "custom_35.EDITOR.xpos",			"18"			},
  { "custom_35.EDITOR.ypos",			"2"			},

  { "custom_36",				"RocksCE.png"		},
  { "custom_36.xpos",				"3"			},
  { "custom_36.ypos",				"2"			},
  { "custom_36.frames",				"1"			},
  { "custom_36.EDITOR",				"RocksCE.png"		},
  { "custom_36.EDITOR.xpos",			"19"			},
  { "custom_36.EDITOR.ypos",			"2"			},

  { "custom_37",				"RocksCE.png"		},
  { "custom_37.xpos",				"4"			},
  { "custom_37.ypos",				"2"			},
  { "custom_37.frames",				"1"			},
  { "custom_37.EDITOR",				"RocksCE.png"		},
  { "custom_37.EDITOR.xpos",			"20"			},
  { "custom_37.EDITOR.ypos",			"2"			},

  { "custom_38",				"RocksCE.png"		},
  { "custom_38.xpos",				"5"			},
  { "custom_38.ypos",				"2"			},
  { "custom_38.frames",				"1"			},
  { "custom_38.EDITOR",				"RocksCE.png"		},
  { "custom_38.EDITOR.xpos",			"21"			},
  { "custom_38.EDITOR.ypos",			"2"			},

  { "custom_39",				"RocksCE.png"		},
  { "custom_39.xpos",				"6"			},
  { "custom_39.ypos",				"2"			},
  { "custom_39.frames",				"1"			},
  { "custom_39.EDITOR",				"RocksCE.png"		},
  { "custom_39.EDITOR.xpos",			"22"			},
  { "custom_39.EDITOR.ypos",			"2"			},

  { "custom_40",				"RocksCE.png"		},
  { "custom_40.xpos",				"7"			},
  { "custom_40.ypos",				"2"			},
  { "custom_40.frames",				"1"			},
  { "custom_40.EDITOR",				"RocksCE.png"		},
  { "custom_40.EDITOR.xpos",			"23"			},
  { "custom_40.EDITOR.ypos",			"2"			},

  { "custom_41",				"RocksCE.png"		},
  { "custom_41.xpos",				"8"			},
  { "custom_41.ypos",				"2"			},
  { "custom_41.frames",				"1"			},
  { "custom_41.EDITOR",				"RocksCE.png"		},
  { "custom_41.EDITOR.xpos",			"24"			},
  { "custom_41.EDITOR.ypos",			"2"			},

  { "custom_42",				"RocksCE.png"		},
  { "custom_42.xpos",				"9"			},
  { "custom_42.ypos",				"2"			},
  { "custom_42.frames",				"1"			},
  { "custom_42.EDITOR",				"RocksCE.png"		},
  { "custom_42.EDITOR.xpos",			"25"			},
  { "custom_42.EDITOR.ypos",			"2"			},

  { "custom_43",				"RocksCE.png"		},
  { "custom_43.xpos",				"10"			},
  { "custom_43.ypos",				"2"			},
  { "custom_43.frames",				"1"			},
  { "custom_43.EDITOR",				"RocksCE.png"		},
  { "custom_43.EDITOR.xpos",			"26"			},
  { "custom_43.EDITOR.ypos",			"2"			},

  { "custom_44",				"RocksCE.png"		},
  { "custom_44.xpos",				"11"			},
  { "custom_44.ypos",				"2"			},
  { "custom_44.frames",				"1"			},
  { "custom_44.EDITOR",				"RocksCE.png"		},
  { "custom_44.EDITOR.xpos",			"27"			},
  { "custom_44.EDITOR.ypos",			"2"			},

  { "custom_45",				"RocksCE.png"		},
  { "custom_45.xpos",				"12"			},
  { "custom_45.ypos",				"2"			},
  { "custom_45.frames",				"1"			},
  { "custom_45.EDITOR",				"RocksCE.png"		},
  { "custom_45.EDITOR.xpos",			"28"			},
  { "custom_45.EDITOR.ypos",			"2"			},

  { "custom_46",				"RocksCE.png"		},
  { "custom_46.xpos",				"13"			},
  { "custom_46.ypos",				"2"			},
  { "custom_46.frames",				"1"			},
  { "custom_46.EDITOR",				"RocksCE.png"		},
  { "custom_46.EDITOR.xpos",			"29"			},
  { "custom_46.EDITOR.ypos",			"2"			},

  { "custom_47",				"RocksCE.png"		},
  { "custom_47.xpos",				"14"			},
  { "custom_47.ypos",				"2"			},
  { "custom_47.frames",				"1"			},
  { "custom_47.EDITOR",				"RocksCE.png"		},
  { "custom_47.EDITOR.xpos",			"30"			},
  { "custom_47.EDITOR.ypos",			"2"			},

  { "custom_48",				"RocksCE.png"		},
  { "custom_48.xpos",				"15"			},
  { "custom_48.ypos",				"2"			},
  { "custom_48.frames",				"1"			},
  { "custom_48.EDITOR",				"RocksCE.png"		},
  { "custom_48.EDITOR.xpos",			"31"			},
  { "custom_48.EDITOR.ypos",			"2"			},

  { "custom_49",				"RocksCE.png"		},
  { "custom_49.xpos",				"0"			},
  { "custom_49.ypos",				"3"			},
  { "custom_49.frames",				"1"			},
  { "custom_49.EDITOR",				"RocksCE.png"		},
  { "custom_49.EDITOR.xpos",			"16"			},
  { "custom_49.EDITOR.ypos",			"3"			},

  { "custom_50",				"RocksCE.png"		},
  { "custom_50.xpos",				"1"			},
  { "custom_50.ypos",				"3"			},
  { "custom_50.frames",				"1"			},
  { "custom_50.EDITOR",				"RocksCE.png"		},
  { "custom_50.EDITOR.xpos",			"17"			},
  { "custom_50.EDITOR.ypos",			"3"			},

  { "custom_51",				"RocksCE.png"		},
  { "custom_51.xpos",				"2"			},
  { "custom_51.ypos",				"3"			},
  { "custom_51.frames",				"1"			},
  { "custom_51.EDITOR",				"RocksCE.png"		},
  { "custom_51.EDITOR.xpos",			"18"			},
  { "custom_51.EDITOR.ypos",			"3"			},

  { "custom_52",				"RocksCE.png"		},
  { "custom_52.xpos",				"3"			},
  { "custom_52.ypos",				"3"			},
  { "custom_52.frames",				"1"			},
  { "custom_52.EDITOR",				"RocksCE.png"		},
  { "custom_52.EDITOR.xpos",			"19"			},
  { "custom_52.EDITOR.ypos",			"3"			},

  { "custom_53",				"RocksCE.png"		},
  { "custom_53.xpos",				"4"			},
  { "custom_53.ypos",				"3"			},
  { "custom_53.frames",				"1"			},
  { "custom_53.EDITOR",				"RocksCE.png"		},
  { "custom_53.EDITOR.xpos",			"20"			},
  { "custom_53.EDITOR.ypos",			"3"			},

  { "custom_54",				"RocksCE.png"		},
  { "custom_54.xpos",				"5"			},
  { "custom_54.ypos",				"3"			},
  { "custom_54.frames",				"1"			},
  { "custom_54.EDITOR",				"RocksCE.png"		},
  { "custom_54.EDITOR.xpos",			"21"			},
  { "custom_54.EDITOR.ypos",			"3"			},

  { "custom_55",				"RocksCE.png"		},
  { "custom_55.xpos",				"6"			},
  { "custom_55.ypos",				"3"			},
  { "custom_55.frames",				"1"			},
  { "custom_55.EDITOR",				"RocksCE.png"		},
  { "custom_55.EDITOR.xpos",			"22"			},
  { "custom_55.EDITOR.ypos",			"3"			},

  { "custom_56",				"RocksCE.png"		},
  { "custom_56.xpos",				"7"			},
  { "custom_56.ypos",				"3"			},
  { "custom_56.frames",				"1"			},
  { "custom_56.EDITOR",				"RocksCE.png"		},
  { "custom_56.EDITOR.xpos",			"23"			},
  { "custom_56.EDITOR.ypos",			"3"			},

  { "custom_57",				"RocksCE.png"		},
  { "custom_57.xpos",				"8"			},
  { "custom_57.ypos",				"3"			},
  { "custom_57.frames",				"1"			},
  { "custom_57.EDITOR",				"RocksCE.png"		},
  { "custom_57.EDITOR.xpos",			"24"			},
  { "custom_57.EDITOR.ypos",			"3"			},

  { "custom_58",				"RocksCE.png"		},
  { "custom_58.xpos",				"9"			},
  { "custom_58.ypos",				"3"			},
  { "custom_58.frames",				"1"			},
  { "custom_58.EDITOR",				"RocksCE.png"		},
  { "custom_58.EDITOR.xpos",			"25"			},
  { "custom_58.EDITOR.ypos",			"3"			},

  { "custom_59",				"RocksCE.png"		},
  { "custom_59.xpos",				"10"			},
  { "custom_59.ypos",				"3"			},
  { "custom_59.frames",				"1"			},
  { "custom_59.EDITOR",				"RocksCE.png"		},
  { "custom_59.EDITOR.xpos",			"26"			},
  { "custom_59.EDITOR.ypos",			"3"			},

  { "custom_60",				"RocksCE.png"		},
  { "custom_60.xpos",				"11"			},
  { "custom_60.ypos",				"3"			},
  { "custom_60.frames",				"1"			},
  { "custom_60.EDITOR",				"RocksCE.png"		},
  { "custom_60.EDITOR.xpos",			"27"			},
  { "custom_60.EDITOR.ypos",			"3"			},

  { "custom_61",				"RocksCE.png"		},
  { "custom_61.xpos",				"12"			},
  { "custom_61.ypos",				"3"			},
  { "custom_61.frames",				"1"			},
  { "custom_61.EDITOR",				"RocksCE.png"		},
  { "custom_61.EDITOR.xpos",			"28"			},
  { "custom_61.EDITOR.ypos",			"3"			},

  { "custom_62",				"RocksCE.png"		},
  { "custom_62.xpos",				"13"			},
  { "custom_62.ypos",				"3"			},
  { "custom_62.frames",				"1"			},
  { "custom_62.EDITOR",				"RocksCE.png"		},
  { "custom_62.EDITOR.xpos",			"29"			},
  { "custom_62.EDITOR.ypos",			"3"			},

  { "custom_63",				"RocksCE.png"		},
  { "custom_63.xpos",				"14"			},
  { "custom_63.ypos",				"3"			},
  { "custom_63.frames",				"1"			},
  { "custom_63.EDITOR",				"RocksCE.png"		},
  { "custom_63.EDITOR.xpos",			"30"			},
  { "custom_63.EDITOR.ypos",			"3"			},

  { "custom_64",				"RocksCE.png"		},
  { "custom_64.xpos",				"15"			},
  { "custom_64.ypos",				"3"			},
  { "custom_64.frames",				"1"			},
  { "custom_64.EDITOR",				"RocksCE.png"		},
  { "custom_64.EDITOR.xpos",			"31"			},
  { "custom_64.EDITOR.ypos",			"3"			},

  { "custom_65",				"RocksCE.png"		},
  { "custom_65.xpos",				"0"			},
  { "custom_65.ypos",				"4"			},
  { "custom_65.frames",				"1"			},
  { "custom_65.EDITOR",				"RocksCE.png"		},
  { "custom_65.EDITOR.xpos",			"16"			},
  { "custom_65.EDITOR.ypos",			"4"			},

  { "custom_66",				"RocksCE.png"		},
  { "custom_66.xpos",				"1"			},
  { "custom_66.ypos",				"4"			},
  { "custom_66.frames",				"1"			},
  { "custom_66.EDITOR",				"RocksCE.png"		},
  { "custom_66.EDITOR.xpos",			"17"			},
  { "custom_66.EDITOR.ypos",			"4"			},

  { "custom_67",				"RocksCE.png"		},
  { "custom_67.xpos",				"2"			},
  { "custom_67.ypos",				"4"			},
  { "custom_67.frames",				"1"			},
  { "custom_67.EDITOR",				"RocksCE.png"		},
  { "custom_67.EDITOR.xpos",			"18"			},
  { "custom_67.EDITOR.ypos",			"4"			},

  { "custom_68",				"RocksCE.png"		},
  { "custom_68.xpos",				"3"			},
  { "custom_68.ypos",				"4"			},
  { "custom_68.frames",				"1"			},
  { "custom_68.EDITOR",				"RocksCE.png"		},
  { "custom_68.EDITOR.xpos",			"19"			},
  { "custom_68.EDITOR.ypos",			"4"			},

  { "custom_69",				"RocksCE.png"		},
  { "custom_69.xpos",				"4"			},
  { "custom_69.ypos",				"4"			},
  { "custom_69.frames",				"1"			},
  { "custom_69.EDITOR",				"RocksCE.png"		},
  { "custom_69.EDITOR.xpos",			"20"			},
  { "custom_69.EDITOR.ypos",			"4"			},

  { "custom_70",				"RocksCE.png"		},
  { "custom_70.xpos",				"5"			},
  { "custom_70.ypos",				"4"			},
  { "custom_70.frames",				"1"			},
  { "custom_70.EDITOR",				"RocksCE.png"		},
  { "custom_70.EDITOR.xpos",			"21"			},
  { "custom_70.EDITOR.ypos",			"4"			},

  { "custom_71",				"RocksCE.png"		},
  { "custom_71.xpos",				"6"			},
  { "custom_71.ypos",				"4"			},
  { "custom_71.frames",				"1"			},
  { "custom_71.EDITOR",				"RocksCE.png"		},
  { "custom_71.EDITOR.xpos",			"22"			},
  { "custom_71.EDITOR.ypos",			"4"			},

  { "custom_72",				"RocksCE.png"		},
  { "custom_72.xpos",				"7"			},
  { "custom_72.ypos",				"4"			},
  { "custom_72.frames",				"1"			},
  { "custom_72.EDITOR",				"RocksCE.png"		},
  { "custom_72.EDITOR.xpos",			"23"			},
  { "custom_72.EDITOR.ypos",			"4"			},

  { "custom_73",				"RocksCE.png"		},
  { "custom_73.xpos",				"8"			},
  { "custom_73.ypos",				"4"			},
  { "custom_73.frames",				"1"			},
  { "custom_73.EDITOR",				"RocksCE.png"		},
  { "custom_73.EDITOR.xpos",			"24"			},
  { "custom_73.EDITOR.ypos",			"4"			},

  { "custom_74",				"RocksCE.png"		},
  { "custom_74.xpos",				"9"			},
  { "custom_74.ypos",				"4"			},
  { "custom_74.frames",				"1"			},
  { "custom_74.EDITOR",				"RocksCE.png"		},
  { "custom_74.EDITOR.xpos",			"25"			},
  { "custom_74.EDITOR.ypos",			"4"			},

  { "custom_75",				"RocksCE.png"		},
  { "custom_75.xpos",				"10"			},
  { "custom_75.ypos",				"4"			},
  { "custom_75.frames",				"1"			},
  { "custom_75.EDITOR",				"RocksCE.png"		},
  { "custom_75.EDITOR.xpos",			"26"			},
  { "custom_75.EDITOR.ypos",			"4"			},

  { "custom_76",				"RocksCE.png"		},
  { "custom_76.xpos",				"11"			},
  { "custom_76.ypos",				"4"			},
  { "custom_76.frames",				"1"			},
  { "custom_76.EDITOR",				"RocksCE.png"		},
  { "custom_76.EDITOR.xpos",			"27"			},
  { "custom_76.EDITOR.ypos",			"4"			},

  { "custom_77",				"RocksCE.png"		},
  { "custom_77.xpos",				"12"			},
  { "custom_77.ypos",				"4"			},
  { "custom_77.frames",				"1"			},
  { "custom_77.EDITOR",				"RocksCE.png"		},
  { "custom_77.EDITOR.xpos",			"28"			},
  { "custom_77.EDITOR.ypos",			"4"			},

  { "custom_78",				"RocksCE.png"		},
  { "custom_78.xpos",				"13"			},
  { "custom_78.ypos",				"4"			},
  { "custom_78.frames",				"1"			},
  { "custom_78.EDITOR",				"RocksCE.png"		},
  { "custom_78.EDITOR.xpos",			"29"			},
  { "custom_78.EDITOR.ypos",			"4"			},

  { "custom_79",				"RocksCE.png"		},
  { "custom_79.xpos",				"14"			},
  { "custom_79.ypos",				"4"			},
  { "custom_79.frames",				"1"			},
  { "custom_79.EDITOR",				"RocksCE.png"		},
  { "custom_79.EDITOR.xpos",			"30"			},
  { "custom_79.EDITOR.ypos",			"4"			},

  { "custom_80",				"RocksCE.png"		},
  { "custom_80.xpos",				"15"			},
  { "custom_80.ypos",				"4"			},
  { "custom_80.frames",				"1"			},
  { "custom_80.EDITOR",				"RocksCE.png"		},
  { "custom_80.EDITOR.xpos",			"31"			},
  { "custom_80.EDITOR.ypos",			"4"			},

  { "custom_81",				"RocksCE.png"		},
  { "custom_81.xpos",				"0"			},
  { "custom_81.ypos",				"5"			},
  { "custom_81.frames",				"1"			},
  { "custom_81.EDITOR",				"RocksCE.png"		},
  { "custom_81.EDITOR.xpos",			"16"			},
  { "custom_81.EDITOR.ypos",			"5"			},

  { "custom_82",				"RocksCE.png"		},
  { "custom_82.xpos",				"1"			},
  { "custom_82.ypos",				"5"			},
  { "custom_82.frames",				"1"			},
  { "custom_82.EDITOR",				"RocksCE.png"		},
  { "custom_82.EDITOR.xpos",			"17"			},
  { "custom_82.EDITOR.ypos",			"5"			},

  { "custom_83",				"RocksCE.png"		},
  { "custom_83.xpos",				"2"			},
  { "custom_83.ypos",				"5"			},
  { "custom_83.frames",				"1"			},
  { "custom_83.EDITOR",				"RocksCE.png"		},
  { "custom_83.EDITOR.xpos",			"18"			},
  { "custom_83.EDITOR.ypos",			"5"			},

  { "custom_84",				"RocksCE.png"		},
  { "custom_84.xpos",				"3"			},
  { "custom_84.ypos",				"5"			},
  { "custom_84.frames",				"1"			},
  { "custom_84.EDITOR",				"RocksCE.png"		},
  { "custom_84.EDITOR.xpos",			"19"			},
  { "custom_84.EDITOR.ypos",			"5"			},

  { "custom_85",				"RocksCE.png"		},
  { "custom_85.xpos",				"4"			},
  { "custom_85.ypos",				"5"			},
  { "custom_85.frames",				"1"			},
  { "custom_85.EDITOR",				"RocksCE.png"		},
  { "custom_85.EDITOR.xpos",			"20"			},
  { "custom_85.EDITOR.ypos",			"5"			},

  { "custom_86",				"RocksCE.png"		},
  { "custom_86.xpos",				"5"			},
  { "custom_86.ypos",				"5"			},
  { "custom_86.frames",				"1"			},
  { "custom_86.EDITOR",				"RocksCE.png"		},
  { "custom_86.EDITOR.xpos",			"21"			},
  { "custom_86.EDITOR.ypos",			"5"			},

  { "custom_87",				"RocksCE.png"		},
  { "custom_87.xpos",				"6"			},
  { "custom_87.ypos",				"5"			},
  { "custom_87.frames",				"1"			},
  { "custom_87.EDITOR",				"RocksCE.png"		},
  { "custom_87.EDITOR.xpos",			"22"			},
  { "custom_87.EDITOR.ypos",			"5"			},

  { "custom_88",				"RocksCE.png"		},
  { "custom_88.xpos",				"7"			},
  { "custom_88.ypos",				"5"			},
  { "custom_88.frames",				"1"			},
  { "custom_88.EDITOR",				"RocksCE.png"		},
  { "custom_88.EDITOR.xpos",			"23"			},
  { "custom_88.EDITOR.ypos",			"5"			},

  { "custom_89",				"RocksCE.png"		},
  { "custom_89.xpos",				"8"			},
  { "custom_89.ypos",				"5"			},
  { "custom_89.frames",				"1"			},
  { "custom_89.EDITOR",				"RocksCE.png"		},
  { "custom_89.EDITOR.xpos",			"24"			},
  { "custom_89.EDITOR.ypos",			"5"			},

  { "custom_90",				"RocksCE.png"		},
  { "custom_90.xpos",				"9"			},
  { "custom_90.ypos",				"5"			},
  { "custom_90.frames",				"1"			},
  { "custom_90.EDITOR",				"RocksCE.png"		},
  { "custom_90.EDITOR.xpos",			"25"			},
  { "custom_90.EDITOR.ypos",			"5"			},

  { "custom_91",				"RocksCE.png"		},
  { "custom_91.xpos",				"10"			},
  { "custom_91.ypos",				"5"			},
  { "custom_91.frames",				"1"			},
  { "custom_91.EDITOR",				"RocksCE.png"		},
  { "custom_91.EDITOR.xpos",			"26"			},
  { "custom_91.EDITOR.ypos",			"5"			},

  { "custom_92",				"RocksCE.png"		},
  { "custom_92.xpos",				"11"			},
  { "custom_92.ypos",				"5"			},
  { "custom_92.frames",				"1"			},
  { "custom_92.EDITOR",				"RocksCE.png"		},
  { "custom_92.EDITOR.xpos",			"27"			},
  { "custom_92.EDITOR.ypos",			"5"			},

  { "custom_93",				"RocksCE.png"		},
  { "custom_93.xpos",				"12"			},
  { "custom_93.ypos",				"5"			},
  { "custom_93.frames",				"1"			},
  { "custom_93.EDITOR",				"RocksCE.png"		},
  { "custom_93.EDITOR.xpos",			"28"			},
  { "custom_93.EDITOR.ypos",			"5"			},

  { "custom_94",				"RocksCE.png"		},
  { "custom_94.xpos",				"13"			},
  { "custom_94.ypos",				"5"			},
  { "custom_94.frames",				"1"			},
  { "custom_94.EDITOR",				"RocksCE.png"		},
  { "custom_94.EDITOR.xpos",			"29"			},
  { "custom_94.EDITOR.ypos",			"5"			},

  { "custom_95",				"RocksCE.png"		},
  { "custom_95.xpos",				"14"			},
  { "custom_95.ypos",				"5"			},
  { "custom_95.frames",				"1"			},
  { "custom_95.EDITOR",				"RocksCE.png"		},
  { "custom_95.EDITOR.xpos",			"30"			},
  { "custom_95.EDITOR.ypos",			"5"			},

  { "custom_96",				"RocksCE.png"		},
  { "custom_96.xpos",				"15"			},
  { "custom_96.ypos",				"5"			},
  { "custom_96.frames",				"1"			},
  { "custom_96.EDITOR",				"RocksCE.png"		},
  { "custom_96.EDITOR.xpos",			"31"			},
  { "custom_96.EDITOR.ypos",			"5"			},

  { "custom_97",				"RocksCE.png"		},
  { "custom_97.xpos",				"0"			},
  { "custom_97.ypos",				"6"			},
  { "custom_97.frames",				"1"			},
  { "custom_97.EDITOR",				"RocksCE.png"		},
  { "custom_97.EDITOR.xpos",			"16"			},
  { "custom_97.EDITOR.ypos",			"6"			},

  { "custom_98",				"RocksCE.png"		},
  { "custom_98.xpos",				"1"			},
  { "custom_98.ypos",				"6"			},
  { "custom_98.frames",				"1"			},
  { "custom_98.EDITOR",				"RocksCE.png"		},
  { "custom_98.EDITOR.xpos",			"17"			},
  { "custom_98.EDITOR.ypos",			"6"			},

  { "custom_99",				"RocksCE.png"		},
  { "custom_99.xpos",				"2"			},
  { "custom_99.ypos",				"6"			},
  { "custom_99.frames",				"1"			},
  { "custom_99.EDITOR",				"RocksCE.png"		},
  { "custom_99.EDITOR.xpos",			"18"			},
  { "custom_99.EDITOR.ypos",			"6"			},

  { "custom_100",				"RocksCE.png"		},
  { "custom_100.xpos",				"3"			},
  { "custom_100.ypos",				"6"			},
  { "custom_100.frames",			"1"			},
  { "custom_100.EDITOR",			"RocksCE.png"		},
  { "custom_100.EDITOR.xpos",			"19"			},
  { "custom_100.EDITOR.ypos",			"6"			},

  { "custom_101",				"RocksCE.png"		},
  { "custom_101.xpos",				"4"			},
  { "custom_101.ypos",				"6"			},
  { "custom_101.frames",			"1"			},
  { "custom_101.EDITOR",			"RocksCE.png"		},
  { "custom_101.EDITOR.xpos",			"20"			},
  { "custom_101.EDITOR.ypos",			"6"			},

  { "custom_102",				"RocksCE.png"		},
  { "custom_102.xpos",				"5"			},
  { "custom_102.ypos",				"6"			},
  { "custom_102.frames",			"1"			},
  { "custom_102.EDITOR",			"RocksCE.png"		},
  { "custom_102.EDITOR.xpos",			"21"			},
  { "custom_102.EDITOR.ypos",			"6"			},

  { "custom_103",				"RocksCE.png"		},
  { "custom_103.xpos",				"6"			},
  { "custom_103.ypos",				"6"			},
  { "custom_103.frames",			"1"			},
  { "custom_103.EDITOR",			"RocksCE.png"		},
  { "custom_103.EDITOR.xpos",			"22"			},
  { "custom_103.EDITOR.ypos",			"6"			},

  { "custom_104",				"RocksCE.png"		},
  { "custom_104.xpos",				"7"			},
  { "custom_104.ypos",				"6"			},
  { "custom_104.frames",			"1"			},
  { "custom_104.EDITOR",			"RocksCE.png"		},
  { "custom_104.EDITOR.xpos",			"23"			},
  { "custom_104.EDITOR.ypos",			"6"			},

  { "custom_105",				"RocksCE.png"		},
  { "custom_105.xpos",				"8"			},
  { "custom_105.ypos",				"6"			},
  { "custom_105.frames",			"1"			},
  { "custom_105.EDITOR",			"RocksCE.png"		},
  { "custom_105.EDITOR.xpos",			"24"			},
  { "custom_105.EDITOR.ypos",			"6"			},

  { "custom_106",				"RocksCE.png"		},
  { "custom_106.xpos",				"9"			},
  { "custom_106.ypos",				"6"			},
  { "custom_106.frames",			"1"			},
  { "custom_106.EDITOR",			"RocksCE.png"		},
  { "custom_106.EDITOR.xpos",			"25"			},
  { "custom_106.EDITOR.ypos",			"6"			},

  { "custom_107",				"RocksCE.png"		},
  { "custom_107.xpos",				"10"			},
  { "custom_107.ypos",				"6"			},
  { "custom_107.frames",			"1"			},
  { "custom_107.EDITOR",			"RocksCE.png"		},
  { "custom_107.EDITOR.xpos",			"26"			},
  { "custom_107.EDITOR.ypos",			"6"			},

  { "custom_108",				"RocksCE.png"		},
  { "custom_108.xpos",				"11"			},
  { "custom_108.ypos",				"6"			},
  { "custom_108.frames",			"1"			},
  { "custom_108.EDITOR",			"RocksCE.png"		},
  { "custom_108.EDITOR.xpos",			"27"			},
  { "custom_108.EDITOR.ypos",			"6"			},

  { "custom_109",				"RocksCE.png"		},
  { "custom_109.xpos",				"12"			},
  { "custom_109.ypos",				"6"			},
  { "custom_109.frames",			"1"			},
  { "custom_109.EDITOR",			"RocksCE.png"		},
  { "custom_109.EDITOR.xpos",			"28"			},
  { "custom_109.EDITOR.ypos",			"6"			},

  { "custom_110",				"RocksCE.png"		},
  { "custom_110.xpos",				"13"			},
  { "custom_110.ypos",				"6"			},
  { "custom_110.frames",			"1"			},
  { "custom_110.EDITOR",			"RocksCE.png"		},
  { "custom_110.EDITOR.xpos",			"29"			},
  { "custom_110.EDITOR.ypos",			"6"			},

  { "custom_111",				"RocksCE.png"		},
  { "custom_111.xpos",				"14"			},
  { "custom_111.ypos",				"6"			},
  { "custom_111.frames",			"1"			},
  { "custom_111.EDITOR",			"RocksCE.png"		},
  { "custom_111.EDITOR.xpos",			"30"			},
  { "custom_111.EDITOR.ypos",			"6"			},

  { "custom_112",				"RocksCE.png"		},
  { "custom_112.xpos",				"15"			},
  { "custom_112.ypos",				"6"			},
  { "custom_112.frames",			"1"			},
  { "custom_112.EDITOR",			"RocksCE.png"		},
  { "custom_112.EDITOR.xpos",			"31"			},
  { "custom_112.EDITOR.ypos",			"6"			},

  { "custom_113",				"RocksCE.png"		},
  { "custom_113.xpos",				"0"			},
  { "custom_113.ypos",				"7"			},
  { "custom_113.frames",			"1"			},
  { "custom_113.EDITOR",			"RocksCE.png"		},
  { "custom_113.EDITOR.xpos",			"16"			},
  { "custom_113.EDITOR.ypos",			"7"			},

  { "custom_114",				"RocksCE.png"		},
  { "custom_114.xpos",				"1"			},
  { "custom_114.ypos",				"7"			},
  { "custom_114.frames",			"1"			},
  { "custom_114.EDITOR",			"RocksCE.png"		},
  { "custom_114.EDITOR.xpos",			"17"			},
  { "custom_114.EDITOR.ypos",			"7"			},

  { "custom_115",				"RocksCE.png"		},
  { "custom_115.xpos",				"2"			},
  { "custom_115.ypos",				"7"			},
  { "custom_115.frames",			"1"			},
  { "custom_115.EDITOR",			"RocksCE.png"		},
  { "custom_115.EDITOR.xpos",			"18"			},
  { "custom_115.EDITOR.ypos",			"7"			},

  { "custom_116",				"RocksCE.png"		},
  { "custom_116.xpos",				"3"			},
  { "custom_116.ypos",				"7"			},
  { "custom_116.frames",			"1"			},
  { "custom_116.EDITOR",			"RocksCE.png"		},
  { "custom_116.EDITOR.xpos",			"19"			},
  { "custom_116.EDITOR.ypos",			"7"			},

  { "custom_117",				"RocksCE.png"		},
  { "custom_117.xpos",				"4"			},
  { "custom_117.ypos",				"7"			},
  { "custom_117.frames",			"1"			},
  { "custom_117.EDITOR",			"RocksCE.png"		},
  { "custom_117.EDITOR.xpos",			"20"			},
  { "custom_117.EDITOR.ypos",			"7"			},

  { "custom_118",				"RocksCE.png"		},
  { "custom_118.xpos",				"5"			},
  { "custom_118.ypos",				"7"			},
  { "custom_118.frames",			"1"			},
  { "custom_118.EDITOR",			"RocksCE.png"		},
  { "custom_118.EDITOR.xpos",			"21"			},
  { "custom_118.EDITOR.ypos",			"7"			},

  { "custom_119",				"RocksCE.png"		},
  { "custom_119.xpos",				"6"			},
  { "custom_119.ypos",				"7"			},
  { "custom_119.frames",			"1"			},
  { "custom_119.EDITOR",			"RocksCE.png"		},
  { "custom_119.EDITOR.xpos",			"22"			},
  { "custom_119.EDITOR.ypos",			"7"			},

  { "custom_120",				"RocksCE.png"		},
  { "custom_120.xpos",				"7"			},
  { "custom_120.ypos",				"7"			},
  { "custom_120.frames",			"1"			},
  { "custom_120.EDITOR",			"RocksCE.png"		},
  { "custom_120.EDITOR.xpos",			"23"			},
  { "custom_120.EDITOR.ypos",			"7"			},

  { "custom_121",				"RocksCE.png"		},
  { "custom_121.xpos",				"8"			},
  { "custom_121.ypos",				"7"			},
  { "custom_121.frames",			"1"			},
  { "custom_121.EDITOR",			"RocksCE.png"		},
  { "custom_121.EDITOR.xpos",			"24"			},
  { "custom_121.EDITOR.ypos",			"7"			},

  { "custom_122",				"RocksCE.png"		},
  { "custom_122.xpos",				"9"			},
  { "custom_122.ypos",				"7"			},
  { "custom_122.frames",			"1"			},
  { "custom_122.EDITOR",			"RocksCE.png"		},
  { "custom_122.EDITOR.xpos",			"25"			},
  { "custom_122.EDITOR.ypos",			"7"			},

  { "custom_123",				"RocksCE.png"		},
  { "custom_123.xpos",				"10"			},
  { "custom_123.ypos",				"7"			},
  { "custom_123.frames",			"1"			},
  { "custom_123.EDITOR",			"RocksCE.png"		},
  { "custom_123.EDITOR.xpos",			"26"			},
  { "custom_123.EDITOR.ypos",			"7"			},

  { "custom_124",				"RocksCE.png"		},
  { "custom_124.xpos",				"11"			},
  { "custom_124.ypos",				"7"			},
  { "custom_124.frames",			"1"			},
  { "custom_124.EDITOR",			"RocksCE.png"		},
  { "custom_124.EDITOR.xpos",			"27"			},
  { "custom_124.EDITOR.ypos",			"7"			},

  { "custom_125",				"RocksCE.png"		},
  { "custom_125.xpos",				"12"			},
  { "custom_125.ypos",				"7"			},
  { "custom_125.frames",			"1"			},
  { "custom_125.EDITOR",			"RocksCE.png"		},
  { "custom_125.EDITOR.xpos",			"28"			},
  { "custom_125.EDITOR.ypos",			"7"			},

  { "custom_126",				"RocksCE.png"		},
  { "custom_126.xpos",				"13"			},
  { "custom_126.ypos",				"7"			},
  { "custom_126.frames",			"1"			},
  { "custom_126.EDITOR",			"RocksCE.png"		},
  { "custom_126.EDITOR.xpos",			"29"			},
  { "custom_126.EDITOR.ypos",			"7"			},

  { "custom_127",				"RocksCE.png"		},
  { "custom_127.xpos",				"14"			},
  { "custom_127.ypos",				"7"			},
  { "custom_127.frames",			"1"			},
  { "custom_127.EDITOR",			"RocksCE.png"		},
  { "custom_127.EDITOR.xpos",			"30"			},
  { "custom_127.EDITOR.ypos",			"7"			},

  { "custom_128",				"RocksCE.png"		},
  { "custom_128.xpos",				"15"			},
  { "custom_128.ypos",				"7"			},
  { "custom_128.frames",			"1"			},
  { "custom_128.EDITOR",			"RocksCE.png"		},
  { "custom_128.EDITOR.xpos",			"31"			},
  { "custom_128.EDITOR.ypos",			"7"			},

  { "custom_129",				"RocksCE.png"		},
  { "custom_129.xpos",				"0"			},
  { "custom_129.ypos",				"8"			},
  { "custom_129.frames",			"1"			},
  { "custom_129.EDITOR",			"RocksCE.png"		},
  { "custom_129.EDITOR.xpos",			"16"			},
  { "custom_129.EDITOR.ypos",			"8"			},

  { "custom_130",				"RocksCE.png"		},
  { "custom_130.xpos",				"1"			},
  { "custom_130.ypos",				"8"			},
  { "custom_130.frames",			"1"			},
  { "custom_130.EDITOR",			"RocksCE.png"		},
  { "custom_130.EDITOR.xpos",			"17"			},
  { "custom_130.EDITOR.ypos",			"8"			},

  { "custom_131",				"RocksCE.png"		},
  { "custom_131.xpos",				"2"			},
  { "custom_131.ypos",				"8"			},
  { "custom_131.frames",			"1"			},
  { "custom_131.EDITOR",			"RocksCE.png"		},
  { "custom_131.EDITOR.xpos",			"18"			},
  { "custom_131.EDITOR.ypos",			"8"			},

  { "custom_132",				"RocksCE.png"		},
  { "custom_132.xpos",				"3"			},
  { "custom_132.ypos",				"8"			},
  { "custom_132.frames",			"1"			},
  { "custom_132.EDITOR",			"RocksCE.png"		},
  { "custom_132.EDITOR.xpos",			"19"			},
  { "custom_132.EDITOR.ypos",			"8"			},

  { "custom_133",				"RocksCE.png"		},
  { "custom_133.xpos",				"4"			},
  { "custom_133.ypos",				"8"			},
  { "custom_133.frames",			"1"			},
  { "custom_133.EDITOR",			"RocksCE.png"		},
  { "custom_133.EDITOR.xpos",			"20"			},
  { "custom_133.EDITOR.ypos",			"8"			},

  { "custom_134",				"RocksCE.png"		},
  { "custom_134.xpos",				"5"			},
  { "custom_134.ypos",				"8"			},
  { "custom_134.frames",			"1"			},
  { "custom_134.EDITOR",			"RocksCE.png"		},
  { "custom_134.EDITOR.xpos",			"21"			},
  { "custom_134.EDITOR.ypos",			"8"			},

  { "custom_135",				"RocksCE.png"		},
  { "custom_135.xpos",				"6"			},
  { "custom_135.ypos",				"8"			},
  { "custom_135.frames",			"1"			},
  { "custom_135.EDITOR",			"RocksCE.png"		},
  { "custom_135.EDITOR.xpos",			"22"			},
  { "custom_135.EDITOR.ypos",			"8"			},

  { "custom_136",				"RocksCE.png"		},
  { "custom_136.xpos",				"7"			},
  { "custom_136.ypos",				"8"			},
  { "custom_136.frames",			"1"			},
  { "custom_136.EDITOR",			"RocksCE.png"		},
  { "custom_136.EDITOR.xpos",			"23"			},
  { "custom_136.EDITOR.ypos",			"8"			},

  { "custom_137",				"RocksCE.png"		},
  { "custom_137.xpos",				"8"			},
  { "custom_137.ypos",				"8"			},
  { "custom_137.frames",			"1"			},
  { "custom_137.EDITOR",			"RocksCE.png"		},
  { "custom_137.EDITOR.xpos",			"24"			},
  { "custom_137.EDITOR.ypos",			"8"			},

  { "custom_138",				"RocksCE.png"		},
  { "custom_138.xpos",				"9"			},
  { "custom_138.ypos",				"8"			},
  { "custom_138.frames",			"1"			},
  { "custom_138.EDITOR",			"RocksCE.png"		},
  { "custom_138.EDITOR.xpos",			"25"			},
  { "custom_138.EDITOR.ypos",			"8"			},

  { "custom_139",				"RocksCE.png"		},
  { "custom_139.xpos",				"10"			},
  { "custom_139.ypos",				"8"			},
  { "custom_139.frames",			"1"			},
  { "custom_139.EDITOR",			"RocksCE.png"		},
  { "custom_139.EDITOR.xpos",			"26"			},
  { "custom_139.EDITOR.ypos",			"8"			},

  { "custom_140",				"RocksCE.png"		},
  { "custom_140.xpos",				"11"			},
  { "custom_140.ypos",				"8"			},
  { "custom_140.frames",			"1"			},
  { "custom_140.EDITOR",			"RocksCE.png"		},
  { "custom_140.EDITOR.xpos",			"27"			},
  { "custom_140.EDITOR.ypos",			"8"			},

  { "custom_141",				"RocksCE.png"		},
  { "custom_141.xpos",				"12"			},
  { "custom_141.ypos",				"8"			},
  { "custom_141.frames",			"1"			},
  { "custom_141.EDITOR",			"RocksCE.png"		},
  { "custom_141.EDITOR.xpos",			"28"			},
  { "custom_141.EDITOR.ypos",			"8"			},

  { "custom_142",				"RocksCE.png"		},
  { "custom_142.xpos",				"13"			},
  { "custom_142.ypos",				"8"			},
  { "custom_142.frames",			"1"			},
  { "custom_142.EDITOR",			"RocksCE.png"		},
  { "custom_142.EDITOR.xpos",			"29"			},
  { "custom_142.EDITOR.ypos",			"8"			},

  { "custom_143",				"RocksCE.png"		},
  { "custom_143.xpos",				"14"			},
  { "custom_143.ypos",				"8"			},
  { "custom_143.frames",			"1"			},
  { "custom_143.EDITOR",			"RocksCE.png"		},
  { "custom_143.EDITOR.xpos",			"30"			},
  { "custom_143.EDITOR.ypos",			"8"			},

  { "custom_144",				"RocksCE.png"		},
  { "custom_144.xpos",				"15"			},
  { "custom_144.ypos",				"8"			},
  { "custom_144.frames",			"1"			},
  { "custom_144.EDITOR",			"RocksCE.png"		},
  { "custom_144.EDITOR.xpos",			"31"			},
  { "custom_144.EDITOR.ypos",			"8"			},

  { "custom_145",				"RocksCE.png"		},
  { "custom_145.xpos",				"0"			},
  { "custom_145.ypos",				"9"			},
  { "custom_145.frames",			"1"			},
  { "custom_145.EDITOR",			"RocksCE.png"		},
  { "custom_145.EDITOR.xpos",			"16"			},
  { "custom_145.EDITOR.ypos",			"9"			},

  { "custom_146",				"RocksCE.png"		},
  { "custom_146.xpos",				"1"			},
  { "custom_146.ypos",				"9"			},
  { "custom_146.frames",			"1"			},
  { "custom_146.EDITOR",			"RocksCE.png"		},
  { "custom_146.EDITOR.xpos",			"17"			},
  { "custom_146.EDITOR.ypos",			"9"			},

  { "custom_147",				"RocksCE.png"		},
  { "custom_147.xpos",				"2"			},
  { "custom_147.ypos",				"9"			},
  { "custom_147.frames",			"1"			},
  { "custom_147.EDITOR",			"RocksCE.png"		},
  { "custom_147.EDITOR.xpos",			"18"			},
  { "custom_147.EDITOR.ypos",			"9"			},

  { "custom_148",				"RocksCE.png"		},
  { "custom_148.xpos",				"3"			},
  { "custom_148.ypos",				"9"			},
  { "custom_148.frames",			"1"			},
  { "custom_148.EDITOR",			"RocksCE.png"		},
  { "custom_148.EDITOR.xpos",			"19"			},
  { "custom_148.EDITOR.ypos",			"9"			},

  { "custom_149",				"RocksCE.png"		},
  { "custom_149.xpos",				"4"			},
  { "custom_149.ypos",				"9"			},
  { "custom_149.frames",			"1"			},
  { "custom_149.EDITOR",			"RocksCE.png"		},
  { "custom_149.EDITOR.xpos",			"20"			},
  { "custom_149.EDITOR.ypos",			"9"			},

  { "custom_150",				"RocksCE.png"		},
  { "custom_150.xpos",				"5"			},
  { "custom_150.ypos",				"9"			},
  { "custom_150.frames",			"1"			},
  { "custom_150.EDITOR",			"RocksCE.png"		},
  { "custom_150.EDITOR.xpos",			"21"			},
  { "custom_150.EDITOR.ypos",			"9"			},

  { "custom_151",				"RocksCE.png"		},
  { "custom_151.xpos",				"6"			},
  { "custom_151.ypos",				"9"			},
  { "custom_151.frames",			"1"			},
  { "custom_151.EDITOR",			"RocksCE.png"		},
  { "custom_151.EDITOR.xpos",			"22"			},
  { "custom_151.EDITOR.ypos",			"9"			},

  { "custom_152",				"RocksCE.png"		},
  { "custom_152.xpos",				"7"			},
  { "custom_152.ypos",				"9"			},
  { "custom_152.frames",			"1"			},
  { "custom_152.EDITOR",			"RocksCE.png"		},
  { "custom_152.EDITOR.xpos",			"23"			},
  { "custom_152.EDITOR.ypos",			"9"			},

  { "custom_153",				"RocksCE.png"		},
  { "custom_153.xpos",				"8"			},
  { "custom_153.ypos",				"9"			},
  { "custom_153.frames",			"1"			},
  { "custom_153.EDITOR",			"RocksCE.png"		},
  { "custom_153.EDITOR.xpos",			"24"			},
  { "custom_153.EDITOR.ypos",			"9"			},

  { "custom_154",				"RocksCE.png"		},
  { "custom_154.xpos",				"9"			},
  { "custom_154.ypos",				"9"			},
  { "custom_154.frames",			"1"			},
  { "custom_154.EDITOR",			"RocksCE.png"		},
  { "custom_154.EDITOR.xpos",			"25"			},
  { "custom_154.EDITOR.ypos",			"9"			},

  { "custom_155",				"RocksCE.png"		},
  { "custom_155.xpos",				"10"			},
  { "custom_155.ypos",				"9"			},
  { "custom_155.frames",			"1"			},
  { "custom_155.EDITOR",			"RocksCE.png"		},
  { "custom_155.EDITOR.xpos",			"26"			},
  { "custom_155.EDITOR.ypos",			"9"			},

  { "custom_156",				"RocksCE.png"		},
  { "custom_156.xpos",				"11"			},
  { "custom_156.ypos",				"9"			},
  { "custom_156.frames",			"1"			},
  { "custom_156.EDITOR",			"RocksCE.png"		},
  { "custom_156.EDITOR.xpos",			"27"			},
  { "custom_156.EDITOR.ypos",			"9"			},

  { "custom_157",				"RocksCE.png"		},
  { "custom_157.xpos",				"12"			},
  { "custom_157.ypos",				"9"			},
  { "custom_157.frames",			"1"			},
  { "custom_157.EDITOR",			"RocksCE.png"		},
  { "custom_157.EDITOR.xpos",			"28"			},
  { "custom_157.EDITOR.ypos",			"9"			},

  { "custom_158",				"RocksCE.png"		},
  { "custom_158.xpos",				"13"			},
  { "custom_158.ypos",				"9"			},
  { "custom_158.frames",			"1"			},
  { "custom_158.EDITOR",			"RocksCE.png"		},
  { "custom_158.EDITOR.xpos",			"29"			},
  { "custom_158.EDITOR.ypos",			"9"			},

  { "custom_159",				"RocksCE.png"		},
  { "custom_159.xpos",				"14"			},
  { "custom_159.ypos",				"9"			},
  { "custom_159.frames",			"1"			},
  { "custom_159.EDITOR",			"RocksCE.png"		},
  { "custom_159.EDITOR.xpos",			"30"			},
  { "custom_159.EDITOR.ypos",			"9"			},

  { "custom_160",				"RocksCE.png"		},
  { "custom_160.xpos",				"15"			},
  { "custom_160.ypos",				"9"			},
  { "custom_160.frames",			"1"			},
  { "custom_160.EDITOR",			"RocksCE.png"		},
  { "custom_160.EDITOR.xpos",			"31"			},
  { "custom_160.EDITOR.ypos",			"9"			},

  { "custom_161",				"RocksCE.png"		},
  { "custom_161.xpos",				"0"			},
  { "custom_161.ypos",				"10"			},
  { "custom_161.frames",			"1"			},
  { "custom_161.EDITOR",			"RocksCE.png"		},
  { "custom_161.EDITOR.xpos",			"16"			},
  { "custom_161.EDITOR.ypos",			"10"			},

  { "custom_162",				"RocksCE.png"		},
  { "custom_162.xpos",				"1"			},
  { "custom_162.ypos",				"10"			},
  { "custom_162.frames",			"1"			},
  { "custom_162.EDITOR",			"RocksCE.png"		},
  { "custom_162.EDITOR.xpos",			"17"			},
  { "custom_162.EDITOR.ypos",			"10"			},

  { "custom_163",				"RocksCE.png"		},
  { "custom_163.xpos",				"2"			},
  { "custom_163.ypos",				"10"			},
  { "custom_163.frames",			"1"			},
  { "custom_163.EDITOR",			"RocksCE.png"		},
  { "custom_163.EDITOR.xpos",			"18"			},
  { "custom_163.EDITOR.ypos",			"10"			},

  { "custom_164",				"RocksCE.png"		},
  { "custom_164.xpos",				"3"			},
  { "custom_164.ypos",				"10"			},
  { "custom_164.frames",			"1"			},
  { "custom_164.EDITOR",			"RocksCE.png"		},
  { "custom_164.EDITOR.xpos",			"19"			},
  { "custom_164.EDITOR.ypos",			"10"			},

  { "custom_165",				"RocksCE.png"		},
  { "custom_165.xpos",				"4"			},
  { "custom_165.ypos",				"10"			},
  { "custom_165.frames",			"1"			},
  { "custom_165.EDITOR",			"RocksCE.png"		},
  { "custom_165.EDITOR.xpos",			"20"			},
  { "custom_165.EDITOR.ypos",			"10"			},

  { "custom_166",				"RocksCE.png"		},
  { "custom_166.xpos",				"5"			},
  { "custom_166.ypos",				"10"			},
  { "custom_166.frames",			"1"			},
  { "custom_166.EDITOR",			"RocksCE.png"		},
  { "custom_166.EDITOR.xpos",			"21"			},
  { "custom_166.EDITOR.ypos",			"10"			},

  { "custom_167",				"RocksCE.png"		},
  { "custom_167.xpos",				"6"			},
  { "custom_167.ypos",				"10"			},
  { "custom_167.frames",			"1"			},
  { "custom_167.EDITOR",			"RocksCE.png"		},
  { "custom_167.EDITOR.xpos",			"22"			},
  { "custom_167.EDITOR.ypos",			"10"			},

  { "custom_168",				"RocksCE.png"		},
  { "custom_168.xpos",				"7"			},
  { "custom_168.ypos",				"10"			},
  { "custom_168.frames",			"1"			},
  { "custom_168.EDITOR",			"RocksCE.png"		},
  { "custom_168.EDITOR.xpos",			"23"			},
  { "custom_168.EDITOR.ypos",			"10"			},

  { "custom_169",				"RocksCE.png"		},
  { "custom_169.xpos",				"8"			},
  { "custom_169.ypos",				"10"			},
  { "custom_169.frames",			"1"			},
  { "custom_169.EDITOR",			"RocksCE.png"		},
  { "custom_169.EDITOR.xpos",			"24"			},
  { "custom_169.EDITOR.ypos",			"10"			},

  { "custom_170",				"RocksCE.png"		},
  { "custom_170.xpos",				"9"			},
  { "custom_170.ypos",				"10"			},
  { "custom_170.frames",			"1"			},
  { "custom_170.EDITOR",			"RocksCE.png"		},
  { "custom_170.EDITOR.xpos",			"25"			},
  { "custom_170.EDITOR.ypos",			"10"			},

  { "custom_171",				"RocksCE.png"		},
  { "custom_171.xpos",				"10"			},
  { "custom_171.ypos",				"10"			},
  { "custom_171.frames",			"1"			},
  { "custom_171.EDITOR",			"RocksCE.png"		},
  { "custom_171.EDITOR.xpos",			"26"			},
  { "custom_171.EDITOR.ypos",			"10"			},

  { "custom_172",				"RocksCE.png"		},
  { "custom_172.xpos",				"11"			},
  { "custom_172.ypos",				"10"			},
  { "custom_172.frames",			"1"			},
  { "custom_172.EDITOR",			"RocksCE.png"		},
  { "custom_172.EDITOR.xpos",			"27"			},
  { "custom_172.EDITOR.ypos",			"10"			},

  { "custom_173",				"RocksCE.png"		},
  { "custom_173.xpos",				"12"			},
  { "custom_173.ypos",				"10"			},
  { "custom_173.frames",			"1"			},
  { "custom_173.EDITOR",			"RocksCE.png"		},
  { "custom_173.EDITOR.xpos",			"28"			},
  { "custom_173.EDITOR.ypos",			"10"			},

  { "custom_174",				"RocksCE.png"		},
  { "custom_174.xpos",				"13"			},
  { "custom_174.ypos",				"10"			},
  { "custom_174.frames",			"1"			},
  { "custom_174.EDITOR",			"RocksCE.png"		},
  { "custom_174.EDITOR.xpos",			"29"			},
  { "custom_174.EDITOR.ypos",			"10"			},

  { "custom_175",				"RocksCE.png"		},
  { "custom_175.xpos",				"14"			},
  { "custom_175.ypos",				"10"			},
  { "custom_175.frames",			"1"			},
  { "custom_175.EDITOR",			"RocksCE.png"		},
  { "custom_175.EDITOR.xpos",			"30"			},
  { "custom_175.EDITOR.ypos",			"10"			},

  { "custom_176",				"RocksCE.png"		},
  { "custom_176.xpos",				"15"			},
  { "custom_176.ypos",				"10"			},
  { "custom_176.frames",			"1"			},
  { "custom_176.EDITOR",			"RocksCE.png"		},
  { "custom_176.EDITOR.xpos",			"31"			},
  { "custom_176.EDITOR.ypos",			"10"			},

  { "custom_177",				"RocksCE.png"		},
  { "custom_177.xpos",				"0"			},
  { "custom_177.ypos",				"11"			},
  { "custom_177.frames",			"1"			},
  { "custom_177.EDITOR",			"RocksCE.png"		},
  { "custom_177.EDITOR.xpos",			"16"			},
  { "custom_177.EDITOR.ypos",			"11"			},

  { "custom_178",				"RocksCE.png"		},
  { "custom_178.xpos",				"1"			},
  { "custom_178.ypos",				"11"			},
  { "custom_178.frames",			"1"			},
  { "custom_178.EDITOR",			"RocksCE.png"		},
  { "custom_178.EDITOR.xpos",			"17"			},
  { "custom_178.EDITOR.ypos",			"11"			},

  { "custom_179",				"RocksCE.png"		},
  { "custom_179.xpos",				"2"			},
  { "custom_179.ypos",				"11"			},
  { "custom_179.frames",			"1"			},
  { "custom_179.EDITOR",			"RocksCE.png"		},
  { "custom_179.EDITOR.xpos",			"18"			},
  { "custom_179.EDITOR.ypos",			"11"			},

  { "custom_180",				"RocksCE.png"		},
  { "custom_180.xpos",				"3"			},
  { "custom_180.ypos",				"11"			},
  { "custom_180.frames",			"1"			},
  { "custom_180.EDITOR",			"RocksCE.png"		},
  { "custom_180.EDITOR.xpos",			"19"			},
  { "custom_180.EDITOR.ypos",			"11"			},

  { "custom_181",				"RocksCE.png"		},
  { "custom_181.xpos",				"4"			},
  { "custom_181.ypos",				"11"			},
  { "custom_181.frames",			"1"			},
  { "custom_181.EDITOR",			"RocksCE.png"		},
  { "custom_181.EDITOR.xpos",			"20"			},
  { "custom_181.EDITOR.ypos",			"11"			},

  { "custom_182",				"RocksCE.png"		},
  { "custom_182.xpos",				"5"			},
  { "custom_182.ypos",				"11"			},
  { "custom_182.frames",			"1"			},
  { "custom_182.EDITOR",			"RocksCE.png"		},
  { "custom_182.EDITOR.xpos",			"21"			},
  { "custom_182.EDITOR.ypos",			"11"			},

  { "custom_183",				"RocksCE.png"		},
  { "custom_183.xpos",				"6"			},
  { "custom_183.ypos",				"11"			},
  { "custom_183.frames",			"1"			},
  { "custom_183.EDITOR",			"RocksCE.png"		},
  { "custom_183.EDITOR.xpos",			"22"			},
  { "custom_183.EDITOR.ypos",			"11"			},

  { "custom_184",				"RocksCE.png"		},
  { "custom_184.xpos",				"7"			},
  { "custom_184.ypos",				"11"			},
  { "custom_184.frames",			"1"			},
  { "custom_184.EDITOR",			"RocksCE.png"		},
  { "custom_184.EDITOR.xpos",			"23"			},
  { "custom_184.EDITOR.ypos",			"11"			},

  { "custom_185",				"RocksCE.png"		},
  { "custom_185.xpos",				"8"			},
  { "custom_185.ypos",				"11"			},
  { "custom_185.frames",			"1"			},
  { "custom_185.EDITOR",			"RocksCE.png"		},
  { "custom_185.EDITOR.xpos",			"24"			},
  { "custom_185.EDITOR.ypos",			"11"			},

  { "custom_186",				"RocksCE.png"		},
  { "custom_186.xpos",				"9"			},
  { "custom_186.ypos",				"11"			},
  { "custom_186.frames",			"1"			},
  { "custom_186.EDITOR",			"RocksCE.png"		},
  { "custom_186.EDITOR.xpos",			"25"			},
  { "custom_186.EDITOR.ypos",			"11"			},

  { "custom_187",				"RocksCE.png"		},
  { "custom_187.xpos",				"10"			},
  { "custom_187.ypos",				"11"			},
  { "custom_187.frames",			"1"			},
  { "custom_187.EDITOR",			"RocksCE.png"		},
  { "custom_187.EDITOR.xpos",			"26"			},
  { "custom_187.EDITOR.ypos",			"11"			},

  { "custom_188",				"RocksCE.png"		},
  { "custom_188.xpos",				"11"			},
  { "custom_188.ypos",				"11"			},
  { "custom_188.frames",			"1"			},
  { "custom_188.EDITOR",			"RocksCE.png"		},
  { "custom_188.EDITOR.xpos",			"27"			},
  { "custom_188.EDITOR.ypos",			"11"			},

  { "custom_189",				"RocksCE.png"		},
  { "custom_189.xpos",				"12"			},
  { "custom_189.ypos",				"11"			},
  { "custom_189.frames",			"1"			},
  { "custom_189.EDITOR",			"RocksCE.png"		},
  { "custom_189.EDITOR.xpos",			"28"			},
  { "custom_189.EDITOR.ypos",			"11"			},

  { "custom_190",				"RocksCE.png"		},
  { "custom_190.xpos",				"13"			},
  { "custom_190.ypos",				"11"			},
  { "custom_190.frames",			"1"			},
  { "custom_190.EDITOR",			"RocksCE.png"		},
  { "custom_190.EDITOR.xpos",			"29"			},
  { "custom_190.EDITOR.ypos",			"11"			},

  { "custom_191",				"RocksCE.png"		},
  { "custom_191.xpos",				"14"			},
  { "custom_191.ypos",				"11"			},
  { "custom_191.frames",			"1"			},
  { "custom_191.EDITOR",			"RocksCE.png"		},
  { "custom_191.EDITOR.xpos",			"30"			},
  { "custom_191.EDITOR.ypos",			"11"			},

  { "custom_192",				"RocksCE.png"		},
  { "custom_192.xpos",				"15"			},
  { "custom_192.ypos",				"11"			},
  { "custom_192.frames",			"1"			},
  { "custom_192.EDITOR",			"RocksCE.png"		},
  { "custom_192.EDITOR.xpos",			"31"			},
  { "custom_192.EDITOR.ypos",			"11"			},

  { "custom_193",				"RocksCE.png"		},
  { "custom_193.xpos",				"0"			},
  { "custom_193.ypos",				"12"			},
  { "custom_193.frames",			"1"			},
  { "custom_193.EDITOR",			"RocksCE.png"		},
  { "custom_193.EDITOR.xpos",			"16"			},
  { "custom_193.EDITOR.ypos",			"12"			},

  { "custom_194",				"RocksCE.png"		},
  { "custom_194.xpos",				"1"			},
  { "custom_194.ypos",				"12"			},
  { "custom_194.frames",			"1"			},
  { "custom_194.EDITOR",			"RocksCE.png"		},
  { "custom_194.EDITOR.xpos",			"17"			},
  { "custom_194.EDITOR.ypos",			"12"			},

  { "custom_195",				"RocksCE.png"		},
  { "custom_195.xpos",				"2"			},
  { "custom_195.ypos",				"12"			},
  { "custom_195.frames",			"1"			},
  { "custom_195.EDITOR",			"RocksCE.png"		},
  { "custom_195.EDITOR.xpos",			"18"			},
  { "custom_195.EDITOR.ypos",			"12"			},

  { "custom_196",				"RocksCE.png"		},
  { "custom_196.xpos",				"3"			},
  { "custom_196.ypos",				"12"			},
  { "custom_196.frames",			"1"			},
  { "custom_196.EDITOR",			"RocksCE.png"		},
  { "custom_196.EDITOR.xpos",			"19"			},
  { "custom_196.EDITOR.ypos",			"12"			},

  { "custom_197",				"RocksCE.png"		},
  { "custom_197.xpos",				"4"			},
  { "custom_197.ypos",				"12"			},
  { "custom_197.frames",			"1"			},
  { "custom_197.EDITOR",			"RocksCE.png"		},
  { "custom_197.EDITOR.xpos",			"20"			},
  { "custom_197.EDITOR.ypos",			"12"			},

  { "custom_198",				"RocksCE.png"		},
  { "custom_198.xpos",				"5"			},
  { "custom_198.ypos",				"12"			},
  { "custom_198.frames",			"1"			},
  { "custom_198.EDITOR",			"RocksCE.png"		},
  { "custom_198.EDITOR.xpos",			"21"			},
  { "custom_198.EDITOR.ypos",			"12"			},

  { "custom_199",				"RocksCE.png"		},
  { "custom_199.xpos",				"6"			},
  { "custom_199.ypos",				"12"			},
  { "custom_199.frames",			"1"			},
  { "custom_199.EDITOR",			"RocksCE.png"		},
  { "custom_199.EDITOR.xpos",			"22"			},
  { "custom_199.EDITOR.ypos",			"12"			},

  { "custom_200",				"RocksCE.png"		},
  { "custom_200.xpos",				"7"			},
  { "custom_200.ypos",				"12"			},
  { "custom_200.frames",			"1"			},
  { "custom_200.EDITOR",			"RocksCE.png"		},
  { "custom_200.EDITOR.xpos",			"23"			},
  { "custom_200.EDITOR.ypos",			"12"			},

  { "custom_201",				"RocksCE.png"		},
  { "custom_201.xpos",				"8"			},
  { "custom_201.ypos",				"12"			},
  { "custom_201.frames",			"1"			},
  { "custom_201.EDITOR",			"RocksCE.png"		},
  { "custom_201.EDITOR.xpos",			"24"			},
  { "custom_201.EDITOR.ypos",			"12"			},

  { "custom_202",				"RocksCE.png"		},
  { "custom_202.xpos",				"9"			},
  { "custom_202.ypos",				"12"			},
  { "custom_202.frames",			"1"			},
  { "custom_202.EDITOR",			"RocksCE.png"		},
  { "custom_202.EDITOR.xpos",			"25"			},
  { "custom_202.EDITOR.ypos",			"12"			},

  { "custom_203",				"RocksCE.png"		},
  { "custom_203.xpos",				"10"			},
  { "custom_203.ypos",				"12"			},
  { "custom_203.frames",			"1"			},
  { "custom_203.EDITOR",			"RocksCE.png"		},
  { "custom_203.EDITOR.xpos",			"26"			},
  { "custom_203.EDITOR.ypos",			"12"			},

  { "custom_204",				"RocksCE.png"		},
  { "custom_204.xpos",				"11"			},
  { "custom_204.ypos",				"12"			},
  { "custom_204.frames",			"1"			},
  { "custom_204.EDITOR",			"RocksCE.png"		},
  { "custom_204.EDITOR.xpos",			"27"			},
  { "custom_204.EDITOR.ypos",			"12"			},

  { "custom_205",				"RocksCE.png"		},
  { "custom_205.xpos",				"12"			},
  { "custom_205.ypos",				"12"			},
  { "custom_205.frames",			"1"			},
  { "custom_205.EDITOR",			"RocksCE.png"		},
  { "custom_205.EDITOR.xpos",			"28"			},
  { "custom_205.EDITOR.ypos",			"12"			},

  { "custom_206",				"RocksCE.png"		},
  { "custom_206.xpos",				"13"			},
  { "custom_206.ypos",				"12"			},
  { "custom_206.frames",			"1"			},
  { "custom_206.EDITOR",			"RocksCE.png"		},
  { "custom_206.EDITOR.xpos",			"29"			},
  { "custom_206.EDITOR.ypos",			"12"			},

  { "custom_207",				"RocksCE.png"		},
  { "custom_207.xpos",				"14"			},
  { "custom_207.ypos",				"12"			},
  { "custom_207.frames",			"1"			},
  { "custom_207.EDITOR",			"RocksCE.png"		},
  { "custom_207.EDITOR.xpos",			"30"			},
  { "custom_207.EDITOR.ypos",			"12"			},

  { "custom_208",				"RocksCE.png"		},
  { "custom_208.xpos",				"15"			},
  { "custom_208.ypos",				"12"			},
  { "custom_208.frames",			"1"			},
  { "custom_208.EDITOR",			"RocksCE.png"		},
  { "custom_208.EDITOR.xpos",			"31"			},
  { "custom_208.EDITOR.ypos",			"12"			},

  { "custom_209",				"RocksCE.png"		},
  { "custom_209.xpos",				"0"			},
  { "custom_209.ypos",				"13"			},
  { "custom_209.frames",			"1"			},
  { "custom_209.EDITOR",			"RocksCE.png"		},
  { "custom_209.EDITOR.xpos",			"16"			},
  { "custom_209.EDITOR.ypos",			"13"			},

  { "custom_210",				"RocksCE.png"		},
  { "custom_210.xpos",				"1"			},
  { "custom_210.ypos",				"13"			},
  { "custom_210.frames",			"1"			},
  { "custom_210.EDITOR",			"RocksCE.png"		},
  { "custom_210.EDITOR.xpos",			"17"			},
  { "custom_210.EDITOR.ypos",			"13"			},

  { "custom_211",				"RocksCE.png"		},
  { "custom_211.xpos",				"2"			},
  { "custom_211.ypos",				"13"			},
  { "custom_211.frames",			"1"			},
  { "custom_211.EDITOR",			"RocksCE.png"		},
  { "custom_211.EDITOR.xpos",			"18"			},
  { "custom_211.EDITOR.ypos",			"13"			},

  { "custom_212",				"RocksCE.png"		},
  { "custom_212.xpos",				"3"			},
  { "custom_212.ypos",				"13"			},
  { "custom_212.frames",			"1"			},
  { "custom_212.EDITOR",			"RocksCE.png"		},
  { "custom_212.EDITOR.xpos",			"19"			},
  { "custom_212.EDITOR.ypos",			"13"			},

  { "custom_213",				"RocksCE.png"		},
  { "custom_213.xpos",				"4"			},
  { "custom_213.ypos",				"13"			},
  { "custom_213.frames",			"1"			},
  { "custom_213.EDITOR",			"RocksCE.png"		},
  { "custom_213.EDITOR.xpos",			"20"			},
  { "custom_213.EDITOR.ypos",			"13"			},

  { "custom_214",				"RocksCE.png"		},
  { "custom_214.xpos",				"5"			},
  { "custom_214.ypos",				"13"			},
  { "custom_214.frames",			"1"			},
  { "custom_214.EDITOR",			"RocksCE.png"		},
  { "custom_214.EDITOR.xpos",			"21"			},
  { "custom_214.EDITOR.ypos",			"13"			},

  { "custom_215",				"RocksCE.png"		},
  { "custom_215.xpos",				"6"			},
  { "custom_215.ypos",				"13"			},
  { "custom_215.frames",			"1"			},
  { "custom_215.EDITOR",			"RocksCE.png"		},
  { "custom_215.EDITOR.xpos",			"22"			},
  { "custom_215.EDITOR.ypos",			"13"			},

  { "custom_216",				"RocksCE.png"		},
  { "custom_216.xpos",				"7"			},
  { "custom_216.ypos",				"13"			},
  { "custom_216.frames",			"1"			},
  { "custom_216.EDITOR",			"RocksCE.png"		},
  { "custom_216.EDITOR.xpos",			"23"			},
  { "custom_216.EDITOR.ypos",			"13"			},

  { "custom_217",				"RocksCE.png"		},
  { "custom_217.xpos",				"8"			},
  { "custom_217.ypos",				"13"			},
  { "custom_217.frames",			"1"			},
  { "custom_217.EDITOR",			"RocksCE.png"		},
  { "custom_217.EDITOR.xpos",			"24"			},
  { "custom_217.EDITOR.ypos",			"13"			},

  { "custom_218",				"RocksCE.png"		},
  { "custom_218.xpos",				"9"			},
  { "custom_218.ypos",				"13"			},
  { "custom_218.frames",			"1"			},
  { "custom_218.EDITOR",			"RocksCE.png"		},
  { "custom_218.EDITOR.xpos",			"25"			},
  { "custom_218.EDITOR.ypos",			"13"			},

  { "custom_219",				"RocksCE.png"		},
  { "custom_219.xpos",				"10"			},
  { "custom_219.ypos",				"13"			},
  { "custom_219.frames",			"1"			},
  { "custom_219.EDITOR",			"RocksCE.png"		},
  { "custom_219.EDITOR.xpos",			"26"			},
  { "custom_219.EDITOR.ypos",			"13"			},

  { "custom_220",				"RocksCE.png"		},
  { "custom_220.xpos",				"11"			},
  { "custom_220.ypos",				"13"			},
  { "custom_220.frames",			"1"			},
  { "custom_220.EDITOR",			"RocksCE.png"		},
  { "custom_220.EDITOR.xpos",			"27"			},
  { "custom_220.EDITOR.ypos",			"13"			},

  { "custom_221",				"RocksCE.png"		},
  { "custom_221.xpos",				"12"			},
  { "custom_221.ypos",				"13"			},
  { "custom_221.frames",			"1"			},
  { "custom_221.EDITOR",			"RocksCE.png"		},
  { "custom_221.EDITOR.xpos",			"28"			},
  { "custom_221.EDITOR.ypos",			"13"			},

  { "custom_222",				"RocksCE.png"		},
  { "custom_222.xpos",				"13"			},
  { "custom_222.ypos",				"13"			},
  { "custom_222.frames",			"1"			},
  { "custom_222.EDITOR",			"RocksCE.png"		},
  { "custom_222.EDITOR.xpos",			"29"			},
  { "custom_222.EDITOR.ypos",			"13"			},

  { "custom_223",				"RocksCE.png"		},
  { "custom_223.xpos",				"14"			},
  { "custom_223.ypos",				"13"			},
  { "custom_223.frames",			"1"			},
  { "custom_223.EDITOR",			"RocksCE.png"		},
  { "custom_223.EDITOR.xpos",			"30"			},
  { "custom_223.EDITOR.ypos",			"13"			},

  { "custom_224",				"RocksCE.png"		},
  { "custom_224.xpos",				"15"			},
  { "custom_224.ypos",				"13"			},
  { "custom_224.frames",			"1"			},
  { "custom_224.EDITOR",			"RocksCE.png"		},
  { "custom_224.EDITOR.xpos",			"31"			},
  { "custom_224.EDITOR.ypos",			"13"			},

  { "custom_225",				"RocksCE.png"		},
  { "custom_225.xpos",				"0"			},
  { "custom_225.ypos",				"14"			},
  { "custom_225.frames",			"1"			},
  { "custom_225.EDITOR",			"RocksCE.png"		},
  { "custom_225.EDITOR.xpos",			"16"			},
  { "custom_225.EDITOR.ypos",			"14"			},

  { "custom_226",				"RocksCE.png"		},
  { "custom_226.xpos",				"1"			},
  { "custom_226.ypos",				"14"			},
  { "custom_226.frames",			"1"			},
  { "custom_226.EDITOR",			"RocksCE.png"		},
  { "custom_226.EDITOR.xpos",			"17"			},
  { "custom_226.EDITOR.ypos",			"14"			},

  { "custom_227",				"RocksCE.png"		},
  { "custom_227.xpos",				"2"			},
  { "custom_227.ypos",				"14"			},
  { "custom_227.frames",			"1"			},
  { "custom_227.EDITOR",			"RocksCE.png"		},
  { "custom_227.EDITOR.xpos",			"18"			},
  { "custom_227.EDITOR.ypos",			"14"			},

  { "custom_228",				"RocksCE.png"		},
  { "custom_228.xpos",				"3"			},
  { "custom_228.ypos",				"14"			},
  { "custom_228.frames",			"1"			},
  { "custom_228.EDITOR",			"RocksCE.png"		},
  { "custom_228.EDITOR.xpos",			"19"			},
  { "custom_228.EDITOR.ypos",			"14"			},

  { "custom_229",				"RocksCE.png"		},
  { "custom_229.xpos",				"4"			},
  { "custom_229.ypos",				"14"			},
  { "custom_229.frames",			"1"			},
  { "custom_229.EDITOR",			"RocksCE.png"		},
  { "custom_229.EDITOR.xpos",			"20"			},
  { "custom_229.EDITOR.ypos",			"14"			},

  { "custom_230",				"RocksCE.png"		},
  { "custom_230.xpos",				"5"			},
  { "custom_230.ypos",				"14"			},
  { "custom_230.frames",			"1"			},
  { "custom_230.EDITOR",			"RocksCE.png"		},
  { "custom_230.EDITOR.xpos",			"21"			},
  { "custom_230.EDITOR.ypos",			"14"			},

  { "custom_231",				"RocksCE.png"		},
  { "custom_231.xpos",				"6"			},
  { "custom_231.ypos",				"14"			},
  { "custom_231.frames",			"1"			},
  { "custom_231.EDITOR",			"RocksCE.png"		},
  { "custom_231.EDITOR.xpos",			"22"			},
  { "custom_231.EDITOR.ypos",			"14"			},

  { "custom_232",				"RocksCE.png"		},
  { "custom_232.xpos",				"7"			},
  { "custom_232.ypos",				"14"			},
  { "custom_232.frames",			"1"			},
  { "custom_232.EDITOR",			"RocksCE.png"		},
  { "custom_232.EDITOR.xpos",			"23"			},
  { "custom_232.EDITOR.ypos",			"14"			},

  { "custom_233",				"RocksCE.png"		},
  { "custom_233.xpos",				"8"			},
  { "custom_233.ypos",				"14"			},
  { "custom_233.frames",			"1"			},
  { "custom_233.EDITOR",			"RocksCE.png"		},
  { "custom_233.EDITOR.xpos",			"24"			},
  { "custom_233.EDITOR.ypos",			"14"			},

  { "custom_234",				"RocksCE.png"		},
  { "custom_234.xpos",				"9"			},
  { "custom_234.ypos",				"14"			},
  { "custom_234.frames",			"1"			},
  { "custom_234.EDITOR",			"RocksCE.png"		},
  { "custom_234.EDITOR.xpos",			"25"			},
  { "custom_234.EDITOR.ypos",			"14"			},

  { "custom_235",				"RocksCE.png"		},
  { "custom_235.xpos",				"10"			},
  { "custom_235.ypos",				"14"			},
  { "custom_235.frames",			"1"			},
  { "custom_235.EDITOR",			"RocksCE.png"		},
  { "custom_235.EDITOR.xpos",			"26"			},
  { "custom_235.EDITOR.ypos",			"14"			},

  { "custom_236",				"RocksCE.png"		},
  { "custom_236.xpos",				"11"			},
  { "custom_236.ypos",				"14"			},
  { "custom_236.frames",			"1"			},
  { "custom_236.EDITOR",			"RocksCE.png"		},
  { "custom_236.EDITOR.xpos",			"27"			},
  { "custom_236.EDITOR.ypos",			"14"			},

  { "custom_237",				"RocksCE.png"		},
  { "custom_237.xpos",				"12"			},
  { "custom_237.ypos",				"14"			},
  { "custom_237.frames",			"1"			},
  { "custom_237.EDITOR",			"RocksCE.png"		},
  { "custom_237.EDITOR.xpos",			"28"			},
  { "custom_237.EDITOR.ypos",			"14"			},

  { "custom_238",				"RocksCE.png"		},
  { "custom_238.xpos",				"13"			},
  { "custom_238.ypos",				"14"			},
  { "custom_238.frames",			"1"			},
  { "custom_238.EDITOR",			"RocksCE.png"		},
  { "custom_238.EDITOR.xpos",			"29"			},
  { "custom_238.EDITOR.ypos",			"14"			},

  { "custom_239",				"RocksCE.png"		},
  { "custom_239.xpos",				"14"			},
  { "custom_239.ypos",				"14"			},
  { "custom_239.frames",			"1"			},
  { "custom_239.EDITOR",			"RocksCE.png"		},
  { "custom_239.EDITOR.xpos",			"30"			},
  { "custom_239.EDITOR.ypos",			"14"			},

  { "custom_240",				"RocksCE.png"		},
  { "custom_240.xpos",				"15"			},
  { "custom_240.ypos",				"14"			},
  { "custom_240.frames",			"1"			},
  { "custom_240.EDITOR",			"RocksCE.png"		},
  { "custom_240.EDITOR.xpos",			"31"			},
  { "custom_240.EDITOR.ypos",			"14"			},

  { "custom_241",				"RocksCE.png"		},
  { "custom_241.xpos",				"0"			},
  { "custom_241.ypos",				"15"			},
  { "custom_241.frames",			"1"			},
  { "custom_241.EDITOR",			"RocksCE.png"		},
  { "custom_241.EDITOR.xpos",			"16"			},
  { "custom_241.EDITOR.ypos",			"15"			},

  { "custom_242",				"RocksCE.png"		},
  { "custom_242.xpos",				"1"			},
  { "custom_242.ypos",				"15"			},
  { "custom_242.frames",			"1"			},
  { "custom_242.EDITOR",			"RocksCE.png"		},
  { "custom_242.EDITOR.xpos",			"17"			},
  { "custom_242.EDITOR.ypos",			"15"			},

  { "custom_243",				"RocksCE.png"		},
  { "custom_243.xpos",				"2"			},
  { "custom_243.ypos",				"15"			},
  { "custom_243.frames",			"1"			},
  { "custom_243.EDITOR",			"RocksCE.png"		},
  { "custom_243.EDITOR.xpos",			"18"			},
  { "custom_243.EDITOR.ypos",			"15"			},

  { "custom_244",				"RocksCE.png"		},
  { "custom_244.xpos",				"3"			},
  { "custom_244.ypos",				"15"			},
  { "custom_244.frames",			"1"			},
  { "custom_244.EDITOR",			"RocksCE.png"		},
  { "custom_244.EDITOR.xpos",			"19"			},
  { "custom_244.EDITOR.ypos",			"15"			},

  { "custom_245",				"RocksCE.png"		},
  { "custom_245.xpos",				"4"			},
  { "custom_245.ypos",				"15"			},
  { "custom_245.frames",			"1"			},
  { "custom_245.EDITOR",			"RocksCE.png"		},
  { "custom_245.EDITOR.xpos",			"20"			},
  { "custom_245.EDITOR.ypos",			"15"			},

  { "custom_246",				"RocksCE.png"		},
  { "custom_246.xpos",				"5"			},
  { "custom_246.ypos",				"15"			},
  { "custom_246.frames",			"1"			},
  { "custom_246.EDITOR",			"RocksCE.png"		},
  { "custom_246.EDITOR.xpos",			"21"			},
  { "custom_246.EDITOR.ypos",			"15"			},

  { "custom_247",				"RocksCE.png"		},
  { "custom_247.xpos",				"6"			},
  { "custom_247.ypos",				"15"			},
  { "custom_247.frames",			"1"			},
  { "custom_247.EDITOR",			"RocksCE.png"		},
  { "custom_247.EDITOR.xpos",			"22"			},
  { "custom_247.EDITOR.ypos",			"15"			},

  { "custom_248",				"RocksCE.png"		},
  { "custom_248.xpos",				"7"			},
  { "custom_248.ypos",				"15"			},
  { "custom_248.frames",			"1"			},
  { "custom_248.EDITOR",			"RocksCE.png"		},
  { "custom_248.EDITOR.xpos",			"23"			},
  { "custom_248.EDITOR.ypos",			"15"			},

  { "custom_249",				"RocksCE.png"		},
  { "custom_249.xpos",				"8"			},
  { "custom_249.ypos",				"15"			},
  { "custom_249.frames",			"1"			},
  { "custom_249.EDITOR",			"RocksCE.png"		},
  { "custom_249.EDITOR.xpos",			"24"			},
  { "custom_249.EDITOR.ypos",			"15"			},

  { "custom_250",				"RocksCE.png"		},
  { "custom_250.xpos",				"9"			},
  { "custom_250.ypos",				"15"			},
  { "custom_250.frames",			"1"			},
  { "custom_250.EDITOR",			"RocksCE.png"		},
  { "custom_250.EDITOR.xpos",			"25"			},
  { "custom_250.EDITOR.ypos",			"15"			},

  { "custom_251",				"RocksCE.png"		},
  { "custom_251.xpos",				"10"			},
  { "custom_251.ypos",				"15"			},
  { "custom_251.frames",			"1"			},
  { "custom_251.EDITOR",			"RocksCE.png"		},
  { "custom_251.EDITOR.xpos",			"26"			},
  { "custom_251.EDITOR.ypos",			"15"			},

  { "custom_252",				"RocksCE.png"		},
  { "custom_252.xpos",				"11"			},
  { "custom_252.ypos",				"15"			},
  { "custom_252.frames",			"1"			},
  { "custom_252.EDITOR",			"RocksCE.png"		},
  { "custom_252.EDITOR.xpos",			"27"			},
  { "custom_252.EDITOR.ypos",			"15"			},

  { "custom_253",				"RocksCE.png"		},
  { "custom_253.xpos",				"12"			},
  { "custom_253.ypos",				"15"			},
  { "custom_253.frames",			"1"			},
  { "custom_253.EDITOR",			"RocksCE.png"		},
  { "custom_253.EDITOR.xpos",			"28"			},
  { "custom_253.EDITOR.ypos",			"15"			},

  { "custom_254",				"RocksCE.png"		},
  { "custom_254.xpos",				"13"			},
  { "custom_254.ypos",				"15"			},
  { "custom_254.frames",			"1"			},
  { "custom_254.EDITOR",			"RocksCE.png"		},
  { "custom_254.EDITOR.xpos",			"29"			},
  { "custom_254.EDITOR.ypos",			"15"			},

  { "custom_255",				"RocksCE.png"		},
  { "custom_255.xpos",				"14"			},
  { "custom_255.ypos",				"15"			},
  { "custom_255.frames",			"1"			},
  { "custom_255.EDITOR",			"RocksCE.png"		},
  { "custom_255.EDITOR.xpos",			"30"			},
  { "custom_255.EDITOR.ypos",			"15"			},

  { "custom_256",				"RocksCE.png"		},
  { "custom_256.xpos",				"15"			},
  { "custom_256.ypos",				"15"			},
  { "custom_256.frames",			"1"			},
  { "custom_256.EDITOR",			"RocksCE.png"		},
  { "custom_256.EDITOR.xpos",			"31"			},
  { "custom_256.EDITOR.ypos",			"15"			},


#endif	/* CONF_CUS_C */
