// ============================================================================
// Rocks'n'Diamonds - McDuffin Strikes Back!
// ----------------------------------------------------------------------------
// (c) 1995-2014 by Artsoft Entertainment
//                  Holger Schemel
//                  info@artsoft.org
//                  http://www.artsoft.org/
// ----------------------------------------------------------------------------
// conf_grp.c
// ============================================================================

/* ----- this file was automatically generated -- do not edit by hand ----- */

#ifndef CONF_GRP_C
#define CONF_GRP_C

/* values for graphics configuration (group elements) */

  { "group_1",					"RocksCE.png"		},
  { "group_1.xpos",				"0"			},
  { "group_1.ypos",				"16"			},
  { "group_1.frames",				"1"			},
  { "group_1.EDITOR",				"RocksCE.png"		},
  { "group_1.EDITOR.xpos",			"16"			},
  { "group_1.EDITOR.ypos",			"16"			},

  { "group_2",					"RocksCE.png"		},
  { "group_2.xpos",				"1"			},
  { "group_2.ypos",				"16"			},
  { "group_2.frames",				"1"			},
  { "group_2.EDITOR",				"RocksCE.png"		},
  { "group_2.EDITOR.xpos",			"17"			},
  { "group_2.EDITOR.ypos",			"16"			},

  { "group_3",					"RocksCE.png"		},
  { "group_3.xpos",				"2"			},
  { "group_3.ypos",				"16"			},
  { "group_3.frames",				"1"			},
  { "group_3.EDITOR",				"RocksCE.png"		},
  { "group_3.EDITOR.xpos",			"18"			},
  { "group_3.EDITOR.ypos",			"16"			},

  { "group_4",					"RocksCE.png"		},
  { "group_4.xpos",				"3"			},
  { "group_4.ypos",				"16"			},
  { "group_4.frames",				"1"			},
  { "group_4.EDITOR",				"RocksCE.png"		},
  { "group_4.EDITOR.xpos",			"19"			},
  { "group_4.EDITOR.ypos",			"16"			},

  { "group_5",					"RocksCE.png"		},
  { "group_5.xpos",				"4"			},
  { "group_5.ypos",				"16"			},
  { "group_5.frames",				"1"			},
  { "group_5.EDITOR",				"RocksCE.png"		},
  { "group_5.EDITOR.xpos",			"20"			},
  { "group_5.EDITOR.ypos",			"16"			},

  { "group_6",					"RocksCE.png"		},
  { "group_6.xpos",				"5"			},
  { "group_6.ypos",				"16"			},
  { "group_6.frames",				"1"			},
  { "group_6.EDITOR",				"RocksCE.png"		},
  { "group_6.EDITOR.xpos",			"21"			},
  { "group_6.EDITOR.ypos",			"16"			},

  { "group_7",					"RocksCE.png"		},
  { "group_7.xpos",				"6"			},
  { "group_7.ypos",				"16"			},
  { "group_7.frames",				"1"			},
  { "group_7.EDITOR",				"RocksCE.png"		},
  { "group_7.EDITOR.xpos",			"22"			},
  { "group_7.EDITOR.ypos",			"16"			},

  { "group_8",					"RocksCE.png"		},
  { "group_8.xpos",				"7"			},
  { "group_8.ypos",				"16"			},
  { "group_8.frames",				"1"			},
  { "group_8.EDITOR",				"RocksCE.png"		},
  { "group_8.EDITOR.xpos",			"23"			},
  { "group_8.EDITOR.ypos",			"16"			},

  { "group_9",					"RocksCE.png"		},
  { "group_9.xpos",				"8"			},
  { "group_9.ypos",				"16"			},
  { "group_9.frames",				"1"			},
  { "group_9.EDITOR",				"RocksCE.png"		},
  { "group_9.EDITOR.xpos",			"24"			},
  { "group_9.EDITOR.ypos",			"16"			},

  { "group_10",					"RocksCE.png"		},
  { "group_10.xpos",				"9"			},
  { "group_10.ypos",				"16"			},
  { "group_10.frames",				"1"			},
  { "group_10.EDITOR",				"RocksCE.png"		},
  { "group_10.EDITOR.xpos",			"25"			},
  { "group_10.EDITOR.ypos",			"16"			},

  { "group_11",					"RocksCE.png"		},
  { "group_11.xpos",				"10"			},
  { "group_11.ypos",				"16"			},
  { "group_11.frames",				"1"			},
  { "group_11.EDITOR",				"RocksCE.png"		},
  { "group_11.EDITOR.xpos",			"26"			},
  { "group_11.EDITOR.ypos",			"16"			},

  { "group_12",					"RocksCE.png"		},
  { "group_12.xpos",				"11"			},
  { "group_12.ypos",				"16"			},
  { "group_12.frames",				"1"			},
  { "group_12.EDITOR",				"RocksCE.png"		},
  { "group_12.EDITOR.xpos",			"27"			},
  { "group_12.EDITOR.ypos",			"16"			},

  { "group_13",					"RocksCE.png"		},
  { "group_13.xpos",				"12"			},
  { "group_13.ypos",				"16"			},
  { "group_13.frames",				"1"			},
  { "group_13.EDITOR",				"RocksCE.png"		},
  { "group_13.EDITOR.xpos",			"28"			},
  { "group_13.EDITOR.ypos",			"16"			},

  { "group_14",					"RocksCE.png"		},
  { "group_14.xpos",				"13"			},
  { "group_14.ypos",				"16"			},
  { "group_14.frames",				"1"			},
  { "group_14.EDITOR",				"RocksCE.png"		},
  { "group_14.EDITOR.xpos",			"29"			},
  { "group_14.EDITOR.ypos",			"16"			},

  { "group_15",					"RocksCE.png"		},
  { "group_15.xpos",				"14"			},
  { "group_15.ypos",				"16"			},
  { "group_15.frames",				"1"			},
  { "group_15.EDITOR",				"RocksCE.png"		},
  { "group_15.EDITOR.xpos",			"30"			},
  { "group_15.EDITOR.ypos",			"16"			},

  { "group_16",					"RocksCE.png"		},
  { "group_16.xpos",				"15"			},
  { "group_16.ypos",				"16"			},
  { "group_16.frames",				"1"			},
  { "group_16.EDITOR",				"RocksCE.png"		},
  { "group_16.EDITOR.xpos",			"31"			},
  { "group_16.EDITOR.ypos",			"16"			},

  { "group_17",					"RocksCE.png"		},
  { "group_17.xpos",				"0"			},
  { "group_17.ypos",				"17"			},
  { "group_17.frames",				"1"			},
  { "group_17.EDITOR",				"RocksCE.png"		},
  { "group_17.EDITOR.xpos",			"16"			},
  { "group_17.EDITOR.ypos",			"17"			},

  { "group_18",					"RocksCE.png"		},
  { "group_18.xpos",				"1"			},
  { "group_18.ypos",				"17"			},
  { "group_18.frames",				"1"			},
  { "group_18.EDITOR",				"RocksCE.png"		},
  { "group_18.EDITOR.xpos",			"17"			},
  { "group_18.EDITOR.ypos",			"17"			},

  { "group_19",					"RocksCE.png"		},
  { "group_19.xpos",				"2"			},
  { "group_19.ypos",				"17"			},
  { "group_19.frames",				"1"			},
  { "group_19.EDITOR",				"RocksCE.png"		},
  { "group_19.EDITOR.xpos",			"18"			},
  { "group_19.EDITOR.ypos",			"17"			},

  { "group_20",					"RocksCE.png"		},
  { "group_20.xpos",				"3"			},
  { "group_20.ypos",				"17"			},
  { "group_20.frames",				"1"			},
  { "group_20.EDITOR",				"RocksCE.png"		},
  { "group_20.EDITOR.xpos",			"19"			},
  { "group_20.EDITOR.ypos",			"17"			},

  { "group_21",					"RocksCE.png"		},
  { "group_21.xpos",				"4"			},
  { "group_21.ypos",				"17"			},
  { "group_21.frames",				"1"			},
  { "group_21.EDITOR",				"RocksCE.png"		},
  { "group_21.EDITOR.xpos",			"20"			},
  { "group_21.EDITOR.ypos",			"17"			},

  { "group_22",					"RocksCE.png"		},
  { "group_22.xpos",				"5"			},
  { "group_22.ypos",				"17"			},
  { "group_22.frames",				"1"			},
  { "group_22.EDITOR",				"RocksCE.png"		},
  { "group_22.EDITOR.xpos",			"21"			},
  { "group_22.EDITOR.ypos",			"17"			},

  { "group_23",					"RocksCE.png"		},
  { "group_23.xpos",				"6"			},
  { "group_23.ypos",				"17"			},
  { "group_23.frames",				"1"			},
  { "group_23.EDITOR",				"RocksCE.png"		},
  { "group_23.EDITOR.xpos",			"22"			},
  { "group_23.EDITOR.ypos",			"17"			},

  { "group_24",					"RocksCE.png"		},
  { "group_24.xpos",				"7"			},
  { "group_24.ypos",				"17"			},
  { "group_24.frames",				"1"			},
  { "group_24.EDITOR",				"RocksCE.png"		},
  { "group_24.EDITOR.xpos",			"23"			},
  { "group_24.EDITOR.ypos",			"17"			},

  { "group_25",					"RocksCE.png"		},
  { "group_25.xpos",				"8"			},
  { "group_25.ypos",				"17"			},
  { "group_25.frames",				"1"			},
  { "group_25.EDITOR",				"RocksCE.png"		},
  { "group_25.EDITOR.xpos",			"24"			},
  { "group_25.EDITOR.ypos",			"17"			},

  { "group_26",					"RocksCE.png"		},
  { "group_26.xpos",				"9"			},
  { "group_26.ypos",				"17"			},
  { "group_26.frames",				"1"			},
  { "group_26.EDITOR",				"RocksCE.png"		},
  { "group_26.EDITOR.xpos",			"25"			},
  { "group_26.EDITOR.ypos",			"17"			},

  { "group_27",					"RocksCE.png"		},
  { "group_27.xpos",				"10"			},
  { "group_27.ypos",				"17"			},
  { "group_27.frames",				"1"			},
  { "group_27.EDITOR",				"RocksCE.png"		},
  { "group_27.EDITOR.xpos",			"26"			},
  { "group_27.EDITOR.ypos",			"17"			},

  { "group_28",					"RocksCE.png"		},
  { "group_28.xpos",				"11"			},
  { "group_28.ypos",				"17"			},
  { "group_28.frames",				"1"			},
  { "group_28.EDITOR",				"RocksCE.png"		},
  { "group_28.EDITOR.xpos",			"27"			},
  { "group_28.EDITOR.ypos",			"17"			},

  { "group_29",					"RocksCE.png"		},
  { "group_29.xpos",				"12"			},
  { "group_29.ypos",				"17"			},
  { "group_29.frames",				"1"			},
  { "group_29.EDITOR",				"RocksCE.png"		},
  { "group_29.EDITOR.xpos",			"28"			},
  { "group_29.EDITOR.ypos",			"17"			},

  { "group_30",					"RocksCE.png"		},
  { "group_30.xpos",				"13"			},
  { "group_30.ypos",				"17"			},
  { "group_30.frames",				"1"			},
  { "group_30.EDITOR",				"RocksCE.png"		},
  { "group_30.EDITOR.xpos",			"29"			},
  { "group_30.EDITOR.ypos",			"17"			},

  { "group_31",					"RocksCE.png"		},
  { "group_31.xpos",				"14"			},
  { "group_31.ypos",				"17"			},
  { "group_31.frames",				"1"			},
  { "group_31.EDITOR",				"RocksCE.png"		},
  { "group_31.EDITOR.xpos",			"30"			},
  { "group_31.EDITOR.ypos",			"17"			},

  { "group_32",					"RocksCE.png"		},
  { "group_32.xpos",				"15"			},
  { "group_32.ypos",				"17"			},
  { "group_32.frames",				"1"			},
  { "group_32.EDITOR",				"RocksCE.png"		},
  { "group_32.EDITOR.xpos",			"31"			},
  { "group_32.EDITOR.ypos",			"17"			},


#endif	/* CONF_GRP_C */
