/***********************************************************
* Rocks'n'Diamonds -- McDuffin Strikes Back!               *
*----------------------------------------------------------*
* (c) 1995-2006 Artsoft Entertainment                      *
*               Holger Schemel                             *
*               Detmolder Strasse 189                      *
*               33604 Bielefeld                            *
*               Germany                                    *
*               e-mail: info@artsoft.org                   *
*----------------------------------------------------------*
* conf_var.c                                               *
***********************************************************/

/* ----- this file was automatically generated -- do not edit by hand ----- */

#ifndef CONF_VAR_C
#define CONF_VAR_C

/* values for image and layout parameter configuration */

struct TokenIntPtrInfo image_config_vars[] =
{
  {
    "titlemessage_initial_1.x",
    &titlemessage_initial[0].x
  },
  {
    "titlemessage_initial_1.y",
    &titlemessage_initial[0].y
  },
  {
    "titlemessage_initial_1.width",
    &titlemessage_initial[0].width
  },
  {
    "titlemessage_initial_1.height",
    &titlemessage_initial[0].height
  },
  {
    "titlemessage_initial_1.chars",
    &titlemessage_initial[0].chars
  },
  {
    "titlemessage_initial_1.lines",
    &titlemessage_initial[0].lines
  },
  {
    "titlemessage_initial_1.align",
    &titlemessage_initial[0].align
  },
  {
    "titlemessage_initial_1.font",
    &titlemessage_initial[0].font
  },
  {
    "titlemessage_initial_1.autowrap",
    &titlemessage_initial[0].autowrap
  },
  {
    "titlemessage_initial_1.centered",
    &titlemessage_initial[0].centered
  },
  {
    "titlemessage_initial_1.skip_comments",
    &titlemessage_initial[0].skip_comments
  },
  {
    "titlemessage_initial_1.sort_priority",
    &titlemessage_initial[0].sort_priority
  },
  {
    "titlemessage_initial_2.x",
    &titlemessage_initial[1].x
  },
  {
    "titlemessage_initial_2.y",
    &titlemessage_initial[1].y
  },
  {
    "titlemessage_initial_2.width",
    &titlemessage_initial[1].width
  },
  {
    "titlemessage_initial_2.height",
    &titlemessage_initial[1].height
  },
  {
    "titlemessage_initial_2.chars",
    &titlemessage_initial[1].chars
  },
  {
    "titlemessage_initial_2.lines",
    &titlemessage_initial[1].lines
  },
  {
    "titlemessage_initial_2.align",
    &titlemessage_initial[1].align
  },
  {
    "titlemessage_initial_2.font",
    &titlemessage_initial[1].font
  },
  {
    "titlemessage_initial_2.autowrap",
    &titlemessage_initial[1].autowrap
  },
  {
    "titlemessage_initial_2.centered",
    &titlemessage_initial[1].centered
  },
  {
    "titlemessage_initial_2.skip_comments",
    &titlemessage_initial[1].skip_comments
  },
  {
    "titlemessage_initial_2.sort_priority",
    &titlemessage_initial[1].sort_priority
  },
  {
    "titlemessage_initial_3.x",
    &titlemessage_initial[2].x
  },
  {
    "titlemessage_initial_3.y",
    &titlemessage_initial[2].y
  },
  {
    "titlemessage_initial_3.width",
    &titlemessage_initial[2].width
  },
  {
    "titlemessage_initial_3.height",
    &titlemessage_initial[2].height
  },
  {
    "titlemessage_initial_3.chars",
    &titlemessage_initial[2].chars
  },
  {
    "titlemessage_initial_3.lines",
    &titlemessage_initial[2].lines
  },
  {
    "titlemessage_initial_3.align",
    &titlemessage_initial[2].align
  },
  {
    "titlemessage_initial_3.font",
    &titlemessage_initial[2].font
  },
  {
    "titlemessage_initial_3.autowrap",
    &titlemessage_initial[2].autowrap
  },
  {
    "titlemessage_initial_3.centered",
    &titlemessage_initial[2].centered
  },
  {
    "titlemessage_initial_3.skip_comments",
    &titlemessage_initial[2].skip_comments
  },
  {
    "titlemessage_initial_3.sort_priority",
    &titlemessage_initial[2].sort_priority
  },
  {
    "titlemessage_initial_4.x",
    &titlemessage_initial[3].x
  },
  {
    "titlemessage_initial_4.y",
    &titlemessage_initial[3].y
  },
  {
    "titlemessage_initial_4.width",
    &titlemessage_initial[3].width
  },
  {
    "titlemessage_initial_4.height",
    &titlemessage_initial[3].height
  },
  {
    "titlemessage_initial_4.chars",
    &titlemessage_initial[3].chars
  },
  {
    "titlemessage_initial_4.lines",
    &titlemessage_initial[3].lines
  },
  {
    "titlemessage_initial_4.align",
    &titlemessage_initial[3].align
  },
  {
    "titlemessage_initial_4.font",
    &titlemessage_initial[3].font
  },
  {
    "titlemessage_initial_4.autowrap",
    &titlemessage_initial[3].autowrap
  },
  {
    "titlemessage_initial_4.centered",
    &titlemessage_initial[3].centered
  },
  {
    "titlemessage_initial_4.skip_comments",
    &titlemessage_initial[3].skip_comments
  },
  {
    "titlemessage_initial_4.sort_priority",
    &titlemessage_initial[3].sort_priority
  },
  {
    "titlemessage_initial_5.x",
    &titlemessage_initial[4].x
  },
  {
    "titlemessage_initial_5.y",
    &titlemessage_initial[4].y
  },
  {
    "titlemessage_initial_5.width",
    &titlemessage_initial[4].width
  },
  {
    "titlemessage_initial_5.height",
    &titlemessage_initial[4].height
  },
  {
    "titlemessage_initial_5.chars",
    &titlemessage_initial[4].chars
  },
  {
    "titlemessage_initial_5.lines",
    &titlemessage_initial[4].lines
  },
  {
    "titlemessage_initial_5.align",
    &titlemessage_initial[4].align
  },
  {
    "titlemessage_initial_5.font",
    &titlemessage_initial[4].font
  },
  {
    "titlemessage_initial_5.autowrap",
    &titlemessage_initial[4].autowrap
  },
  {
    "titlemessage_initial_5.centered",
    &titlemessage_initial[4].centered
  },
  {
    "titlemessage_initial_5.skip_comments",
    &titlemessage_initial[4].skip_comments
  },
  {
    "titlemessage_initial_5.sort_priority",
    &titlemessage_initial[4].sort_priority
  },
  {
    "titlemessage_1.x",
    &titlemessage[0].x
  },
  {
    "titlemessage_1.y",
    &titlemessage[0].y
  },
  {
    "titlemessage_1.width",
    &titlemessage[0].width
  },
  {
    "titlemessage_1.height",
    &titlemessage[0].height
  },
  {
    "titlemessage_1.chars",
    &titlemessage[0].chars
  },
  {
    "titlemessage_1.lines",
    &titlemessage[0].lines
  },
  {
    "titlemessage_1.align",
    &titlemessage[0].align
  },
  {
    "titlemessage_1.font",
    &titlemessage[0].font
  },
  {
    "titlemessage_1.autowrap",
    &titlemessage[0].autowrap
  },
  {
    "titlemessage_1.centered",
    &titlemessage[0].centered
  },
  {
    "titlemessage_1.skip_comments",
    &titlemessage[0].skip_comments
  },
  {
    "titlemessage_1.sort_priority",
    &titlemessage[0].sort_priority
  },
  {
    "titlemessage_2.x",
    &titlemessage[1].x
  },
  {
    "titlemessage_2.y",
    &titlemessage[1].y
  },
  {
    "titlemessage_2.width",
    &titlemessage[1].width
  },
  {
    "titlemessage_2.height",
    &titlemessage[1].height
  },
  {
    "titlemessage_2.chars",
    &titlemessage[1].chars
  },
  {
    "titlemessage_2.lines",
    &titlemessage[1].lines
  },
  {
    "titlemessage_2.align",
    &titlemessage[1].align
  },
  {
    "titlemessage_2.font",
    &titlemessage[1].font
  },
  {
    "titlemessage_2.autowrap",
    &titlemessage[1].autowrap
  },
  {
    "titlemessage_2.centered",
    &titlemessage[1].centered
  },
  {
    "titlemessage_2.skip_comments",
    &titlemessage[1].skip_comments
  },
  {
    "titlemessage_2.sort_priority",
    &titlemessage[1].sort_priority
  },
  {
    "titlemessage_3.x",
    &titlemessage[2].x
  },
  {
    "titlemessage_3.y",
    &titlemessage[2].y
  },
  {
    "titlemessage_3.width",
    &titlemessage[2].width
  },
  {
    "titlemessage_3.height",
    &titlemessage[2].height
  },
  {
    "titlemessage_3.chars",
    &titlemessage[2].chars
  },
  {
    "titlemessage_3.lines",
    &titlemessage[2].lines
  },
  {
    "titlemessage_3.align",
    &titlemessage[2].align
  },
  {
    "titlemessage_3.font",
    &titlemessage[2].font
  },
  {
    "titlemessage_3.autowrap",
    &titlemessage[2].autowrap
  },
  {
    "titlemessage_3.centered",
    &titlemessage[2].centered
  },
  {
    "titlemessage_3.skip_comments",
    &titlemessage[2].skip_comments
  },
  {
    "titlemessage_3.sort_priority",
    &titlemessage[2].sort_priority
  },
  {
    "titlemessage_4.x",
    &titlemessage[3].x
  },
  {
    "titlemessage_4.y",
    &titlemessage[3].y
  },
  {
    "titlemessage_4.width",
    &titlemessage[3].width
  },
  {
    "titlemessage_4.height",
    &titlemessage[3].height
  },
  {
    "titlemessage_4.chars",
    &titlemessage[3].chars
  },
  {
    "titlemessage_4.lines",
    &titlemessage[3].lines
  },
  {
    "titlemessage_4.align",
    &titlemessage[3].align
  },
  {
    "titlemessage_4.font",
    &titlemessage[3].font
  },
  {
    "titlemessage_4.autowrap",
    &titlemessage[3].autowrap
  },
  {
    "titlemessage_4.centered",
    &titlemessage[3].centered
  },
  {
    "titlemessage_4.skip_comments",
    &titlemessage[3].skip_comments
  },
  {
    "titlemessage_4.sort_priority",
    &titlemessage[3].sort_priority
  },
  {
    "titlemessage_5.x",
    &titlemessage[4].x
  },
  {
    "titlemessage_5.y",
    &titlemessage[4].y
  },
  {
    "titlemessage_5.width",
    &titlemessage[4].width
  },
  {
    "titlemessage_5.height",
    &titlemessage[4].height
  },
  {
    "titlemessage_5.chars",
    &titlemessage[4].chars
  },
  {
    "titlemessage_5.lines",
    &titlemessage[4].lines
  },
  {
    "titlemessage_5.align",
    &titlemessage[4].align
  },
  {
    "titlemessage_5.font",
    &titlemessage[4].font
  },
  {
    "titlemessage_5.autowrap",
    &titlemessage[4].autowrap
  },
  {
    "titlemessage_5.centered",
    &titlemessage[4].centered
  },
  {
    "titlemessage_5.skip_comments",
    &titlemessage[4].skip_comments
  },
  {
    "titlemessage_5.sort_priority",
    &titlemessage[4].sort_priority
  },
  {
    "readme.x",
    &readme.x
  },
  {
    "readme.y",
    &readme.y
  },
  {
    "readme.width",
    &readme.width
  },
  {
    "readme.height",
    &readme.height
  },
  {
    "readme.chars",
    &readme.chars
  },
  {
    "readme.lines",
    &readme.lines
  },
  {
    "readme.align",
    &readme.align
  },
  {
    "readme.font",
    &readme.font
  },
  {
    "readme.autowrap",
    &readme.autowrap
  },
  {
    "readme.centered",
    &readme.centered
  },
  {
    "readme.skip_comments",
    &readme.skip_comments
  },
  {
    "readme.sort_priority",
    &readme.sort_priority
  },
  {
    "global.num_toons",
    &global.num_toons
  },
  {
    "border.draw_masked.TITLE",
    &border.draw_masked[GFX_SPECIAL_ARG_TITLE]
  },
  {
    "border.draw_masked.MAIN",
    &border.draw_masked[GFX_SPECIAL_ARG_MAIN]
  },
  {
    "border.draw_masked.LEVELS",
    &border.draw_masked[GFX_SPECIAL_ARG_LEVELS]
  },
  {
    "border.draw_masked.SCORES",
    &border.draw_masked[GFX_SPECIAL_ARG_SCORES]
  },
  {
    "border.draw_masked.EDITOR",
    &border.draw_masked[GFX_SPECIAL_ARG_EDITOR]
  },
  {
    "border.draw_masked.INFO",
    &border.draw_masked[GFX_SPECIAL_ARG_INFO]
  },
  {
    "border.draw_masked.SETUP",
    &border.draw_masked[GFX_SPECIAL_ARG_SETUP]
  },
  {
    "border.draw_masked.PLAYING",
    &border.draw_masked[GFX_SPECIAL_ARG_PLAYING]
  },
  {
    "border.draw_masked.DOOR",
    &border.draw_masked[GFX_SPECIAL_ARG_DOOR]
  },
  {
    "title.fade_delay",
    &title.fade_delay
  },
  {
    "title.post_delay",
    &title.post_delay
  },
  {
    "title.auto_delay",
    &title.auto_delay
  },
  {
    "menu.fade_delay",
    &menu.fade_delay
  },
  {
    "menu.post_delay",
    &menu.post_delay
  },
  {
    "menu.auto_delay",
    &menu.auto_delay
  },
  {
    "menu.draw_xoffset",
    &menu.draw_xoffset[GFX_SPECIAL_ARG_DEFAULT]
  },
  {
    "menu.draw_yoffset",
    &menu.draw_yoffset[GFX_SPECIAL_ARG_DEFAULT]
  },
  {
    "menu.draw_xoffset.MAIN",
    &menu.draw_xoffset[GFX_SPECIAL_ARG_MAIN]
  },
  {
    "menu.draw_yoffset.MAIN",
    &menu.draw_yoffset[GFX_SPECIAL_ARG_MAIN]
  },
  {
    "menu.draw_xoffset.LEVELS",
    &menu.draw_xoffset[GFX_SPECIAL_ARG_LEVELS]
  },
  {
    "menu.draw_yoffset.LEVELS",
    &menu.draw_yoffset[GFX_SPECIAL_ARG_LEVELS]
  },
  {
    "menu.draw_xoffset.SCORES",
    &menu.draw_xoffset[GFX_SPECIAL_ARG_SCORES]
  },
  {
    "menu.draw_yoffset.SCORES",
    &menu.draw_yoffset[GFX_SPECIAL_ARG_SCORES]
  },
  {
    "menu.draw_xoffset.EDITOR",
    &menu.draw_xoffset[GFX_SPECIAL_ARG_EDITOR]
  },
  {
    "menu.draw_yoffset.EDITOR",
    &menu.draw_yoffset[GFX_SPECIAL_ARG_EDITOR]
  },
  {
    "menu.draw_xoffset.INFO",
    &menu.draw_xoffset[GFX_SPECIAL_ARG_INFO]
  },
  {
    "menu.draw_yoffset.INFO",
    &menu.draw_yoffset[GFX_SPECIAL_ARG_INFO]
  },
  {
    "menu.draw_xoffset.INFO[ELEMENTS]",
    &menu.draw_xoffset_info[GFX_SPECIAL_ARG_INFO_ELEMENTS]
  },
  {
    "menu.draw_yoffset.INFO[ELEMENTS]",
    &menu.draw_yoffset_info[GFX_SPECIAL_ARG_INFO_ELEMENTS]
  },
  {
    "menu.draw_xoffset.INFO[MUSIC]",
    &menu.draw_xoffset_info[GFX_SPECIAL_ARG_INFO_MUSIC]
  },
  {
    "menu.draw_yoffset.INFO[MUSIC]",
    &menu.draw_yoffset_info[GFX_SPECIAL_ARG_INFO_MUSIC]
  },
  {
    "menu.draw_xoffset.INFO[CREDITS]",
    &menu.draw_xoffset_info[GFX_SPECIAL_ARG_INFO_CREDITS]
  },
  {
    "menu.draw_yoffset.INFO[CREDITS]",
    &menu.draw_yoffset_info[GFX_SPECIAL_ARG_INFO_CREDITS]
  },
  {
    "menu.draw_xoffset.INFO[PROGRAM]",
    &menu.draw_xoffset_info[GFX_SPECIAL_ARG_INFO_PROGRAM]
  },
  {
    "menu.draw_yoffset.INFO[PROGRAM]",
    &menu.draw_yoffset_info[GFX_SPECIAL_ARG_INFO_PROGRAM]
  },
  {
    "menu.draw_xoffset.INFO[VERSION]",
    &menu.draw_xoffset_info[GFX_SPECIAL_ARG_INFO_VERSION]
  },
  {
    "menu.draw_yoffset.INFO[VERSION]",
    &menu.draw_yoffset_info[GFX_SPECIAL_ARG_INFO_VERSION]
  },
  {
    "menu.draw_xoffset.INFO[LEVELSET]",
    &menu.draw_xoffset_info[GFX_SPECIAL_ARG_INFO_LEVELSET]
  },
  {
    "menu.draw_yoffset.INFO[LEVELSET]",
    &menu.draw_yoffset_info[GFX_SPECIAL_ARG_INFO_LEVELSET]
  },
  {
    "menu.draw_xoffset.SETUP",
    &menu.draw_xoffset[GFX_SPECIAL_ARG_SETUP]
  },
  {
    "menu.draw_yoffset.SETUP",
    &menu.draw_yoffset[GFX_SPECIAL_ARG_SETUP]
  },
  {
    "menu.scrollbar_xoffset",
    &menu.scrollbar_xoffset
  },
  {
    "menu.list_size",
    &menu.list_size[GFX_SPECIAL_ARG_DEFAULT]
  },
  {
    "menu.list_size.LEVELS",
    &menu.list_size[GFX_SPECIAL_ARG_LEVELS]
  },
  {
    "menu.list_size.SCORES",
    &menu.list_size[GFX_SPECIAL_ARG_SCORES]
  },
  {
    "menu.list_size.INFO",
    &menu.list_size[GFX_SPECIAL_ARG_INFO]
  },
  {
    "main.button.name.x",
    &menu.main.button.name.x
  },
  {
    "main.button.name.y",
    &menu.main.button.name.y
  },
  {
    "main.button.levels.x",
    &menu.main.button.levels.x
  },
  {
    "main.button.levels.y",
    &menu.main.button.levels.y
  },
  {
    "main.button.scores.x",
    &menu.main.button.scores.x
  },
  {
    "main.button.scores.y",
    &menu.main.button.scores.y
  },
  {
    "main.button.editor.x",
    &menu.main.button.editor.x
  },
  {
    "main.button.editor.y",
    &menu.main.button.editor.y
  },
  {
    "main.button.info.x",
    &menu.main.button.info.x
  },
  {
    "main.button.info.y",
    &menu.main.button.info.y
  },
  {
    "main.button.game.x",
    &menu.main.button.game.x
  },
  {
    "main.button.game.y",
    &menu.main.button.game.y
  },
  {
    "main.button.setup.x",
    &menu.main.button.setup.x
  },
  {
    "main.button.setup.y",
    &menu.main.button.setup.y
  },
  {
    "main.button.quit.x",
    &menu.main.button.quit.x
  },
  {
    "main.button.quit.y",
    &menu.main.button.quit.y
  },
  {
    "main.button.prev_level.x",
    &menu.main.button.prev_level.x
  },
  {
    "main.button.prev_level.y",
    &menu.main.button.prev_level.y
  },
  {
    "main.button.next_level.x",
    &menu.main.button.next_level.x
  },
  {
    "main.button.next_level.y",
    &menu.main.button.next_level.y
  },
  {
    "main.text.name.x",
    &menu.main.text.name.x
  },
  {
    "main.text.name.y",
    &menu.main.text.name.y
  },
  {
    "main.text.name.width",
    &menu.main.text.name.width
  },
  {
    "main.text.name.height",
    &menu.main.text.name.height
  },
  {
    "main.text.name.align",
    &menu.main.text.name.align
  },
  {
    "main.text.name.font",
    &menu.main.text.name.font
  },
  {
    "main.text.levels.x",
    &menu.main.text.levels.x
  },
  {
    "main.text.levels.y",
    &menu.main.text.levels.y
  },
  {
    "main.text.levels.width",
    &menu.main.text.levels.width
  },
  {
    "main.text.levels.height",
    &menu.main.text.levels.height
  },
  {
    "main.text.levels.align",
    &menu.main.text.levels.align
  },
  {
    "main.text.levels.font",
    &menu.main.text.levels.font
  },
  {
    "main.text.scores.x",
    &menu.main.text.scores.x
  },
  {
    "main.text.scores.y",
    &menu.main.text.scores.y
  },
  {
    "main.text.scores.width",
    &menu.main.text.scores.width
  },
  {
    "main.text.scores.height",
    &menu.main.text.scores.height
  },
  {
    "main.text.scores.align",
    &menu.main.text.scores.align
  },
  {
    "main.text.scores.font",
    &menu.main.text.scores.font
  },
  {
    "main.text.editor.x",
    &menu.main.text.editor.x
  },
  {
    "main.text.editor.y",
    &menu.main.text.editor.y
  },
  {
    "main.text.editor.width",
    &menu.main.text.editor.width
  },
  {
    "main.text.editor.height",
    &menu.main.text.editor.height
  },
  {
    "main.text.editor.align",
    &menu.main.text.editor.align
  },
  {
    "main.text.editor.font",
    &menu.main.text.editor.font
  },
  {
    "main.text.info.x",
    &menu.main.text.info.x
  },
  {
    "main.text.info.y",
    &menu.main.text.info.y
  },
  {
    "main.text.info.width",
    &menu.main.text.info.width
  },
  {
    "main.text.info.height",
    &menu.main.text.info.height
  },
  {
    "main.text.info.align",
    &menu.main.text.info.align
  },
  {
    "main.text.info.font",
    &menu.main.text.info.font
  },
  {
    "main.text.game.x",
    &menu.main.text.game.x
  },
  {
    "main.text.game.y",
    &menu.main.text.game.y
  },
  {
    "main.text.game.width",
    &menu.main.text.game.width
  },
  {
    "main.text.game.height",
    &menu.main.text.game.height
  },
  {
    "main.text.game.align",
    &menu.main.text.game.align
  },
  {
    "main.text.game.font",
    &menu.main.text.game.font
  },
  {
    "main.text.setup.x",
    &menu.main.text.setup.x
  },
  {
    "main.text.setup.y",
    &menu.main.text.setup.y
  },
  {
    "main.text.setup.width",
    &menu.main.text.setup.width
  },
  {
    "main.text.setup.height",
    &menu.main.text.setup.height
  },
  {
    "main.text.setup.align",
    &menu.main.text.setup.align
  },
  {
    "main.text.setup.font",
    &menu.main.text.setup.font
  },
  {
    "main.text.quit.x",
    &menu.main.text.quit.x
  },
  {
    "main.text.quit.y",
    &menu.main.text.quit.y
  },
  {
    "main.text.quit.width",
    &menu.main.text.quit.width
  },
  {
    "main.text.quit.height",
    &menu.main.text.quit.height
  },
  {
    "main.text.quit.align",
    &menu.main.text.quit.align
  },
  {
    "main.text.quit.font",
    &menu.main.text.quit.font
  },
  {
    "main.text.current_level.x",
    &menu.main.text.current_level.x
  },
  {
    "main.text.current_level.y",
    &menu.main.text.current_level.y
  },
  {
    "main.text.current_level.align",
    &menu.main.text.current_level.align
  },
  {
    "main.text.current_level.font",
    &menu.main.text.current_level.font
  },
  {
    "main.text.first_level.x",
    &menu.main.text.first_level.x
  },
  {
    "main.text.first_level.y",
    &menu.main.text.first_level.y
  },
  {
    "main.text.first_level.align",
    &menu.main.text.first_level.align
  },
  {
    "main.text.first_level.font",
    &menu.main.text.first_level.font
  },
  {
    "main.text.last_level.x",
    &menu.main.text.last_level.x
  },
  {
    "main.text.last_level.y",
    &menu.main.text.last_level.y
  },
  {
    "main.text.last_level.align",
    &menu.main.text.last_level.align
  },
  {
    "main.text.last_level.font",
    &menu.main.text.last_level.font
  },
  {
    "main.text.level_info_1.x",
    &menu.main.text.level_info_1.x
  },
  {
    "main.text.level_info_1.y",
    &menu.main.text.level_info_1.y
  },
  {
    "main.text.level_info_1.align",
    &menu.main.text.level_info_1.align
  },
  {
    "main.text.level_info_1.chars",
    &menu.main.text.level_info_1.chars
  },
  {
    "main.text.level_info_1.font",
    &menu.main.text.level_info_1.font
  },
  {
    "main.text.level_info_2.x",
    &menu.main.text.level_info_2.x
  },
  {
    "main.text.level_info_2.y",
    &menu.main.text.level_info_2.y
  },
  {
    "main.text.level_info_2.align",
    &menu.main.text.level_info_2.align
  },
  {
    "main.text.level_info_2.chars",
    &menu.main.text.level_info_2.chars
  },
  {
    "main.text.level_info_2.font",
    &menu.main.text.level_info_2.font
  },
  {
    "main.text.level_info_2.font_header",
    &menu.main.text.level_info_2.font_alt
  },
  {
    "main.text.level_name.x",
    &menu.main.text.level_name.x
  },
  {
    "main.text.level_name.y",
    &menu.main.text.level_name.y
  },
  {
    "main.text.level_name.align",
    &menu.main.text.level_name.align
  },
  {
    "main.text.level_name.chars",
    &menu.main.text.level_name.chars
  },
  {
    "main.text.level_name.font",
    &menu.main.text.level_name.font
  },
  {
    "main.text.level_author.x",
    &menu.main.text.level_author.x
  },
  {
    "main.text.level_author.y",
    &menu.main.text.level_author.y
  },
  {
    "main.text.level_author.align",
    &menu.main.text.level_author.align
  },
  {
    "main.text.level_author.chars",
    &menu.main.text.level_author.chars
  },
  {
    "main.text.level_author.font",
    &menu.main.text.level_author.font
  },
  {
    "main.text.level_year.x",
    &menu.main.text.level_year.x
  },
  {
    "main.text.level_year.y",
    &menu.main.text.level_year.y
  },
  {
    "main.text.level_year.align",
    &menu.main.text.level_year.align
  },
  {
    "main.text.level_year.chars",
    &menu.main.text.level_year.chars
  },
  {
    "main.text.level_year.font",
    &menu.main.text.level_year.font
  },
  {
    "main.text.level_imported_from.x",
    &menu.main.text.level_imported_from.x
  },
  {
    "main.text.level_imported_from.y",
    &menu.main.text.level_imported_from.y
  },
  {
    "main.text.level_imported_from.align",
    &menu.main.text.level_imported_from.align
  },
  {
    "main.text.level_imported_from.chars",
    &menu.main.text.level_imported_from.chars
  },
  {
    "main.text.level_imported_from.font",
    &menu.main.text.level_imported_from.font
  },
  {
    "main.text.level_imported_by.x",
    &menu.main.text.level_imported_by.x
  },
  {
    "main.text.level_imported_by.y",
    &menu.main.text.level_imported_by.y
  },
  {
    "main.text.level_imported_by.align",
    &menu.main.text.level_imported_by.align
  },
  {
    "main.text.level_imported_by.chars",
    &menu.main.text.level_imported_by.chars
  },
  {
    "main.text.level_imported_by.font",
    &menu.main.text.level_imported_by.font
  },
  {
    "main.text.level_tested_by.x",
    &menu.main.text.level_tested_by.x
  },
  {
    "main.text.level_tested_by.y",
    &menu.main.text.level_tested_by.y
  },
  {
    "main.text.level_tested_by.align",
    &menu.main.text.level_tested_by.align
  },
  {
    "main.text.level_tested_by.chars",
    &menu.main.text.level_tested_by.chars
  },
  {
    "main.text.level_tested_by.font",
    &menu.main.text.level_tested_by.font
  },
  {
    "main.text.title_1.x",
    &menu.main.text.title_1.x
  },
  {
    "main.text.title_1.y",
    &menu.main.text.title_1.y
  },
  {
    "main.text.title_1.align",
    &menu.main.text.title_1.align
  },
  {
    "main.text.title_1.font",
    &menu.main.text.title_1.font
  },
  {
    "main.text.title_2.x",
    &menu.main.text.title_2.x
  },
  {
    "main.text.title_2.y",
    &menu.main.text.title_2.y
  },
  {
    "main.text.title_2.align",
    &menu.main.text.title_2.align
  },
  {
    "main.text.title_2.font",
    &menu.main.text.title_2.font
  },
  {
    "main.text.title_3.x",
    &menu.main.text.title_3.x
  },
  {
    "main.text.title_3.y",
    &menu.main.text.title_3.y
  },
  {
    "main.text.title_3.align",
    &menu.main.text.title_3.align
  },
  {
    "main.text.title_3.font",
    &menu.main.text.title_3.font
  },
  {
    "main.input.name.x",
    &menu.main.input.name.x
  },
  {
    "main.input.name.y",
    &menu.main.input.name.y
  },
  {
    "main.input.name.align",
    &menu.main.input.name.align
  },
  {
    "main.input.name.font",
    &menu.main.input.name.font
  },
  {
    "preview.x",
    &preview.x
  },
  {
    "preview.y",
    &preview.y
  },
  {
    "preview.align",
    &preview.align
  },
  {
    "preview.xsize",
    &preview.xsize
  },
  {
    "preview.ysize",
    &preview.ysize
  },
  {
    "preview.xoffset",
    &preview.xoffset
  },
  {
    "preview.yoffset",
    &preview.yoffset
  },
  {
    "preview.tile_size",
    &preview.tile_size
  },
  {
    "preview.step_offset",
    &preview.step_offset
  },
  {
    "preview.step_delay",
    &preview.step_delay
  },
  {
    "preview.anim_mode",
    &preview.anim_mode
  },
  {
    "door_1.width",
    &door_1.width
  },
  {
    "door_1.height",
    &door_1.height
  },
  {
    "door_1.step_offset",
    &door_1.step_offset
  },
  {
    "door_1.step_delay",
    &door_1.step_delay
  },
  {
    "door_1.anim_mode",
    &door_1.anim_mode
  },
  {
    "door_2.width",
    &door_2.width
  },
  {
    "door_2.height",
    &door_2.height
  },
  {
    "door_2.step_offset",
    &door_2.step_offset
  },
  {
    "door_2.step_delay",
    &door_2.step_delay
  },
  {
    "door_2.anim_mode",
    &door_2.anim_mode
  },
  {
    "game.panel.level.x",
    &game.panel.level.x
  },
  {
    "game.panel.level.y",
    &game.panel.level.y
  },
  {
    "game.panel.level.align",
    &game.panel.level.align
  },
  {
    "game.panel.level.chars",
    &game.panel.level.chars
  },
  {
    "game.panel.level.font",
    &game.panel.level.font
  },
  {
    "game.panel.level.font_narrow",
    &game.panel.level.font_alt
  },
  {
    "game.panel.gems.x",
    &game.panel.gems.x
  },
  {
    "game.panel.gems.y",
    &game.panel.gems.y
  },
  {
    "game.panel.gems.align",
    &game.panel.gems.align
  },
  {
    "game.panel.gems.chars",
    &game.panel.gems.chars
  },
  {
    "game.panel.gems.font",
    &game.panel.gems.font
  },
  {
    "game.panel.inventory.x",
    &game.panel.inventory.x
  },
  {
    "game.panel.inventory.y",
    &game.panel.inventory.y
  },
  {
    "game.panel.inventory.align",
    &game.panel.inventory.align
  },
  {
    "game.panel.inventory.chars",
    &game.panel.inventory.chars
  },
  {
    "game.panel.inventory.font",
    &game.panel.inventory.font
  },
  {
    "game.panel.keys.x",
    &game.panel.keys.x
  },
  {
    "game.panel.keys.y",
    &game.panel.keys.y
  },
  {
    "game.panel.keys.align",
    &game.panel.keys.align
  },
  {
    "game.panel.score.x",
    &game.panel.score.x
  },
  {
    "game.panel.score.y",
    &game.panel.score.y
  },
  {
    "game.panel.score.align",
    &game.panel.score.align
  },
  {
    "game.panel.score.chars",
    &game.panel.score.chars
  },
  {
    "game.panel.score.font",
    &game.panel.score.font
  },
  {
    "game.panel.time.x",
    &game.panel.time.x
  },
  {
    "game.panel.time.y",
    &game.panel.time.y
  },
  {
    "game.panel.time.align",
    &game.panel.time.align
  },
  {
    "game.panel.time.chars",
    &game.panel.time.chars
  },
  {
    "game.panel.time.font",
    &game.panel.time.font
  },
  {
    "game.panel.time.font_narrow",
    &game.panel.time.font_alt
  },
  {
    "game.panel.time_hh.x",
    &game.panel.time_hh.x
  },
  {
    "game.panel.time_hh.y",
    &game.panel.time_hh.y
  },
  {
    "game.panel.time_hh.align",
    &game.panel.time_hh.align
  },
  {
    "game.panel.time_hh.chars",
    &game.panel.time_hh.chars
  },
  {
    "game.panel.time_hh.font",
    &game.panel.time_hh.font
  },
  {
    "game.panel.time_mm.x",
    &game.panel.time_mm.x
  },
  {
    "game.panel.time_mm.y",
    &game.panel.time_mm.y
  },
  {
    "game.panel.time_mm.align",
    &game.panel.time_mm.align
  },
  {
    "game.panel.time_mm.chars",
    &game.panel.time_mm.chars
  },
  {
    "game.panel.time_mm.font",
    &game.panel.time_mm.font
  },
  {
    "game.panel.time_ss.x",
    &game.panel.time_ss.x
  },
  {
    "game.panel.time_ss.y",
    &game.panel.time_ss.y
  },
  {
    "game.panel.time_ss.align",
    &game.panel.time_ss.align
  },
  {
    "game.panel.time_ss.chars",
    &game.panel.time_ss.chars
  },
  {
    "game.panel.time_ss.font",
    &game.panel.time_ss.font
  },
  {
    "game.panel.drop_next_1.x",
    &game.panel.drop_next_1.x
  },
  {
    "game.panel.drop_next_1.y",
    &game.panel.drop_next_1.y
  },
  {
    "game.panel.drop_next_2.x",
    &game.panel.drop_next_2.x
  },
  {
    "game.panel.drop_next_2.y",
    &game.panel.drop_next_2.y
  },
  {
    "game.panel.drop_next_3.x",
    &game.panel.drop_next_3.x
  },
  {
    "game.panel.drop_next_3.y",
    &game.panel.drop_next_3.y
  },
  {
    "game.panel.drop_next_4.x",
    &game.panel.drop_next_4.x
  },
  {
    "game.panel.drop_next_4.y",
    &game.panel.drop_next_4.y
  },
  {
    "game.panel.drop_next_5.x",
    &game.panel.drop_next_5.x
  },
  {
    "game.panel.drop_next_5.y",
    &game.panel.drop_next_5.y
  },
  {
    "game.panel.drop_next_6.x",
    &game.panel.drop_next_6.x
  },
  {
    "game.panel.drop_next_6.y",
    &game.panel.drop_next_6.y
  },
  {
    "game.panel.drop_next_7.x",
    &game.panel.drop_next_7.x
  },
  {
    "game.panel.drop_next_7.y",
    &game.panel.drop_next_7.y
  },
  {
    "game.panel.drop_next_8.x",
    &game.panel.drop_next_8.x
  },
  {
    "game.panel.drop_next_8.y",
    &game.panel.drop_next_8.y
  },
  {
    "game.panel.emc_keys.x",
    &game.panel.emc_keys.x
  },
  {
    "game.panel.emc_keys.y",
    &game.panel.emc_keys.y
  },
  {
    "game.panel.emc_keys.align",
    &game.panel.emc_keys.align
  },
  {
    "game.panel.key_1.x",
    &game.panel.key_1.x
  },
  {
    "game.panel.key_1.y",
    &game.panel.key_1.y
  },
  {
    "game.panel.key_2.x",
    &game.panel.key_2.x
  },
  {
    "game.panel.key_2.y",
    &game.panel.key_2.y
  },
  {
    "game.panel.key_3.x",
    &game.panel.key_3.x
  },
  {
    "game.panel.key_3.y",
    &game.panel.key_3.y
  },
  {
    "game.panel.key_4.x",
    &game.panel.key_4.x
  },
  {
    "game.panel.key_4.y",
    &game.panel.key_4.y
  },
  {
    "game.panel.key_5.x",
    &game.panel.key_5.x
  },
  {
    "game.panel.key_5.y",
    &game.panel.key_5.y
  },
  {
    "game.panel.key_6.x",
    &game.panel.key_6.x
  },
  {
    "game.panel.key_6.y",
    &game.panel.key_6.y
  },
  {
    "game.panel.key_7.x",
    &game.panel.key_7.x
  },
  {
    "game.panel.key_7.y",
    &game.panel.key_7.y
  },
  {
    "game.panel.key_8.x",
    &game.panel.key_8.x
  },
  {
    "game.panel.key_8.y",
    &game.panel.key_8.y
  },
  {
    "game.panel.key_white.x",
    &game.panel.key_white.x
  },
  {
    "game.panel.key_white.y",
    &game.panel.key_white.y
  },
  {
    "game.panel.key_white_count.x",
    &game.panel.key_white_count.x
  },
  {
    "game.panel.key_white_count.y",
    &game.panel.key_white_count.y
  },
  {
    "game.panel.key_white_count.align",
    &game.panel.key_white_count.align
  },
  {
    "game.panel.key_white_count.chars",
    &game.panel.key_white_count.chars
  },
  {
    "game.panel.key_white_count.font",
    &game.panel.key_white_count.font
  },
  {
    "game.panel.shield_normal.x",
    &game.panel.shield_normal.x
  },
  {
    "game.panel.shield_normal.y",
    &game.panel.shield_normal.y
  },
  {
    "game.panel.shield_normal_time.x",
    &game.panel.shield_normal_time.x
  },
  {
    "game.panel.shield_normal_time.y",
    &game.panel.shield_normal_time.y
  },
  {
    "game.panel.shield_normal_time.align",
    &game.panel.shield_normal_time.align
  },
  {
    "game.panel.shield_normal_time.chars",
    &game.panel.shield_normal_time.chars
  },
  {
    "game.panel.shield_normal_time.font",
    &game.panel.shield_normal_time.font
  },
  {
    "game.panel.shield_deadly.x",
    &game.panel.shield_deadly.x
  },
  {
    "game.panel.shield_deadly.y",
    &game.panel.shield_deadly.y
  },
  {
    "game.panel.shield_deadly_time.x",
    &game.panel.shield_deadly_time.x
  },
  {
    "game.panel.shield_deadly_time.y",
    &game.panel.shield_deadly_time.y
  },
  {
    "game.panel.shield_deadly_time.align",
    &game.panel.shield_deadly_time.align
  },
  {
    "game.panel.shield_deadly_time.chars",
    &game.panel.shield_deadly_time.chars
  },
  {
    "game.panel.shield_deadly_time.font",
    &game.panel.shield_deadly_time.font
  },
  {
    "game.panel.exit.x",
    &game.panel.exit.x
  },
  {
    "game.panel.exit.y",
    &game.panel.exit.y
  },
  {
    "game.panel.em_exit.x",
    &game.panel.em_exit.x
  },
  {
    "game.panel.em_exit.y",
    &game.panel.em_exit.y
  },
  {
    "game.panel.sp_exit.x",
    &game.panel.sp_exit.x
  },
  {
    "game.panel.sp_exit.y",
    &game.panel.sp_exit.y
  },
  {
    "game.panel.steel_exit.x",
    &game.panel.steel_exit.x
  },
  {
    "game.panel.steel_exit.y",
    &game.panel.steel_exit.y
  },
  {
    "game.panel.em_steel_exit.x",
    &game.panel.em_steel_exit.x
  },
  {
    "game.panel.em_steel_exit.y",
    &game.panel.em_steel_exit.y
  },
  {
    "game.panel.emc_magic_ball.x",
    &game.panel.emc_magic_ball.x
  },
  {
    "game.panel.emc_magic_ball.y",
    &game.panel.emc_magic_ball.y
  },
  {
    "game.panel.emc_magic_ball_switch.x",
    &game.panel.emc_magic_ball_switch.x
  },
  {
    "game.panel.emc_magic_ball_switch.y",
    &game.panel.emc_magic_ball_switch.y
  },
  {
    "game.panel.emc_magic_ball_time.x",
    &game.panel.emc_magic_ball_time.x
  },
  {
    "game.panel.emc_magic_ball_time.y",
    &game.panel.emc_magic_ball_time.y
  },
  {
    "game.panel.emc_magic_ball_time.align",
    &game.panel.emc_magic_ball_time.align
  },
  {
    "game.panel.emc_magic_ball_time.chars",
    &game.panel.emc_magic_ball_time.chars
  },
  {
    "game.panel.emc_magic_ball_time.font",
    &game.panel.emc_magic_ball_time.font
  },
  {
    "game.panel.light_switch.x",
    &game.panel.light_switch.x
  },
  {
    "game.panel.light_switch.y",
    &game.panel.light_switch.y
  },
  {
    "game.panel.light_switch_time.x",
    &game.panel.light_switch_time.x
  },
  {
    "game.panel.light_switch_time.y",
    &game.panel.light_switch_time.y
  },
  {
    "game.panel.light_switch_time.align",
    &game.panel.light_switch_time.align
  },
  {
    "game.panel.light_switch_time.chars",
    &game.panel.light_switch_time.chars
  },
  {
    "game.panel.light_switch_time.font",
    &game.panel.light_switch_time.font
  },
  {
    "game.panel.timegate_switch.x",
    &game.panel.timegate_switch.x
  },
  {
    "game.panel.timegate_switch.y",
    &game.panel.timegate_switch.y
  },
  {
    "game.panel.timegate_switch_time.x",
    &game.panel.timegate_switch_time.x
  },
  {
    "game.panel.timegate_switch_time.y",
    &game.panel.timegate_switch_time.y
  },
  {
    "game.panel.timegate_switch_time.align",
    &game.panel.timegate_switch_time.align
  },
  {
    "game.panel.timegate_switch_time.chars",
    &game.panel.timegate_switch_time.chars
  },
  {
    "game.panel.timegate_switch_time.font",
    &game.panel.timegate_switch_time.font
  },
  {
    "game.panel.switchgate_switch.x",
    &game.panel.switchgate_switch.x
  },
  {
    "game.panel.switchgate_switch.y",
    &game.panel.switchgate_switch.y
  },
  {
    "game.panel.emc_lenses.x",
    &game.panel.emc_lenses.x
  },
  {
    "game.panel.emc_lenses.y",
    &game.panel.emc_lenses.y
  },
  {
    "game.panel.emc_lenses_time.x",
    &game.panel.emc_lenses_time.x
  },
  {
    "game.panel.emc_lenses_time.y",
    &game.panel.emc_lenses_time.y
  },
  {
    "game.panel.emc_lenses_time.align",
    &game.panel.emc_lenses_time.align
  },
  {
    "game.panel.emc_lenses_time.chars",
    &game.panel.emc_lenses_time.chars
  },
  {
    "game.panel.emc_lenses_time.font",
    &game.panel.emc_lenses_time.font
  },
  {
    "game.panel.emc_magnifier.x",
    &game.panel.emc_magnifier.x
  },
  {
    "game.panel.emc_magnifier.y",
    &game.panel.emc_magnifier.y
  },
  {
    "game.panel.emc_magnifier_time.x",
    &game.panel.emc_magnifier_time.x
  },
  {
    "game.panel.emc_magnifier_time.y",
    &game.panel.emc_magnifier_time.y
  },
  {
    "game.panel.emc_magnifier_time.align",
    &game.panel.emc_magnifier_time.align
  },
  {
    "game.panel.emc_magnifier_time.chars",
    &game.panel.emc_magnifier_time.chars
  },
  {
    "game.panel.emc_magnifier_time.font",
    &game.panel.emc_magnifier_time.font
  },
  {
    "game.panel.balloon_switch.x",
    &game.panel.balloon_switch.x
  },
  {
    "game.panel.balloon_switch.y",
    &game.panel.balloon_switch.y
  },
  {
    "game.panel.dynabomb_number.x",
    &game.panel.dynabomb_number.x
  },
  {
    "game.panel.dynabomb_number.y",
    &game.panel.dynabomb_number.y
  },
  {
    "game.panel.dynabomb_number.align",
    &game.panel.dynabomb_number.align
  },
  {
    "game.panel.dynabomb_number.chars",
    &game.panel.dynabomb_number.chars
  },
  {
    "game.panel.dynabomb_number.font",
    &game.panel.dynabomb_number.font
  },
  {
    "game.panel.dynabomb_size.x",
    &game.panel.dynabomb_size.x
  },
  {
    "game.panel.dynabomb_size.y",
    &game.panel.dynabomb_size.y
  },
  {
    "game.panel.dynabomb_size.align",
    &game.panel.dynabomb_size.align
  },
  {
    "game.panel.dynabomb_size.chars",
    &game.panel.dynabomb_size.chars
  },
  {
    "game.panel.dynabomb_size.font",
    &game.panel.dynabomb_size.font
  },
  {
    "game.panel.dynabomb_power.x",
    &game.panel.dynabomb_power.x
  },
  {
    "game.panel.dynabomb_power.y",
    &game.panel.dynabomb_power.y
  },
  {
    "game.panel.penguins.x",
    &game.panel.penguins.x
  },
  {
    "game.panel.penguins.y",
    &game.panel.penguins.y
  },
  {
    "game.panel.penguins.align",
    &game.panel.penguins.align
  },
  {
    "game.panel.penguins.chars",
    &game.panel.penguins.chars
  },
  {
    "game.panel.penguins.font",
    &game.panel.penguins.font
  },
  {
    "game.panel.sokoban_objects.x",
    &game.panel.sokoban_objects.x
  },
  {
    "game.panel.sokoban_objects.y",
    &game.panel.sokoban_objects.y
  },
  {
    "game.panel.sokoban_objects.align",
    &game.panel.sokoban_objects.align
  },
  {
    "game.panel.sokoban_objects.chars",
    &game.panel.sokoban_objects.chars
  },
  {
    "game.panel.sokoban_objects.font",
    &game.panel.sokoban_objects.font
  },
  {
    "game.panel.sokoban_fields.x",
    &game.panel.sokoban_fields.x
  },
  {
    "game.panel.sokoban_fields.y",
    &game.panel.sokoban_fields.y
  },
  {
    "game.panel.sokoban_fields.align",
    &game.panel.sokoban_fields.align
  },
  {
    "game.panel.sokoban_fields.chars",
    &game.panel.sokoban_fields.chars
  },
  {
    "game.panel.sokoban_fields.font",
    &game.panel.sokoban_fields.font
  },
  {
    "game.panel.robot_wheel.x",
    &game.panel.robot_wheel.x
  },
  {
    "game.panel.robot_wheel.y",
    &game.panel.robot_wheel.y
  },
  {
    "game.panel.conveyor_belt_1.x",
    &game.panel.conveyor_belt_1.x
  },
  {
    "game.panel.conveyor_belt_1.y",
    &game.panel.conveyor_belt_1.y
  },
  {
    "game.panel.conveyor_belt_1_switch.x",
    &game.panel.conveyor_belt_1_switch.x
  },
  {
    "game.panel.conveyor_belt_1_switch.y",
    &game.panel.conveyor_belt_1_switch.y
  },
  {
    "game.panel.conveyor_belt_2.x",
    &game.panel.conveyor_belt_2.x
  },
  {
    "game.panel.conveyor_belt_2.y",
    &game.panel.conveyor_belt_2.y
  },
  {
    "game.panel.conveyor_belt_2_switch.x",
    &game.panel.conveyor_belt_2_switch.x
  },
  {
    "game.panel.conveyor_belt_2_switch.y",
    &game.panel.conveyor_belt_2_switch.y
  },
  {
    "game.panel.conveyor_belt_3.x",
    &game.panel.conveyor_belt_3.x
  },
  {
    "game.panel.conveyor_belt_3.y",
    &game.panel.conveyor_belt_3.y
  },
  {
    "game.panel.conveyor_belt_3_switch.x",
    &game.panel.conveyor_belt_3_switch.x
  },
  {
    "game.panel.conveyor_belt_3_switch.y",
    &game.panel.conveyor_belt_3_switch.y
  },
  {
    "game.panel.conveyor_belt_4.x",
    &game.panel.conveyor_belt_4.x
  },
  {
    "game.panel.conveyor_belt_4.y",
    &game.panel.conveyor_belt_4.y
  },
  {
    "game.panel.conveyor_belt_4_switch.x",
    &game.panel.conveyor_belt_4_switch.x
  },
  {
    "game.panel.conveyor_belt_4_switch.y",
    &game.panel.conveyor_belt_4_switch.y
  },
  {
    "game.panel.magic_wall.x",
    &game.panel.magic_wall.x
  },
  {
    "game.panel.magic_wall.y",
    &game.panel.magic_wall.y
  },
  {
    "game.panel.magic_wall_time.x",
    &game.panel.magic_wall_time.x
  },
  {
    "game.panel.magic_wall_time.y",
    &game.panel.magic_wall_time.y
  },
  {
    "game.panel.magic_wall_time.align",
    &game.panel.magic_wall_time.align
  },
  {
    "game.panel.magic_wall_time.chars",
    &game.panel.magic_wall_time.chars
  },
  {
    "game.panel.magic_wall_time.font",
    &game.panel.magic_wall_time.font
  },
  {
    "game.panel.bd_magic_wall.x",
    &game.panel.bd_magic_wall.x
  },
  {
    "game.panel.bd_magic_wall.y",
    &game.panel.bd_magic_wall.y
  },
  {
    "game.panel.dc_magic_wall.x",
    &game.panel.dc_magic_wall.x
  },
  {
    "game.panel.dc_magic_wall.y",
    &game.panel.dc_magic_wall.y
  },
  {
    "game.panel.player_name.x",
    &game.panel.player_name.x
  },
  {
    "game.panel.player_name.y",
    &game.panel.player_name.y
  },
  {
    "game.panel.player_name.align",
    &game.panel.player_name.align
  },
  {
    "game.panel.player_name.chars",
    &game.panel.player_name.chars
  },
  {
    "game.panel.player_name.font",
    &game.panel.player_name.font
  },
  {
    "game.panel.level_name.x",
    &game.panel.level_name.x
  },
  {
    "game.panel.level_name.y",
    &game.panel.level_name.y
  },
  {
    "game.panel.level_name.align",
    &game.panel.level_name.align
  },
  {
    "game.panel.level_name.chars",
    &game.panel.level_name.chars
  },
  {
    "game.panel.level_name.font",
    &game.panel.level_name.font
  },
  {
    "game.panel.level_author.x",
    &game.panel.level_author.x
  },
  {
    "game.panel.level_author.y",
    &game.panel.level_author.y
  },
  {
    "game.panel.level_author.align",
    &game.panel.level_author.align
  },
  {
    "game.panel.level_author.chars",
    &game.panel.level_author.chars
  },
  {
    "game.panel.level_author.font",
    &game.panel.level_author.font
  },
  {
    "game.button.stop.x",
    &game.button.stop.x
  },
  {
    "game.button.stop.y",
    &game.button.stop.y
  },
  {
    "game.button.pause.x",
    &game.button.pause.x
  },
  {
    "game.button.pause.y",
    &game.button.pause.y
  },
  {
    "game.button.play.x",
    &game.button.play.x
  },
  {
    "game.button.play.y",
    &game.button.play.y
  },
  {
    "game.button.sound_music.x",
    &game.button.sound_music.x
  },
  {
    "game.button.sound_music.y",
    &game.button.sound_music.y
  },
  {
    "game.button.sound_loops.x",
    &game.button.sound_loops.x
  },
  {
    "game.button.sound_loops.y",
    &game.button.sound_loops.y
  },
  {
    "game.button.sound_simple.x",
    &game.button.sound_simple.x
  },
  {
    "game.button.sound_simple.y",
    &game.button.sound_simple.y
  },
  {
    "[player].boring_delay_fixed",
    &game.player_boring_delay_fixed
  },
  {
    "[player].boring_delay_random",
    &game.player_boring_delay_random
  },
  {
    "[player].sleeping_delay_fixed",
    &game.player_sleeping_delay_fixed
  },
  {
    "[player].sleeping_delay_random",
    &game.player_sleeping_delay_random
  },
  {
    NULL,
    NULL
  },
};

#endif	/* CONF_VAR_C */
