/***********************************************************
* Rocks'n'Diamonds -- McDuffin Strikes Back!               *
*----------------------------------------------------------*
* (c) 1995-2002 Artsoft Entertainment                      *
*               Holger Schemel                             *
*               Detmolder Strasse 189                      *
*               33604 Bielefeld                            *
*               Germany                                    *
*               e-mail: info@artsoft.org                   *
*----------------------------------------------------------*
* conf_snd.h                                               *
***********************************************************/

/* ----- this file was automatically generated -- do not edit by hand ----- */

#ifndef CONF_SND_H
#define CONF_SND_H

/* values for sounds configuration */

#define SND_BD_DIAMOND_COLLECTING				0
#define SND_BD_DIAMOND_IMPACT				1
#define SND_BD_ROCK_PUSHING					2
#define SND_BD_ROCK_IMPACT					3
#define SND_BD_MAGIC_WALL_ACTIVATING			4
#define SND_BD_MAGIC_WALL_ACTIVE				5
#define SND_BD_MAGIC_WALL_FILLING				6
#define SND_BD_AMOEBA_WAITING				7
#define SND_BD_AMOEBA_GROWING				8
#define SND_BD_AMOEBA_TURNING_TO_GEM			9
#define SND_BD_AMOEBA_TURNING_TO_ROCK			10
#define SND_BD_BUTTERFLY_MOVING				11
#define SND_BD_BUTTERFLY_WAITING				12
#define SND_BD_FIREFLY_MOVING				13
#define SND_BD_FIREFLY_WAITING				14
#define SND_SP_BASE_DIGGING					15
#define SND_SP_BUGGY_BASE_DIGGING				16
#define SND_SP_BUGGY_BASE_ACTIVE				17
#define SND_SP_INFOTRON_COLLECTING				18
#define SND_SP_INFOTRON_IMPACT				19
#define SND_SP_ZONK_PUSHING					20
#define SND_SP_ZONK_IMPACT					21
#define SND_SP_DISK_RED_COLLECTING				22
#define SND_SP_DISK_ORANGE_PUSHING				23
#define SND_SP_DISK_YELLOW_PUSHING				24
#define SND_CLASS_SP_PORT_PASSING				25
#define SND_CLASS_SP_EXIT_PASSING				26
#define SND_CLASS_SP_EXIT_OPENING				27
#define SND_SP_SNIKSNAK_MOVING				28
#define SND_SP_SNIKSNAK_WAITING				29
#define SND_SP_ELECTRON_MOVING				30
#define SND_SP_ELECTRON_WAITING				31
#define SND_SP_TERMINAL_ACTIVATING				32
#define SND_SP_TERMINAL_ACTIVE				33
#define SND_CLASS_SOKOBAN_PUSHING				34
#define SND_CLASS_SOKOBAN_FILLING				35
#define SND_CLASS_SOKOBAN_EMPTYING				36
#define SND_EMPTY_SPACE_DIGGING				37
#define SND_SAND_DIGGING					38
#define SND_EMERALD_COLLECTING				39
#define SND_EMERALD_IMPACT					40
#define SND_DIAMOND_COLLECTING				41
#define SND_DIAMOND_IMPACT					42
#define SND_DIAMOND_BREAKING				43
#define SND_ROCK_PUSHING					44
#define SND_ROCK_IMPACT					45
#define SND_BOMB_PUSHING					46
#define SND_NUT_PUSHING					47
#define SND_NUT_BREAKING					48
#define SND_NUT_IMPACT					49
#define SND_CLASS_DYNAMITE_COLLECTING				50
#define SND_CLASS_DYNAMITE_DROPPING				51
#define SND_CLASS_DYNAMITE_ACTIVE				52
#define SND_CLASS_KEY_COLLECTING				53
#define SND_CLASS_GATE_PASSING					54
#define SND_BUG_MOVING					55
#define SND_BUG_WAITING					56
#define SND_SPACESHIP_MOVING				57
#define SND_SPACESHIP_WAITING				58
#define SND_YAMYAM_MOVING					59
#define SND_YAMYAM_WAITING					60
#define SND_YAMYAM_DIGGING					61
#define SND_ROBOT_MOVING					62
#define SND_ROBOT_WAITING					63
#define SND_ROBOT_WHEEL_ACTIVATING				64
#define SND_ROBOT_WHEEL_ACTIVE				65
#define SND_MAGIC_WALL_ACTIVATING				66
#define SND_MAGIC_WALL_ACTIVE				67
#define SND_MAGIC_WALL_FILLING				68
#define SND_CLASS_AMOEBA_WAITING				69
#define SND_CLASS_AMOEBA_GROWING				70
#define SND_CLASS_AMOEBA_DROPPING				71
#define SND_ACID_SPLASHING					72
#define SND_CLASS_QUICKSAND_FILLING				73
#define SND_CLASS_QUICKSAND_EMPTYING				74
#define SND_CLASS_EXIT_OPENING					75
#define SND_CLASS_EXIT_PASSING					76
#define SND_BALLOON_MOVING					77
#define SND_BALLOON_WAITING					78
#define SND_BALLOON_PUSHING					79
#define SND_CLASS_BALLOON_SWITCH_ACTIVATING			80
#define SND_SPRING_MOVING					81
#define SND_SPRING_PUSHING					82
#define SND_SPRING_IMPACT					83
#define SND_CLASS_WALL_GROWING					84
#define SND_PEARL_COLLECTING				85
#define SND_PEARL_BREAKING					86
#define SND_PEARL_IMPACT					87
#define SND_CRYSTAL_COLLECTING				88
#define SND_CRYSTAL_IMPACT					89
#define SND_ENVELOPE_COLLECTING				90
#define SND_INVISIBLE_SAND_DIGGING				91
#define SND_SHIELD_NORMAL_COLLECTING			92
#define SND_SHIELD_NORMAL_ACTIVE				93
#define SND_SHIELD_DEADLY_COLLECTING			94
#define SND_SHIELD_DEADLY_ACTIVE				95
#define SND_EXTRA_TIME_COLLECTING				96
#define SND_MOLE_MOVING					97
#define SND_MOLE_WAITING					98
#define SND_MOLE_DIGGING					99
#define SND_CLASS_SWITCHGATE_SWITCH_ACTIVATING			100
#define SND_CLASS_SWITCHGATE_OPENING				101
#define SND_CLASS_SWITCHGATE_CLOSING				102
#define SND_CLASS_SWITCHGATE_PASSING				103
#define SND_TIMEGATE_SWITCH_ACTIVATING			104
#define SND_TIMEGATE_SWITCH_ACTIVE				105
#define SND_TIMEGATE_SWITCH_DEACTIVATING			106
#define SND_TIMEGATE_OPENING				107
#define SND_CLASS_TIMEGATE_CLOSING				108
#define SND_CLASS_TIMEGATE_PASSING				109
#define SND_CLASS_CONVEYOR_BELT_SWITCH_ACTIVATING		110
#define SND_CLASS_CONVEYOR_BELT_ACTIVE				111
#define SND_CLASS_CONVEYOR_BELT_SWITCH_DEACTIVATING		112
#define SND_LIGHT_SWITCH_ACTIVATING				113
#define SND_LIGHT_SWITCH_DEACTIVATING			114
#define SND_DX_SUPABOMB_PUSHING				115
#define SND_TRAP_DIGGING					116
#define SND_TRAP_ACTIVATING					117
#define SND_CLASS_TUBE_PASSING					118
#define SND_AMOEBA_TURNING_TO_GEM				119
#define SND_AMOEBA_TURNING_TO_ROCK				120
#define SND_SPEED_PILL_COLLECTING				121
#define SND_DYNABOMB_INCREASE_NUMBER_COLLECTING		122
#define SND_DYNABOMB_INCREASE_SIZE_COLLECTING		123
#define SND_DYNABOMB_INCREASE_POWER_COLLECTING		124
#define SND_CLASS_DYNABOMB_DROPPING				125
#define SND_CLASS_DYNABOMB_ACTIVE				126
#define SND_SATELLITE_MOVING				127
#define SND_SATELLITE_WAITING				128
#define SND_SATELLITE_PUSHING				129
#define SND_LAMP_ACTIVATING					130
#define SND_LAMP_DEACTIVATING				131
#define SND_TIME_ORB_FULL_COLLECTING			132
#define SND_TIME_ORB_FULL_IMPACT				133
#define SND_TIME_ORB_EMPTY_PUSHING				134
#define SND_TIME_ORB_EMPTY_IMPACT				135
#define SND_GAME_OF_LIFE_WAITING				136
#define SND_GAME_OF_LIFE_GROWING				137
#define SND_BIOMAZE_WAITING					138
#define SND_BIOMAZE_GROWING					139
#define SND_PACMAN_MOVING					140
#define SND_PACMAN_WAITING					141
#define SND_PACMAN_DIGGING					142
#define SND_DARK_YAMYAM_MOVING				143
#define SND_DARK_YAMYAM_WAITING				144
#define SND_DARK_YAMYAM_DIGGING				145
#define SND_PENGUIN_MOVING					146
#define SND_PENGUIN_WAITING					147
#define SND_PIG_MOVING					148
#define SND_PIG_WAITING					149
#define SND_PIG_DIGGING					150
#define SND_DRAGON_MOVING					151
#define SND_DRAGON_WAITING					152
#define SND_DRAGON_ATTACKING				153
#define SND_CLASS_PLAYER_DYING					154
#define SND_ELEMENT_EXPLODING				155
#define SND_SP_ELEMENT_EXPLODING				156
#define SND_GAME_STARTING					157
#define SND_GAME_RUNNING_OUT_OF_TIME			158
#define SND_GAME_LEVELTIME_BONUS				159
#define SND_GAME_LOSING					160
#define SND_GAME_WINNING					161
#define SND_GAME_SOKOBAN_SOLVING				162
#define SND_MENU_DOOR_OPENING				163
#define SND_MENU_DOOR_CLOSING				164
#define SND_MENU_HALL_OF_FAME				165
#define SND_MENU_INFO_SCREEN				166

#define NUM_SOUND_FILES				167

#endif	/* CONF_SND_H */
