/***********************************************************
* Rocks'n'Diamonds -- McDuffin Strikes Back!               *
*----------------------------------------------------------*
* (c) 1995-2002 Artsoft Entertainment                      *
*               Holger Schemel                             *
*               Detmolder Strasse 189                      *
*               33604 Bielefeld                            *
*               Germany                                    *
*               e-mail: info@artsoft.org                   *
*----------------------------------------------------------*
* conf_cus.c                                               *
***********************************************************/

/* ----- this file was automatically generated -- do not edit by hand ----- */

#ifndef CONF_CUS_C
#define CONF_CUS_C

/* values for graphics configuration (custom elements) */

  { "custom_1",					"RocksElements.pcx"	},
  { "custom_1.xpos",				"7"			},
  { "custom_1.ypos",				"9"			},
  { "custom_1.frames",				"1"			},
  { "custom_1.EDITOR",				"RocksElements.pcx"	},
  { "custom_1.EDITOR.xpos",			"15"			},
  { "custom_1.EDITOR.ypos",			"13"			},

  { "custom_2",					"RocksElements.pcx"	},
  { "custom_2.xpos",				"7"			},
  { "custom_2.ypos",				"9"			},
  { "custom_2.frames",				"1"			},
  { "custom_2.EDITOR",				"RocksElements.pcx"	},
  { "custom_2.EDITOR.xpos",			"15"			},
  { "custom_2.EDITOR.ypos",			"13"			},

  { "custom_3",					"RocksElements.pcx"	},
  { "custom_3.xpos",				"7"			},
  { "custom_3.ypos",				"9"			},
  { "custom_3.frames",				"1"			},
  { "custom_3.EDITOR",				"RocksElements.pcx"	},
  { "custom_3.EDITOR.xpos",			"15"			},
  { "custom_3.EDITOR.ypos",			"13"			},

  { "custom_4",					"RocksElements.pcx"	},
  { "custom_4.xpos",				"7"			},
  { "custom_4.ypos",				"9"			},
  { "custom_4.frames",				"1"			},
  { "custom_4.EDITOR",				"RocksElements.pcx"	},
  { "custom_4.EDITOR.xpos",			"15"			},
  { "custom_4.EDITOR.ypos",			"13"			},

  { "custom_5",					"RocksElements.pcx"	},
  { "custom_5.xpos",				"7"			},
  { "custom_5.ypos",				"9"			},
  { "custom_5.frames",				"1"			},
  { "custom_5.EDITOR",				"RocksElements.pcx"	},
  { "custom_5.EDITOR.xpos",			"15"			},
  { "custom_5.EDITOR.ypos",			"13"			},

  { "custom_6",					"RocksElements.pcx"	},
  { "custom_6.xpos",				"7"			},
  { "custom_6.ypos",				"9"			},
  { "custom_6.frames",				"1"			},
  { "custom_6.EDITOR",				"RocksElements.pcx"	},
  { "custom_6.EDITOR.xpos",			"15"			},
  { "custom_6.EDITOR.ypos",			"13"			},

  { "custom_7",					"RocksElements.pcx"	},
  { "custom_7.xpos",				"7"			},
  { "custom_7.ypos",				"9"			},
  { "custom_7.frames",				"1"			},
  { "custom_7.EDITOR",				"RocksElements.pcx"	},
  { "custom_7.EDITOR.xpos",			"15"			},
  { "custom_7.EDITOR.ypos",			"13"			},

  { "custom_8",					"RocksElements.pcx"	},
  { "custom_8.xpos",				"7"			},
  { "custom_8.ypos",				"9"			},
  { "custom_8.frames",				"1"			},
  { "custom_8.EDITOR",				"RocksElements.pcx"	},
  { "custom_8.EDITOR.xpos",			"15"			},
  { "custom_8.EDITOR.ypos",			"13"			},

  { "custom_9",					"RocksElements.pcx"	},
  { "custom_9.xpos",				"7"			},
  { "custom_9.ypos",				"9"			},
  { "custom_9.frames",				"1"			},
  { "custom_9.EDITOR",				"RocksElements.pcx"	},
  { "custom_9.EDITOR.xpos",			"15"			},
  { "custom_9.EDITOR.ypos",			"13"			},

  { "custom_10",				"RocksElements.pcx"	},
  { "custom_10.xpos",				"7"			},
  { "custom_10.ypos",				"9"			},
  { "custom_10.frames",				"1"			},
  { "custom_10.EDITOR",				"RocksElements.pcx"	},
  { "custom_10.EDITOR.xpos",			"15"			},
  { "custom_10.EDITOR.ypos",			"13"			},

  { "custom_11",				"RocksElements.pcx"	},
  { "custom_11.xpos",				"7"			},
  { "custom_11.ypos",				"9"			},
  { "custom_11.frames",				"1"			},
  { "custom_11.EDITOR",				"RocksElements.pcx"	},
  { "custom_11.EDITOR.xpos",			"15"			},
  { "custom_11.EDITOR.ypos",			"13"			},

  { "custom_12",				"RocksElements.pcx"	},
  { "custom_12.xpos",				"7"			},
  { "custom_12.ypos",				"9"			},
  { "custom_12.frames",				"1"			},
  { "custom_12.EDITOR",				"RocksElements.pcx"	},
  { "custom_12.EDITOR.xpos",			"15"			},
  { "custom_12.EDITOR.ypos",			"13"			},

  { "custom_13",				"RocksElements.pcx"	},
  { "custom_13.xpos",				"7"			},
  { "custom_13.ypos",				"9"			},
  { "custom_13.frames",				"1"			},
  { "custom_13.EDITOR",				"RocksElements.pcx"	},
  { "custom_13.EDITOR.xpos",			"15"			},
  { "custom_13.EDITOR.ypos",			"13"			},

  { "custom_14",				"RocksElements.pcx"	},
  { "custom_14.xpos",				"7"			},
  { "custom_14.ypos",				"9"			},
  { "custom_14.frames",				"1"			},
  { "custom_14.EDITOR",				"RocksElements.pcx"	},
  { "custom_14.EDITOR.xpos",			"15"			},
  { "custom_14.EDITOR.ypos",			"13"			},

  { "custom_15",				"RocksElements.pcx"	},
  { "custom_15.xpos",				"7"			},
  { "custom_15.ypos",				"9"			},
  { "custom_15.frames",				"1"			},
  { "custom_15.EDITOR",				"RocksElements.pcx"	},
  { "custom_15.EDITOR.xpos",			"15"			},
  { "custom_15.EDITOR.ypos",			"13"			},

  { "custom_16",				"RocksElements.pcx"	},
  { "custom_16.xpos",				"7"			},
  { "custom_16.ypos",				"9"			},
  { "custom_16.frames",				"1"			},
  { "custom_16.EDITOR",				"RocksElements.pcx"	},
  { "custom_16.EDITOR.xpos",			"15"			},
  { "custom_16.EDITOR.ypos",			"13"			},

  { "custom_17",				"RocksElements.pcx"	},
  { "custom_17.xpos",				"7"			},
  { "custom_17.ypos",				"9"			},
  { "custom_17.frames",				"1"			},
  { "custom_17.EDITOR",				"RocksElements.pcx"	},
  { "custom_17.EDITOR.xpos",			"15"			},
  { "custom_17.EDITOR.ypos",			"13"			},

  { "custom_18",				"RocksElements.pcx"	},
  { "custom_18.xpos",				"7"			},
  { "custom_18.ypos",				"9"			},
  { "custom_18.frames",				"1"			},
  { "custom_18.EDITOR",				"RocksElements.pcx"	},
  { "custom_18.EDITOR.xpos",			"15"			},
  { "custom_18.EDITOR.ypos",			"13"			},

  { "custom_19",				"RocksElements.pcx"	},
  { "custom_19.xpos",				"7"			},
  { "custom_19.ypos",				"9"			},
  { "custom_19.frames",				"1"			},
  { "custom_19.EDITOR",				"RocksElements.pcx"	},
  { "custom_19.EDITOR.xpos",			"15"			},
  { "custom_19.EDITOR.ypos",			"13"			},

  { "custom_20",				"RocksElements.pcx"	},
  { "custom_20.xpos",				"7"			},
  { "custom_20.ypos",				"9"			},
  { "custom_20.frames",				"1"			},
  { "custom_20.EDITOR",				"RocksElements.pcx"	},
  { "custom_20.EDITOR.xpos",			"15"			},
  { "custom_20.EDITOR.ypos",			"13"			},

  { "custom_21",				"RocksElements.pcx"	},
  { "custom_21.xpos",				"7"			},
  { "custom_21.ypos",				"9"			},
  { "custom_21.frames",				"1"			},
  { "custom_21.EDITOR",				"RocksElements.pcx"	},
  { "custom_21.EDITOR.xpos",			"15"			},
  { "custom_21.EDITOR.ypos",			"13"			},

  { "custom_22",				"RocksElements.pcx"	},
  { "custom_22.xpos",				"7"			},
  { "custom_22.ypos",				"9"			},
  { "custom_22.frames",				"1"			},
  { "custom_22.EDITOR",				"RocksElements.pcx"	},
  { "custom_22.EDITOR.xpos",			"15"			},
  { "custom_22.EDITOR.ypos",			"13"			},

  { "custom_23",				"RocksElements.pcx"	},
  { "custom_23.xpos",				"7"			},
  { "custom_23.ypos",				"9"			},
  { "custom_23.frames",				"1"			},
  { "custom_23.EDITOR",				"RocksElements.pcx"	},
  { "custom_23.EDITOR.xpos",			"15"			},
  { "custom_23.EDITOR.ypos",			"13"			},

  { "custom_24",				"RocksElements.pcx"	},
  { "custom_24.xpos",				"7"			},
  { "custom_24.ypos",				"9"			},
  { "custom_24.frames",				"1"			},
  { "custom_24.EDITOR",				"RocksElements.pcx"	},
  { "custom_24.EDITOR.xpos",			"15"			},
  { "custom_24.EDITOR.ypos",			"13"			},

  { "custom_25",				"RocksElements.pcx"	},
  { "custom_25.xpos",				"7"			},
  { "custom_25.ypos",				"9"			},
  { "custom_25.frames",				"1"			},
  { "custom_25.EDITOR",				"RocksElements.pcx"	},
  { "custom_25.EDITOR.xpos",			"15"			},
  { "custom_25.EDITOR.ypos",			"13"			},

  { "custom_26",				"RocksElements.pcx"	},
  { "custom_26.xpos",				"7"			},
  { "custom_26.ypos",				"9"			},
  { "custom_26.frames",				"1"			},
  { "custom_26.EDITOR",				"RocksElements.pcx"	},
  { "custom_26.EDITOR.xpos",			"15"			},
  { "custom_26.EDITOR.ypos",			"13"			},

  { "custom_27",				"RocksElements.pcx"	},
  { "custom_27.xpos",				"7"			},
  { "custom_27.ypos",				"9"			},
  { "custom_27.frames",				"1"			},
  { "custom_27.EDITOR",				"RocksElements.pcx"	},
  { "custom_27.EDITOR.xpos",			"15"			},
  { "custom_27.EDITOR.ypos",			"13"			},

  { "custom_28",				"RocksElements.pcx"	},
  { "custom_28.xpos",				"7"			},
  { "custom_28.ypos",				"9"			},
  { "custom_28.frames",				"1"			},
  { "custom_28.EDITOR",				"RocksElements.pcx"	},
  { "custom_28.EDITOR.xpos",			"15"			},
  { "custom_28.EDITOR.ypos",			"13"			},

  { "custom_29",				"RocksElements.pcx"	},
  { "custom_29.xpos",				"7"			},
  { "custom_29.ypos",				"9"			},
  { "custom_29.frames",				"1"			},
  { "custom_29.EDITOR",				"RocksElements.pcx"	},
  { "custom_29.EDITOR.xpos",			"15"			},
  { "custom_29.EDITOR.ypos",			"13"			},

  { "custom_30",				"RocksElements.pcx"	},
  { "custom_30.xpos",				"7"			},
  { "custom_30.ypos",				"9"			},
  { "custom_30.frames",				"1"			},
  { "custom_30.EDITOR",				"RocksElements.pcx"	},
  { "custom_30.EDITOR.xpos",			"15"			},
  { "custom_30.EDITOR.ypos",			"13"			},

  { "custom_31",				"RocksElements.pcx"	},
  { "custom_31.xpos",				"7"			},
  { "custom_31.ypos",				"9"			},
  { "custom_31.frames",				"1"			},
  { "custom_31.EDITOR",				"RocksElements.pcx"	},
  { "custom_31.EDITOR.xpos",			"15"			},
  { "custom_31.EDITOR.ypos",			"13"			},

  { "custom_32",				"RocksElements.pcx"	},
  { "custom_32.xpos",				"7"			},
  { "custom_32.ypos",				"9"			},
  { "custom_32.frames",				"1"			},
  { "custom_32.EDITOR",				"RocksElements.pcx"	},
  { "custom_32.EDITOR.xpos",			"15"			},
  { "custom_32.EDITOR.ypos",			"13"			},

  { "custom_33",				"RocksElements.pcx"	},
  { "custom_33.xpos",				"7"			},
  { "custom_33.ypos",				"9"			},
  { "custom_33.frames",				"1"			},
  { "custom_33.EDITOR",				"RocksElements.pcx"	},
  { "custom_33.EDITOR.xpos",			"15"			},
  { "custom_33.EDITOR.ypos",			"13"			},

  { "custom_34",				"RocksElements.pcx"	},
  { "custom_34.xpos",				"7"			},
  { "custom_34.ypos",				"9"			},
  { "custom_34.frames",				"1"			},
  { "custom_34.EDITOR",				"RocksElements.pcx"	},
  { "custom_34.EDITOR.xpos",			"15"			},
  { "custom_34.EDITOR.ypos",			"13"			},

  { "custom_35",				"RocksElements.pcx"	},
  { "custom_35.xpos",				"7"			},
  { "custom_35.ypos",				"9"			},
  { "custom_35.frames",				"1"			},
  { "custom_35.EDITOR",				"RocksElements.pcx"	},
  { "custom_35.EDITOR.xpos",			"15"			},
  { "custom_35.EDITOR.ypos",			"13"			},

  { "custom_36",				"RocksElements.pcx"	},
  { "custom_36.xpos",				"7"			},
  { "custom_36.ypos",				"9"			},
  { "custom_36.frames",				"1"			},
  { "custom_36.EDITOR",				"RocksElements.pcx"	},
  { "custom_36.EDITOR.xpos",			"15"			},
  { "custom_36.EDITOR.ypos",			"13"			},

  { "custom_37",				"RocksElements.pcx"	},
  { "custom_37.xpos",				"7"			},
  { "custom_37.ypos",				"9"			},
  { "custom_37.frames",				"1"			},
  { "custom_37.EDITOR",				"RocksElements.pcx"	},
  { "custom_37.EDITOR.xpos",			"15"			},
  { "custom_37.EDITOR.ypos",			"13"			},

  { "custom_38",				"RocksElements.pcx"	},
  { "custom_38.xpos",				"7"			},
  { "custom_38.ypos",				"9"			},
  { "custom_38.frames",				"1"			},
  { "custom_38.EDITOR",				"RocksElements.pcx"	},
  { "custom_38.EDITOR.xpos",			"15"			},
  { "custom_38.EDITOR.ypos",			"13"			},

  { "custom_39",				"RocksElements.pcx"	},
  { "custom_39.xpos",				"7"			},
  { "custom_39.ypos",				"9"			},
  { "custom_39.frames",				"1"			},
  { "custom_39.EDITOR",				"RocksElements.pcx"	},
  { "custom_39.EDITOR.xpos",			"15"			},
  { "custom_39.EDITOR.ypos",			"13"			},

  { "custom_40",				"RocksElements.pcx"	},
  { "custom_40.xpos",				"7"			},
  { "custom_40.ypos",				"9"			},
  { "custom_40.frames",				"1"			},
  { "custom_40.EDITOR",				"RocksElements.pcx"	},
  { "custom_40.EDITOR.xpos",			"15"			},
  { "custom_40.EDITOR.ypos",			"13"			},

  { "custom_41",				"RocksElements.pcx"	},
  { "custom_41.xpos",				"7"			},
  { "custom_41.ypos",				"9"			},
  { "custom_41.frames",				"1"			},
  { "custom_41.EDITOR",				"RocksElements.pcx"	},
  { "custom_41.EDITOR.xpos",			"15"			},
  { "custom_41.EDITOR.ypos",			"13"			},

  { "custom_42",				"RocksElements.pcx"	},
  { "custom_42.xpos",				"7"			},
  { "custom_42.ypos",				"9"			},
  { "custom_42.frames",				"1"			},
  { "custom_42.EDITOR",				"RocksElements.pcx"	},
  { "custom_42.EDITOR.xpos",			"15"			},
  { "custom_42.EDITOR.ypos",			"13"			},

  { "custom_43",				"RocksElements.pcx"	},
  { "custom_43.xpos",				"7"			},
  { "custom_43.ypos",				"9"			},
  { "custom_43.frames",				"1"			},
  { "custom_43.EDITOR",				"RocksElements.pcx"	},
  { "custom_43.EDITOR.xpos",			"15"			},
  { "custom_43.EDITOR.ypos",			"13"			},

  { "custom_44",				"RocksElements.pcx"	},
  { "custom_44.xpos",				"7"			},
  { "custom_44.ypos",				"9"			},
  { "custom_44.frames",				"1"			},
  { "custom_44.EDITOR",				"RocksElements.pcx"	},
  { "custom_44.EDITOR.xpos",			"15"			},
  { "custom_44.EDITOR.ypos",			"13"			},

  { "custom_45",				"RocksElements.pcx"	},
  { "custom_45.xpos",				"7"			},
  { "custom_45.ypos",				"9"			},
  { "custom_45.frames",				"1"			},
  { "custom_45.EDITOR",				"RocksElements.pcx"	},
  { "custom_45.EDITOR.xpos",			"15"			},
  { "custom_45.EDITOR.ypos",			"13"			},

  { "custom_46",				"RocksElements.pcx"	},
  { "custom_46.xpos",				"7"			},
  { "custom_46.ypos",				"9"			},
  { "custom_46.frames",				"1"			},
  { "custom_46.EDITOR",				"RocksElements.pcx"	},
  { "custom_46.EDITOR.xpos",			"15"			},
  { "custom_46.EDITOR.ypos",			"13"			},

  { "custom_47",				"RocksElements.pcx"	},
  { "custom_47.xpos",				"7"			},
  { "custom_47.ypos",				"9"			},
  { "custom_47.frames",				"1"			},
  { "custom_47.EDITOR",				"RocksElements.pcx"	},
  { "custom_47.EDITOR.xpos",			"15"			},
  { "custom_47.EDITOR.ypos",			"13"			},

  { "custom_48",				"RocksElements.pcx"	},
  { "custom_48.xpos",				"7"			},
  { "custom_48.ypos",				"9"			},
  { "custom_48.frames",				"1"			},
  { "custom_48.EDITOR",				"RocksElements.pcx"	},
  { "custom_48.EDITOR.xpos",			"15"			},
  { "custom_48.EDITOR.ypos",			"13"			},

  { "custom_49",				"RocksElements.pcx"	},
  { "custom_49.xpos",				"7"			},
  { "custom_49.ypos",				"9"			},
  { "custom_49.frames",				"1"			},
  { "custom_49.EDITOR",				"RocksElements.pcx"	},
  { "custom_49.EDITOR.xpos",			"15"			},
  { "custom_49.EDITOR.ypos",			"13"			},

  { "custom_50",				"RocksElements.pcx"	},
  { "custom_50.xpos",				"7"			},
  { "custom_50.ypos",				"9"			},
  { "custom_50.frames",				"1"			},
  { "custom_50.EDITOR",				"RocksElements.pcx"	},
  { "custom_50.EDITOR.xpos",			"15"			},
  { "custom_50.EDITOR.ypos",			"13"			},

  { "custom_51",				"RocksElements.pcx"	},
  { "custom_51.xpos",				"7"			},
  { "custom_51.ypos",				"9"			},
  { "custom_51.frames",				"1"			},
  { "custom_51.EDITOR",				"RocksElements.pcx"	},
  { "custom_51.EDITOR.xpos",			"15"			},
  { "custom_51.EDITOR.ypos",			"13"			},

  { "custom_52",				"RocksElements.pcx"	},
  { "custom_52.xpos",				"7"			},
  { "custom_52.ypos",				"9"			},
  { "custom_52.frames",				"1"			},
  { "custom_52.EDITOR",				"RocksElements.pcx"	},
  { "custom_52.EDITOR.xpos",			"15"			},
  { "custom_52.EDITOR.ypos",			"13"			},

  { "custom_53",				"RocksElements.pcx"	},
  { "custom_53.xpos",				"7"			},
  { "custom_53.ypos",				"9"			},
  { "custom_53.frames",				"1"			},
  { "custom_53.EDITOR",				"RocksElements.pcx"	},
  { "custom_53.EDITOR.xpos",			"15"			},
  { "custom_53.EDITOR.ypos",			"13"			},

  { "custom_54",				"RocksElements.pcx"	},
  { "custom_54.xpos",				"7"			},
  { "custom_54.ypos",				"9"			},
  { "custom_54.frames",				"1"			},
  { "custom_54.EDITOR",				"RocksElements.pcx"	},
  { "custom_54.EDITOR.xpos",			"15"			},
  { "custom_54.EDITOR.ypos",			"13"			},

  { "custom_55",				"RocksElements.pcx"	},
  { "custom_55.xpos",				"7"			},
  { "custom_55.ypos",				"9"			},
  { "custom_55.frames",				"1"			},
  { "custom_55.EDITOR",				"RocksElements.pcx"	},
  { "custom_55.EDITOR.xpos",			"15"			},
  { "custom_55.EDITOR.ypos",			"13"			},

  { "custom_56",				"RocksElements.pcx"	},
  { "custom_56.xpos",				"7"			},
  { "custom_56.ypos",				"9"			},
  { "custom_56.frames",				"1"			},
  { "custom_56.EDITOR",				"RocksElements.pcx"	},
  { "custom_56.EDITOR.xpos",			"15"			},
  { "custom_56.EDITOR.ypos",			"13"			},

  { "custom_57",				"RocksElements.pcx"	},
  { "custom_57.xpos",				"7"			},
  { "custom_57.ypos",				"9"			},
  { "custom_57.frames",				"1"			},
  { "custom_57.EDITOR",				"RocksElements.pcx"	},
  { "custom_57.EDITOR.xpos",			"15"			},
  { "custom_57.EDITOR.ypos",			"13"			},

  { "custom_58",				"RocksElements.pcx"	},
  { "custom_58.xpos",				"7"			},
  { "custom_58.ypos",				"9"			},
  { "custom_58.frames",				"1"			},
  { "custom_58.EDITOR",				"RocksElements.pcx"	},
  { "custom_58.EDITOR.xpos",			"15"			},
  { "custom_58.EDITOR.ypos",			"13"			},

  { "custom_59",				"RocksElements.pcx"	},
  { "custom_59.xpos",				"7"			},
  { "custom_59.ypos",				"9"			},
  { "custom_59.frames",				"1"			},
  { "custom_59.EDITOR",				"RocksElements.pcx"	},
  { "custom_59.EDITOR.xpos",			"15"			},
  { "custom_59.EDITOR.ypos",			"13"			},

  { "custom_60",				"RocksElements.pcx"	},
  { "custom_60.xpos",				"7"			},
  { "custom_60.ypos",				"9"			},
  { "custom_60.frames",				"1"			},
  { "custom_60.EDITOR",				"RocksElements.pcx"	},
  { "custom_60.EDITOR.xpos",			"15"			},
  { "custom_60.EDITOR.ypos",			"13"			},

  { "custom_61",				"RocksElements.pcx"	},
  { "custom_61.xpos",				"7"			},
  { "custom_61.ypos",				"9"			},
  { "custom_61.frames",				"1"			},
  { "custom_61.EDITOR",				"RocksElements.pcx"	},
  { "custom_61.EDITOR.xpos",			"15"			},
  { "custom_61.EDITOR.ypos",			"13"			},

  { "custom_62",				"RocksElements.pcx"	},
  { "custom_62.xpos",				"7"			},
  { "custom_62.ypos",				"9"			},
  { "custom_62.frames",				"1"			},
  { "custom_62.EDITOR",				"RocksElements.pcx"	},
  { "custom_62.EDITOR.xpos",			"15"			},
  { "custom_62.EDITOR.ypos",			"13"			},

  { "custom_63",				"RocksElements.pcx"	},
  { "custom_63.xpos",				"7"			},
  { "custom_63.ypos",				"9"			},
  { "custom_63.frames",				"1"			},
  { "custom_63.EDITOR",				"RocksElements.pcx"	},
  { "custom_63.EDITOR.xpos",			"15"			},
  { "custom_63.EDITOR.ypos",			"13"			},

  { "custom_64",				"RocksElements.pcx"	},
  { "custom_64.xpos",				"7"			},
  { "custom_64.ypos",				"9"			},
  { "custom_64.frames",				"1"			},
  { "custom_64.EDITOR",				"RocksElements.pcx"	},
  { "custom_64.EDITOR.xpos",			"15"			},
  { "custom_64.EDITOR.ypos",			"13"			},

  { "custom_65",				"RocksElements.pcx"	},
  { "custom_65.xpos",				"7"			},
  { "custom_65.ypos",				"9"			},
  { "custom_65.frames",				"1"			},
  { "custom_65.EDITOR",				"RocksElements.pcx"	},
  { "custom_65.EDITOR.xpos",			"15"			},
  { "custom_65.EDITOR.ypos",			"13"			},

  { "custom_66",				"RocksElements.pcx"	},
  { "custom_66.xpos",				"7"			},
  { "custom_66.ypos",				"9"			},
  { "custom_66.frames",				"1"			},
  { "custom_66.EDITOR",				"RocksElements.pcx"	},
  { "custom_66.EDITOR.xpos",			"15"			},
  { "custom_66.EDITOR.ypos",			"13"			},

  { "custom_67",				"RocksElements.pcx"	},
  { "custom_67.xpos",				"7"			},
  { "custom_67.ypos",				"9"			},
  { "custom_67.frames",				"1"			},
  { "custom_67.EDITOR",				"RocksElements.pcx"	},
  { "custom_67.EDITOR.xpos",			"15"			},
  { "custom_67.EDITOR.ypos",			"13"			},

  { "custom_68",				"RocksElements.pcx"	},
  { "custom_68.xpos",				"7"			},
  { "custom_68.ypos",				"9"			},
  { "custom_68.frames",				"1"			},
  { "custom_68.EDITOR",				"RocksElements.pcx"	},
  { "custom_68.EDITOR.xpos",			"15"			},
  { "custom_68.EDITOR.ypos",			"13"			},

  { "custom_69",				"RocksElements.pcx"	},
  { "custom_69.xpos",				"7"			},
  { "custom_69.ypos",				"9"			},
  { "custom_69.frames",				"1"			},
  { "custom_69.EDITOR",				"RocksElements.pcx"	},
  { "custom_69.EDITOR.xpos",			"15"			},
  { "custom_69.EDITOR.ypos",			"13"			},

  { "custom_70",				"RocksElements.pcx"	},
  { "custom_70.xpos",				"7"			},
  { "custom_70.ypos",				"9"			},
  { "custom_70.frames",				"1"			},
  { "custom_70.EDITOR",				"RocksElements.pcx"	},
  { "custom_70.EDITOR.xpos",			"15"			},
  { "custom_70.EDITOR.ypos",			"13"			},

  { "custom_71",				"RocksElements.pcx"	},
  { "custom_71.xpos",				"7"			},
  { "custom_71.ypos",				"9"			},
  { "custom_71.frames",				"1"			},
  { "custom_71.EDITOR",				"RocksElements.pcx"	},
  { "custom_71.EDITOR.xpos",			"15"			},
  { "custom_71.EDITOR.ypos",			"13"			},

  { "custom_72",				"RocksElements.pcx"	},
  { "custom_72.xpos",				"7"			},
  { "custom_72.ypos",				"9"			},
  { "custom_72.frames",				"1"			},
  { "custom_72.EDITOR",				"RocksElements.pcx"	},
  { "custom_72.EDITOR.xpos",			"15"			},
  { "custom_72.EDITOR.ypos",			"13"			},

  { "custom_73",				"RocksElements.pcx"	},
  { "custom_73.xpos",				"7"			},
  { "custom_73.ypos",				"9"			},
  { "custom_73.frames",				"1"			},
  { "custom_73.EDITOR",				"RocksElements.pcx"	},
  { "custom_73.EDITOR.xpos",			"15"			},
  { "custom_73.EDITOR.ypos",			"13"			},

  { "custom_74",				"RocksElements.pcx"	},
  { "custom_74.xpos",				"7"			},
  { "custom_74.ypos",				"9"			},
  { "custom_74.frames",				"1"			},
  { "custom_74.EDITOR",				"RocksElements.pcx"	},
  { "custom_74.EDITOR.xpos",			"15"			},
  { "custom_74.EDITOR.ypos",			"13"			},

  { "custom_75",				"RocksElements.pcx"	},
  { "custom_75.xpos",				"7"			},
  { "custom_75.ypos",				"9"			},
  { "custom_75.frames",				"1"			},
  { "custom_75.EDITOR",				"RocksElements.pcx"	},
  { "custom_75.EDITOR.xpos",			"15"			},
  { "custom_75.EDITOR.ypos",			"13"			},

  { "custom_76",				"RocksElements.pcx"	},
  { "custom_76.xpos",				"7"			},
  { "custom_76.ypos",				"9"			},
  { "custom_76.frames",				"1"			},
  { "custom_76.EDITOR",				"RocksElements.pcx"	},
  { "custom_76.EDITOR.xpos",			"15"			},
  { "custom_76.EDITOR.ypos",			"13"			},

  { "custom_77",				"RocksElements.pcx"	},
  { "custom_77.xpos",				"7"			},
  { "custom_77.ypos",				"9"			},
  { "custom_77.frames",				"1"			},
  { "custom_77.EDITOR",				"RocksElements.pcx"	},
  { "custom_77.EDITOR.xpos",			"15"			},
  { "custom_77.EDITOR.ypos",			"13"			},

  { "custom_78",				"RocksElements.pcx"	},
  { "custom_78.xpos",				"7"			},
  { "custom_78.ypos",				"9"			},
  { "custom_78.frames",				"1"			},
  { "custom_78.EDITOR",				"RocksElements.pcx"	},
  { "custom_78.EDITOR.xpos",			"15"			},
  { "custom_78.EDITOR.ypos",			"13"			},

  { "custom_79",				"RocksElements.pcx"	},
  { "custom_79.xpos",				"7"			},
  { "custom_79.ypos",				"9"			},
  { "custom_79.frames",				"1"			},
  { "custom_79.EDITOR",				"RocksElements.pcx"	},
  { "custom_79.EDITOR.xpos",			"15"			},
  { "custom_79.EDITOR.ypos",			"13"			},

  { "custom_80",				"RocksElements.pcx"	},
  { "custom_80.xpos",				"7"			},
  { "custom_80.ypos",				"9"			},
  { "custom_80.frames",				"1"			},
  { "custom_80.EDITOR",				"RocksElements.pcx"	},
  { "custom_80.EDITOR.xpos",			"15"			},
  { "custom_80.EDITOR.ypos",			"13"			},

  { "custom_81",				"RocksElements.pcx"	},
  { "custom_81.xpos",				"7"			},
  { "custom_81.ypos",				"9"			},
  { "custom_81.frames",				"1"			},
  { "custom_81.EDITOR",				"RocksElements.pcx"	},
  { "custom_81.EDITOR.xpos",			"15"			},
  { "custom_81.EDITOR.ypos",			"13"			},

  { "custom_82",				"RocksElements.pcx"	},
  { "custom_82.xpos",				"7"			},
  { "custom_82.ypos",				"9"			},
  { "custom_82.frames",				"1"			},
  { "custom_82.EDITOR",				"RocksElements.pcx"	},
  { "custom_82.EDITOR.xpos",			"15"			},
  { "custom_82.EDITOR.ypos",			"13"			},

  { "custom_83",				"RocksElements.pcx"	},
  { "custom_83.xpos",				"7"			},
  { "custom_83.ypos",				"9"			},
  { "custom_83.frames",				"1"			},
  { "custom_83.EDITOR",				"RocksElements.pcx"	},
  { "custom_83.EDITOR.xpos",			"15"			},
  { "custom_83.EDITOR.ypos",			"13"			},

  { "custom_84",				"RocksElements.pcx"	},
  { "custom_84.xpos",				"7"			},
  { "custom_84.ypos",				"9"			},
  { "custom_84.frames",				"1"			},
  { "custom_84.EDITOR",				"RocksElements.pcx"	},
  { "custom_84.EDITOR.xpos",			"15"			},
  { "custom_84.EDITOR.ypos",			"13"			},

  { "custom_85",				"RocksElements.pcx"	},
  { "custom_85.xpos",				"7"			},
  { "custom_85.ypos",				"9"			},
  { "custom_85.frames",				"1"			},
  { "custom_85.EDITOR",				"RocksElements.pcx"	},
  { "custom_85.EDITOR.xpos",			"15"			},
  { "custom_85.EDITOR.ypos",			"13"			},

  { "custom_86",				"RocksElements.pcx"	},
  { "custom_86.xpos",				"7"			},
  { "custom_86.ypos",				"9"			},
  { "custom_86.frames",				"1"			},
  { "custom_86.EDITOR",				"RocksElements.pcx"	},
  { "custom_86.EDITOR.xpos",			"15"			},
  { "custom_86.EDITOR.ypos",			"13"			},

  { "custom_87",				"RocksElements.pcx"	},
  { "custom_87.xpos",				"7"			},
  { "custom_87.ypos",				"9"			},
  { "custom_87.frames",				"1"			},
  { "custom_87.EDITOR",				"RocksElements.pcx"	},
  { "custom_87.EDITOR.xpos",			"15"			},
  { "custom_87.EDITOR.ypos",			"13"			},

  { "custom_88",				"RocksElements.pcx"	},
  { "custom_88.xpos",				"7"			},
  { "custom_88.ypos",				"9"			},
  { "custom_88.frames",				"1"			},
  { "custom_88.EDITOR",				"RocksElements.pcx"	},
  { "custom_88.EDITOR.xpos",			"15"			},
  { "custom_88.EDITOR.ypos",			"13"			},

  { "custom_89",				"RocksElements.pcx"	},
  { "custom_89.xpos",				"7"			},
  { "custom_89.ypos",				"9"			},
  { "custom_89.frames",				"1"			},
  { "custom_89.EDITOR",				"RocksElements.pcx"	},
  { "custom_89.EDITOR.xpos",			"15"			},
  { "custom_89.EDITOR.ypos",			"13"			},

  { "custom_90",				"RocksElements.pcx"	},
  { "custom_90.xpos",				"7"			},
  { "custom_90.ypos",				"9"			},
  { "custom_90.frames",				"1"			},
  { "custom_90.EDITOR",				"RocksElements.pcx"	},
  { "custom_90.EDITOR.xpos",			"15"			},
  { "custom_90.EDITOR.ypos",			"13"			},

  { "custom_91",				"RocksElements.pcx"	},
  { "custom_91.xpos",				"7"			},
  { "custom_91.ypos",				"9"			},
  { "custom_91.frames",				"1"			},
  { "custom_91.EDITOR",				"RocksElements.pcx"	},
  { "custom_91.EDITOR.xpos",			"15"			},
  { "custom_91.EDITOR.ypos",			"13"			},

  { "custom_92",				"RocksElements.pcx"	},
  { "custom_92.xpos",				"7"			},
  { "custom_92.ypos",				"9"			},
  { "custom_92.frames",				"1"			},
  { "custom_92.EDITOR",				"RocksElements.pcx"	},
  { "custom_92.EDITOR.xpos",			"15"			},
  { "custom_92.EDITOR.ypos",			"13"			},

  { "custom_93",				"RocksElements.pcx"	},
  { "custom_93.xpos",				"7"			},
  { "custom_93.ypos",				"9"			},
  { "custom_93.frames",				"1"			},
  { "custom_93.EDITOR",				"RocksElements.pcx"	},
  { "custom_93.EDITOR.xpos",			"15"			},
  { "custom_93.EDITOR.ypos",			"13"			},

  { "custom_94",				"RocksElements.pcx"	},
  { "custom_94.xpos",				"7"			},
  { "custom_94.ypos",				"9"			},
  { "custom_94.frames",				"1"			},
  { "custom_94.EDITOR",				"RocksElements.pcx"	},
  { "custom_94.EDITOR.xpos",			"15"			},
  { "custom_94.EDITOR.ypos",			"13"			},

  { "custom_95",				"RocksElements.pcx"	},
  { "custom_95.xpos",				"7"			},
  { "custom_95.ypos",				"9"			},
  { "custom_95.frames",				"1"			},
  { "custom_95.EDITOR",				"RocksElements.pcx"	},
  { "custom_95.EDITOR.xpos",			"15"			},
  { "custom_95.EDITOR.ypos",			"13"			},

  { "custom_96",				"RocksElements.pcx"	},
  { "custom_96.xpos",				"7"			},
  { "custom_96.ypos",				"9"			},
  { "custom_96.frames",				"1"			},
  { "custom_96.EDITOR",				"RocksElements.pcx"	},
  { "custom_96.EDITOR.xpos",			"15"			},
  { "custom_96.EDITOR.ypos",			"13"			},

  { "custom_97",				"RocksElements.pcx"	},
  { "custom_97.xpos",				"7"			},
  { "custom_97.ypos",				"9"			},
  { "custom_97.frames",				"1"			},
  { "custom_97.EDITOR",				"RocksElements.pcx"	},
  { "custom_97.EDITOR.xpos",			"15"			},
  { "custom_97.EDITOR.ypos",			"13"			},

  { "custom_98",				"RocksElements.pcx"	},
  { "custom_98.xpos",				"7"			},
  { "custom_98.ypos",				"9"			},
  { "custom_98.frames",				"1"			},
  { "custom_98.EDITOR",				"RocksElements.pcx"	},
  { "custom_98.EDITOR.xpos",			"15"			},
  { "custom_98.EDITOR.ypos",			"13"			},

  { "custom_99",				"RocksElements.pcx"	},
  { "custom_99.xpos",				"7"			},
  { "custom_99.ypos",				"9"			},
  { "custom_99.frames",				"1"			},
  { "custom_99.EDITOR",				"RocksElements.pcx"	},
  { "custom_99.EDITOR.xpos",			"15"			},
  { "custom_99.EDITOR.ypos",			"13"			},

  { "custom_100",				"RocksElements.pcx"	},
  { "custom_100.xpos",				"7"			},
  { "custom_100.ypos",				"9"			},
  { "custom_100.frames",			"1"			},
  { "custom_100.EDITOR",			"RocksElements.pcx"	},
  { "custom_100.EDITOR.xpos",			"15"			},
  { "custom_100.EDITOR.ypos",			"13"			},

  { "custom_101",				"RocksElements.pcx"	},
  { "custom_101.xpos",				"7"			},
  { "custom_101.ypos",				"9"			},
  { "custom_101.frames",			"1"			},
  { "custom_101.EDITOR",			"RocksElements.pcx"	},
  { "custom_101.EDITOR.xpos",			"15"			},
  { "custom_101.EDITOR.ypos",			"13"			},

  { "custom_102",				"RocksElements.pcx"	},
  { "custom_102.xpos",				"7"			},
  { "custom_102.ypos",				"9"			},
  { "custom_102.frames",			"1"			},
  { "custom_102.EDITOR",			"RocksElements.pcx"	},
  { "custom_102.EDITOR.xpos",			"15"			},
  { "custom_102.EDITOR.ypos",			"13"			},

  { "custom_103",				"RocksElements.pcx"	},
  { "custom_103.xpos",				"7"			},
  { "custom_103.ypos",				"9"			},
  { "custom_103.frames",			"1"			},
  { "custom_103.EDITOR",			"RocksElements.pcx"	},
  { "custom_103.EDITOR.xpos",			"15"			},
  { "custom_103.EDITOR.ypos",			"13"			},

  { "custom_104",				"RocksElements.pcx"	},
  { "custom_104.xpos",				"7"			},
  { "custom_104.ypos",				"9"			},
  { "custom_104.frames",			"1"			},
  { "custom_104.EDITOR",			"RocksElements.pcx"	},
  { "custom_104.EDITOR.xpos",			"15"			},
  { "custom_104.EDITOR.ypos",			"13"			},

  { "custom_105",				"RocksElements.pcx"	},
  { "custom_105.xpos",				"7"			},
  { "custom_105.ypos",				"9"			},
  { "custom_105.frames",			"1"			},
  { "custom_105.EDITOR",			"RocksElements.pcx"	},
  { "custom_105.EDITOR.xpos",			"15"			},
  { "custom_105.EDITOR.ypos",			"13"			},

  { "custom_106",				"RocksElements.pcx"	},
  { "custom_106.xpos",				"7"			},
  { "custom_106.ypos",				"9"			},
  { "custom_106.frames",			"1"			},
  { "custom_106.EDITOR",			"RocksElements.pcx"	},
  { "custom_106.EDITOR.xpos",			"15"			},
  { "custom_106.EDITOR.ypos",			"13"			},

  { "custom_107",				"RocksElements.pcx"	},
  { "custom_107.xpos",				"7"			},
  { "custom_107.ypos",				"9"			},
  { "custom_107.frames",			"1"			},
  { "custom_107.EDITOR",			"RocksElements.pcx"	},
  { "custom_107.EDITOR.xpos",			"15"			},
  { "custom_107.EDITOR.ypos",			"13"			},

  { "custom_108",				"RocksElements.pcx"	},
  { "custom_108.xpos",				"7"			},
  { "custom_108.ypos",				"9"			},
  { "custom_108.frames",			"1"			},
  { "custom_108.EDITOR",			"RocksElements.pcx"	},
  { "custom_108.EDITOR.xpos",			"15"			},
  { "custom_108.EDITOR.ypos",			"13"			},

  { "custom_109",				"RocksElements.pcx"	},
  { "custom_109.xpos",				"7"			},
  { "custom_109.ypos",				"9"			},
  { "custom_109.frames",			"1"			},
  { "custom_109.EDITOR",			"RocksElements.pcx"	},
  { "custom_109.EDITOR.xpos",			"15"			},
  { "custom_109.EDITOR.ypos",			"13"			},

  { "custom_110",				"RocksElements.pcx"	},
  { "custom_110.xpos",				"7"			},
  { "custom_110.ypos",				"9"			},
  { "custom_110.frames",			"1"			},
  { "custom_110.EDITOR",			"RocksElements.pcx"	},
  { "custom_110.EDITOR.xpos",			"15"			},
  { "custom_110.EDITOR.ypos",			"13"			},

  { "custom_111",				"RocksElements.pcx"	},
  { "custom_111.xpos",				"7"			},
  { "custom_111.ypos",				"9"			},
  { "custom_111.frames",			"1"			},
  { "custom_111.EDITOR",			"RocksElements.pcx"	},
  { "custom_111.EDITOR.xpos",			"15"			},
  { "custom_111.EDITOR.ypos",			"13"			},

  { "custom_112",				"RocksElements.pcx"	},
  { "custom_112.xpos",				"7"			},
  { "custom_112.ypos",				"9"			},
  { "custom_112.frames",			"1"			},
  { "custom_112.EDITOR",			"RocksElements.pcx"	},
  { "custom_112.EDITOR.xpos",			"15"			},
  { "custom_112.EDITOR.ypos",			"13"			},

  { "custom_113",				"RocksElements.pcx"	},
  { "custom_113.xpos",				"7"			},
  { "custom_113.ypos",				"9"			},
  { "custom_113.frames",			"1"			},
  { "custom_113.EDITOR",			"RocksElements.pcx"	},
  { "custom_113.EDITOR.xpos",			"15"			},
  { "custom_113.EDITOR.ypos",			"13"			},

  { "custom_114",				"RocksElements.pcx"	},
  { "custom_114.xpos",				"7"			},
  { "custom_114.ypos",				"9"			},
  { "custom_114.frames",			"1"			},
  { "custom_114.EDITOR",			"RocksElements.pcx"	},
  { "custom_114.EDITOR.xpos",			"15"			},
  { "custom_114.EDITOR.ypos",			"13"			},

  { "custom_115",				"RocksElements.pcx"	},
  { "custom_115.xpos",				"7"			},
  { "custom_115.ypos",				"9"			},
  { "custom_115.frames",			"1"			},
  { "custom_115.EDITOR",			"RocksElements.pcx"	},
  { "custom_115.EDITOR.xpos",			"15"			},
  { "custom_115.EDITOR.ypos",			"13"			},

  { "custom_116",				"RocksElements.pcx"	},
  { "custom_116.xpos",				"7"			},
  { "custom_116.ypos",				"9"			},
  { "custom_116.frames",			"1"			},
  { "custom_116.EDITOR",			"RocksElements.pcx"	},
  { "custom_116.EDITOR.xpos",			"15"			},
  { "custom_116.EDITOR.ypos",			"13"			},

  { "custom_117",				"RocksElements.pcx"	},
  { "custom_117.xpos",				"7"			},
  { "custom_117.ypos",				"9"			},
  { "custom_117.frames",			"1"			},
  { "custom_117.EDITOR",			"RocksElements.pcx"	},
  { "custom_117.EDITOR.xpos",			"15"			},
  { "custom_117.EDITOR.ypos",			"13"			},

  { "custom_118",				"RocksElements.pcx"	},
  { "custom_118.xpos",				"7"			},
  { "custom_118.ypos",				"9"			},
  { "custom_118.frames",			"1"			},
  { "custom_118.EDITOR",			"RocksElements.pcx"	},
  { "custom_118.EDITOR.xpos",			"15"			},
  { "custom_118.EDITOR.ypos",			"13"			},

  { "custom_119",				"RocksElements.pcx"	},
  { "custom_119.xpos",				"7"			},
  { "custom_119.ypos",				"9"			},
  { "custom_119.frames",			"1"			},
  { "custom_119.EDITOR",			"RocksElements.pcx"	},
  { "custom_119.EDITOR.xpos",			"15"			},
  { "custom_119.EDITOR.ypos",			"13"			},

  { "custom_120",				"RocksElements.pcx"	},
  { "custom_120.xpos",				"7"			},
  { "custom_120.ypos",				"9"			},
  { "custom_120.frames",			"1"			},
  { "custom_120.EDITOR",			"RocksElements.pcx"	},
  { "custom_120.EDITOR.xpos",			"15"			},
  { "custom_120.EDITOR.ypos",			"13"			},

  { "custom_121",				"RocksElements.pcx"	},
  { "custom_121.xpos",				"7"			},
  { "custom_121.ypos",				"9"			},
  { "custom_121.frames",			"1"			},
  { "custom_121.EDITOR",			"RocksElements.pcx"	},
  { "custom_121.EDITOR.xpos",			"15"			},
  { "custom_121.EDITOR.ypos",			"13"			},

  { "custom_122",				"RocksElements.pcx"	},
  { "custom_122.xpos",				"7"			},
  { "custom_122.ypos",				"9"			},
  { "custom_122.frames",			"1"			},
  { "custom_122.EDITOR",			"RocksElements.pcx"	},
  { "custom_122.EDITOR.xpos",			"15"			},
  { "custom_122.EDITOR.ypos",			"13"			},

  { "custom_123",				"RocksElements.pcx"	},
  { "custom_123.xpos",				"7"			},
  { "custom_123.ypos",				"9"			},
  { "custom_123.frames",			"1"			},
  { "custom_123.EDITOR",			"RocksElements.pcx"	},
  { "custom_123.EDITOR.xpos",			"15"			},
  { "custom_123.EDITOR.ypos",			"13"			},

  { "custom_124",				"RocksElements.pcx"	},
  { "custom_124.xpos",				"7"			},
  { "custom_124.ypos",				"9"			},
  { "custom_124.frames",			"1"			},
  { "custom_124.EDITOR",			"RocksElements.pcx"	},
  { "custom_124.EDITOR.xpos",			"15"			},
  { "custom_124.EDITOR.ypos",			"13"			},

  { "custom_125",				"RocksElements.pcx"	},
  { "custom_125.xpos",				"7"			},
  { "custom_125.ypos",				"9"			},
  { "custom_125.frames",			"1"			},
  { "custom_125.EDITOR",			"RocksElements.pcx"	},
  { "custom_125.EDITOR.xpos",			"15"			},
  { "custom_125.EDITOR.ypos",			"13"			},

  { "custom_126",				"RocksElements.pcx"	},
  { "custom_126.xpos",				"7"			},
  { "custom_126.ypos",				"9"			},
  { "custom_126.frames",			"1"			},
  { "custom_126.EDITOR",			"RocksElements.pcx"	},
  { "custom_126.EDITOR.xpos",			"15"			},
  { "custom_126.EDITOR.ypos",			"13"			},

  { "custom_127",				"RocksElements.pcx"	},
  { "custom_127.xpos",				"7"			},
  { "custom_127.ypos",				"9"			},
  { "custom_127.frames",			"1"			},
  { "custom_127.EDITOR",			"RocksElements.pcx"	},
  { "custom_127.EDITOR.xpos",			"15"			},
  { "custom_127.EDITOR.ypos",			"13"			},

  { "custom_128",				"RocksElements.pcx"	},
  { "custom_128.xpos",				"7"			},
  { "custom_128.ypos",				"9"			},
  { "custom_128.frames",			"1"			},
  { "custom_128.EDITOR",			"RocksElements.pcx"	},
  { "custom_128.EDITOR.xpos",			"15"			},
  { "custom_128.EDITOR.ypos",			"13"			},


#endif	/* CONF_CUS_C */
