/***********************************************************
* Rocks'n'Diamonds -- McDuffin Strikes Back!               *
*----------------------------------------------------------*
* (c) 1995-2002 Artsoft Entertainment                      *
*               Holger Schemel                             *
*               Detmolder Strasse 189                      *
*               33604 Bielefeld                            *
*               Germany                                    *
*               e-mail: info@artsoft.org                   *
*----------------------------------------------------------*
* conf_e2g.c                                               *
***********************************************************/

/* ----- this file was automatically generated -- do not edit by hand ----- */

#ifndef CONF_E2G_C
#define CONF_E2G_C

/* values for element/graphics mapping configuration (normal) */

static struct
{
    int element;
    int action;
    int direction;

    int graphic;
}
element_to_graphic[] =
{
  {
    EL_BD_WALL,					-1, -1,
    IMG_BD_WALL
  },
  {
    EL_BD_ROCK,					-1, -1,
    IMG_BD_ROCK
  },
  {
    EL_BD_ROCK,					ACTION_FALLING, -1,
    IMG_BD_ROCK_FALLING
  },
  {
    EL_BD_ROCK,					ACTION_MOVING, MV_BIT_LEFT,
    IMG_BD_ROCK_MOVING_LEFT
  },
  {
    EL_BD_ROCK,					ACTION_MOVING, MV_BIT_RIGHT,
    IMG_BD_ROCK_MOVING_RIGHT
  },
  {
    EL_BD_DIAMOND,				-1, -1,
    IMG_BD_DIAMOND
  },
  {
    EL_BD_DIAMOND,				ACTION_MOVING, -1,
    IMG_BD_DIAMOND_MOVING
  },
  {
    EL_BD_DIAMOND,				ACTION_FALLING, -1,
    IMG_BD_DIAMOND_FALLING
  },
  {
    EL_BD_MAGIC_WALL,				-1, -1,
    IMG_BD_MAGIC_WALL
  },
  {
    EL_BD_MAGIC_WALL_ACTIVE,			-1, -1,
    IMG_BD_MAGIC_WALL_ACTIVE
  },
  {
    EL_BD_MAGIC_WALL,				ACTION_ACTIVE, -1,
    IMG_BD_MAGIC_WALL_ACTIVE
  },
  {
    EL_BD_MAGIC_WALL_FILLING,			-1, -1,
    IMG_BD_MAGIC_WALL_FILLING
  },
  {
    EL_BD_MAGIC_WALL_FULL,			-1, -1,
    IMG_BD_MAGIC_WALL_FULL
  },
  {
    EL_BD_MAGIC_WALL_EMPTYING,			-1, -1,
    IMG_BD_MAGIC_WALL_EMPTYING
  },
  {
    EL_BD_MAGIC_WALL_DEAD,			-1, -1,
    IMG_BD_MAGIC_WALL_DEAD
  },
  {
    EL_BD_AMOEBA,				-1, -1,
    IMG_BD_AMOEBA
  },
  {
    EL_BD_BUTTERFLY,				-1, -1,
    IMG_BD_BUTTERFLY
  },
  {
    EL_BD_BUTTERFLY_RIGHT,			-1, -1,
    IMG_BD_BUTTERFLY_RIGHT
  },
  {
    EL_BD_BUTTERFLY,				-1, MV_BIT_RIGHT,
    IMG_BD_BUTTERFLY_RIGHT
  },
  {
    EL_BD_BUTTERFLY_UP,				-1, -1,
    IMG_BD_BUTTERFLY_UP
  },
  {
    EL_BD_BUTTERFLY,				-1, MV_BIT_UP,
    IMG_BD_BUTTERFLY_UP
  },
  {
    EL_BD_BUTTERFLY_LEFT,			-1, -1,
    IMG_BD_BUTTERFLY_LEFT
  },
  {
    EL_BD_BUTTERFLY,				-1, MV_BIT_LEFT,
    IMG_BD_BUTTERFLY_LEFT
  },
  {
    EL_BD_BUTTERFLY_DOWN,			-1, -1,
    IMG_BD_BUTTERFLY_DOWN
  },
  {
    EL_BD_BUTTERFLY,				-1, MV_BIT_DOWN,
    IMG_BD_BUTTERFLY_DOWN
  },
  {
    EL_BD_BUTTERFLY,				ACTION_MOVING, -1,
    IMG_BD_BUTTERFLY_MOVING
  },
  {
    EL_BD_FIREFLY,				-1, -1,
    IMG_BD_FIREFLY
  },
  {
    EL_BD_FIREFLY_RIGHT,			-1, -1,
    IMG_BD_FIREFLY_RIGHT
  },
  {
    EL_BD_FIREFLY,				-1, MV_BIT_RIGHT,
    IMG_BD_FIREFLY_RIGHT
  },
  {
    EL_BD_FIREFLY_UP,				-1, -1,
    IMG_BD_FIREFLY_UP
  },
  {
    EL_BD_FIREFLY,				-1, MV_BIT_UP,
    IMG_BD_FIREFLY_UP
  },
  {
    EL_BD_FIREFLY_LEFT,				-1, -1,
    IMG_BD_FIREFLY_LEFT
  },
  {
    EL_BD_FIREFLY,				-1, MV_BIT_LEFT,
    IMG_BD_FIREFLY_LEFT
  },
  {
    EL_BD_FIREFLY_DOWN,				-1, -1,
    IMG_BD_FIREFLY_DOWN
  },
  {
    EL_BD_FIREFLY,				-1, MV_BIT_DOWN,
    IMG_BD_FIREFLY_DOWN
  },
  {
    EL_BD_FIREFLY,				ACTION_MOVING, -1,
    IMG_BD_FIREFLY_MOVING
  },
  {
    EL_SP_EMPTY_SPACE,				-1, -1,
    IMG_SP_EMPTY_SPACE
  },
  {
    EL_SP_ZONK,					-1, -1,
    IMG_SP_ZONK
  },
  {
    EL_SP_ZONK,					ACTION_FALLING, -1,
    IMG_SP_ZONK_FALLING
  },
  {
    EL_SP_ZONK,					ACTION_MOVING, MV_BIT_LEFT,
    IMG_SP_ZONK_MOVING_LEFT
  },
  {
    EL_SP_ZONK,					ACTION_MOVING, MV_BIT_RIGHT,
    IMG_SP_ZONK_MOVING_RIGHT
  },
  {
    EL_SP_BASE,					-1, -1,
    IMG_SP_BASE
  },
  {
    EL_SP_MURPHY,				-1, -1,
    IMG_SP_MURPHY
  },
  {
    EL_SP_MURPHY,				-1, MV_BIT_LEFT,
    IMG_SP_MURPHY_LEFT
  },
  {
    EL_SP_MURPHY,				-1, MV_BIT_RIGHT,
    IMG_SP_MURPHY_RIGHT
  },
  {
    EL_SP_MURPHY,				-1, MV_BIT_UP,
    IMG_SP_MURPHY_UP
  },
  {
    EL_SP_MURPHY,				-1, MV_BIT_DOWN,
    IMG_SP_MURPHY_DOWN
  },
  {
    EL_SP_MURPHY,				ACTION_MOVING, MV_BIT_LEFT,
    IMG_SP_MURPHY_MOVING_LEFT
  },
  {
    EL_SP_MURPHY,				ACTION_MOVING, MV_BIT_RIGHT,
    IMG_SP_MURPHY_MOVING_RIGHT
  },
  {
    EL_SP_MURPHY,				ACTION_DIGGING, MV_BIT_LEFT,
    IMG_SP_MURPHY_DIGGING_LEFT
  },
  {
    EL_SP_MURPHY,				ACTION_DIGGING, MV_BIT_RIGHT,
    IMG_SP_MURPHY_DIGGING_RIGHT
  },
  {
    EL_SP_MURPHY,				ACTION_PUSHING, MV_BIT_LEFT,
    IMG_SP_MURPHY_PUSHING_LEFT
  },
  {
    EL_SP_MURPHY,				ACTION_PUSHING, MV_BIT_RIGHT,
    IMG_SP_MURPHY_PUSHING_RIGHT
  },
  {
    EL_SP_MURPHY,				ACTION_SNAPPING, MV_BIT_LEFT,
    IMG_SP_MURPHY_SNAPPING_LEFT
  },
  {
    EL_SP_MURPHY,				ACTION_SNAPPING, MV_BIT_RIGHT,
    IMG_SP_MURPHY_SNAPPING_RIGHT
  },
  {
    EL_SP_MURPHY,				ACTION_SNAPPING, MV_BIT_UP,
    IMG_SP_MURPHY_SNAPPING_UP
  },
  {
    EL_SP_MURPHY,				ACTION_SNAPPING, MV_BIT_DOWN,
    IMG_SP_MURPHY_SNAPPING_DOWN
  },
  {
    EL_SP_MURPHY_CLONE,				-1, -1,
    IMG_SP_MURPHY_CLONE
  },
  {
    EL_SP_INFOTRON,				-1, -1,
    IMG_SP_INFOTRON
  },
  {
    EL_SP_INFOTRON,				ACTION_FALLING, -1,
    IMG_SP_INFOTRON_FALLING
  },
  {
    EL_SP_CHIP_SINGLE,				-1, -1,
    IMG_SP_CHIP_SINGLE
  },
  {
    EL_SP_CHIP_LEFT,				-1, -1,
    IMG_SP_CHIP_LEFT
  },
  {
    EL_SP_CHIP_RIGHT,				-1, -1,
    IMG_SP_CHIP_RIGHT
  },
  {
    EL_SP_CHIP_UPPER,				-1, -1,
    IMG_SP_CHIP_UPPER
  },
  {
    EL_SP_CHIP_LOWER,				-1, -1,
    IMG_SP_CHIP_LOWER
  },
  {
    EL_SP_HARD_GRAY,				-1, -1,
    IMG_SP_HARD_GRAY
  },
  {
    EL_SP_HARD_GREEN,				-1, -1,
    IMG_SP_HARD_GREEN
  },
  {
    EL_SP_HARD_BLUE,				-1, -1,
    IMG_SP_HARD_BLUE
  },
  {
    EL_SP_HARD_RED,				-1, -1,
    IMG_SP_HARD_RED
  },
  {
    EL_SP_HARD_YELLOW,				-1, -1,
    IMG_SP_HARD_YELLOW
  },
  {
    EL_SP_EXIT_CLOSED,				-1, -1,
    IMG_SP_EXIT_CLOSED
  },
  {
    EL_SP_EXIT_OPEN,				-1, -1,
    IMG_SP_EXIT_OPEN
  },
  {
    EL_SP_DISK_ORANGE,				-1, -1,
    IMG_SP_DISK_ORANGE
  },
  {
    EL_SP_DISK_ORANGE,				ACTION_FALLING, -1,
    IMG_SP_DISK_ORANGE_FALLING
  },
  {
    EL_SP_DISK_ORANGE,				ACTION_PUSHING, -1,
    IMG_SP_DISK_ORANGE_PUSHING
  },
  {
    EL_SP_DISK_YELLOW,				-1, -1,
    IMG_SP_DISK_YELLOW
  },
  {
    EL_SP_DISK_YELLOW,				ACTION_PUSHING, -1,
    IMG_SP_DISK_YELLOW_PUSHING
  },
  {
    EL_SP_DISK_RED,				-1, -1,
    IMG_SP_DISK_RED
  },
  {
    EL_SP_DISK_RED,				ACTION_COLLECTING, -1,
    IMG_SP_DISK_RED_COLLECTING
  },
  {
    EL_SP_PORT1_RIGHT,				-1, -1,
    IMG_SP_PORT1_RIGHT
  },
  {
    EL_SP_PORT1_DOWN,				-1, -1,
    IMG_SP_PORT1_DOWN
  },
  {
    EL_SP_PORT1_LEFT,				-1, -1,
    IMG_SP_PORT1_LEFT
  },
  {
    EL_SP_PORT1_UP,				-1, -1,
    IMG_SP_PORT1_UP
  },
  {
    EL_SP_PORT2_RIGHT,				-1, -1,
    IMG_SP_PORT2_RIGHT
  },
  {
    EL_SP_PORT2_DOWN,				-1, -1,
    IMG_SP_PORT2_DOWN
  },
  {
    EL_SP_PORT2_LEFT,				-1, -1,
    IMG_SP_PORT2_LEFT
  },
  {
    EL_SP_PORT2_UP,				-1, -1,
    IMG_SP_PORT2_UP
  },
  {
    EL_SP_PORT_X,				-1, -1,
    IMG_SP_PORT_X
  },
  {
    EL_SP_PORT_Y,				-1, -1,
    IMG_SP_PORT_Y
  },
  {
    EL_SP_PORT_XY,				-1, -1,
    IMG_SP_PORT_XY
  },
  {
    EL_SP_SNIKSNAK,				-1, -1,
    IMG_SP_SNIKSNAK
  },
  {
    EL_SP_SNIKSNAK,				-1, MV_BIT_LEFT,
    IMG_SP_SNIKSNAK_LEFT
  },
  {
    EL_SP_SNIKSNAK,				-1, MV_BIT_RIGHT,
    IMG_SP_SNIKSNAK_RIGHT
  },
  {
    EL_SP_SNIKSNAK,				-1, MV_BIT_UP,
    IMG_SP_SNIKSNAK_UP
  },
  {
    EL_SP_SNIKSNAK,				-1, MV_BIT_DOWN,
    IMG_SP_SNIKSNAK_DOWN
  },
  {
    EL_SP_ELECTRON,				-1, -1,
    IMG_SP_ELECTRON
  },
  {
    EL_SP_TERMINAL,				-1, -1,
    IMG_SP_TERMINAL
  },
  {
    EL_SP_TERMINAL_ACTIVE,			-1, -1,
    IMG_SP_TERMINAL_ACTIVE
  },
  {
    EL_SP_TERMINAL,				ACTION_ACTIVE, -1,
    IMG_SP_TERMINAL_ACTIVE
  },
  {
    EL_SP_BUGGY_BASE,				-1, -1,
    IMG_SP_BUGGY_BASE
  },
  {
    EL_SP_BUGGY_BASE_ACTIVATING,		-1, -1,
    IMG_SP_BUGGY_BASE_ACTIVATING
  },
  {
    EL_SP_BUGGY_BASE,				ACTION_ACTIVATING, -1,
    IMG_SP_BUGGY_BASE_ACTIVATING
  },
  {
    EL_SP_BUGGY_BASE_ACTIVE,			-1, -1,
    IMG_SP_BUGGY_BASE_ACTIVE
  },
  {
    EL_SP_BUGGY_BASE,				ACTION_ACTIVE, -1,
    IMG_SP_BUGGY_BASE_ACTIVE
  },
  {
    EL_SP_HARD_BASE1,				-1, -1,
    IMG_SP_HARD_BASE1
  },
  {
    EL_SP_HARD_BASE2,				-1, -1,
    IMG_SP_HARD_BASE2
  },
  {
    EL_SP_HARD_BASE3,				-1, -1,
    IMG_SP_HARD_BASE3
  },
  {
    EL_SP_HARD_BASE4,				-1, -1,
    IMG_SP_HARD_BASE4
  },
  {
    EL_SP_HARD_BASE5,				-1, -1,
    IMG_SP_HARD_BASE5
  },
  {
    EL_SP_HARD_BASE6,				-1, -1,
    IMG_SP_HARD_BASE6
  },
  {
    EL_SOKOBAN_OBJECT,				-1, -1,
    IMG_SOKOBAN_OBJECT
  },
  {
    EL_SOKOBAN_FIELD_EMPTY,			-1, -1,
    IMG_SOKOBAN_FIELD_EMPTY
  },
  {
    EL_SOKOBAN_FIELD_FULL,			-1, -1,
    IMG_SOKOBAN_FIELD_FULL
  },
  {
    EL_EMPTY_SPACE,				-1, -1,
    IMG_EMPTY_SPACE
  },
  {
    EL_SAND,					-1, -1,
    IMG_SAND
  },
  {
    EL_SAND_CRUMBLED,				-1, -1,
    IMG_SAND_CRUMBLED
  },
  {
    EL_WALL,					-1, -1,
    IMG_WALL
  },
  {
    EL_WALL_CRUMBLED,				-1, -1,
    IMG_WALL_CRUMBLED
  },
  {
    EL_STEELWALL,				-1, -1,
    IMG_STEELWALL
  },
  {
    EL_ROCK,					-1, -1,
    IMG_ROCK
  },
  {
    EL_ROCK,					ACTION_FALLING, -1,
    IMG_ROCK_FALLING
  },
  {
    EL_ROCK,					ACTION_MOVING, MV_BIT_LEFT,
    IMG_ROCK_MOVING_LEFT
  },
  {
    EL_ROCK,					ACTION_MOVING, MV_BIT_RIGHT,
    IMG_ROCK_MOVING_RIGHT
  },
  {
    EL_EMERALD,					-1, -1,
    IMG_EMERALD
  },
  {
    EL_EMERALD,					ACTION_MOVING, -1,
    IMG_EMERALD_MOVING
  },
  {
    EL_EMERALD,					ACTION_FALLING, -1,
    IMG_EMERALD_FALLING
  },
  {
    EL_DIAMOND,					-1, -1,
    IMG_DIAMOND
  },
  {
    EL_DIAMOND,					ACTION_MOVING, -1,
    IMG_DIAMOND_MOVING
  },
  {
    EL_DIAMOND,					ACTION_FALLING, -1,
    IMG_DIAMOND_FALLING
  },
  {
    EL_BOMB,					-1, -1,
    IMG_BOMB
  },
  {
    EL_NUT,					-1, -1,
    IMG_NUT
  },
  {
    EL_NUT,					ACTION_FALLING, -1,
    IMG_NUT_FALLING
  },
  {
    EL_NUT,					ACTION_MOVING, MV_BIT_LEFT,
    IMG_NUT_MOVING_LEFT
  },
  {
    EL_NUT,					ACTION_MOVING, MV_BIT_RIGHT,
    IMG_NUT_MOVING_RIGHT
  },
  {
    EL_NUT_CRACKING,				-1, -1,
    IMG_NUT_CRACKING
  },
  {
    EL_NUT,					ACTION_CRACKING, -1,
    IMG_NUT_CRACKING
  },
  {
    EL_DYNAMITE,				-1, -1,
    IMG_DYNAMITE
  },
  {
    EL_DYNAMITE_ACTIVE,				-1, -1,
    IMG_DYNAMITE_ACTIVE
  },
  {
    EL_DYNAMITE,				ACTION_ACTIVE, -1,
    IMG_DYNAMITE_ACTIVE
  },
  {
    EL_WALL_EMERALD,				-1, -1,
    IMG_WALL_EMERALD
  },
  {
    EL_WALL_DIAMOND,				-1, -1,
    IMG_WALL_DIAMOND
  },
  {
    EL_BUG_RIGHT,				-1, -1,
    IMG_BUG_RIGHT
  },
  {
    EL_BUG,					-1, MV_BIT_RIGHT,
    IMG_BUG_RIGHT
  },
  {
    EL_BUG_UP,					-1, -1,
    IMG_BUG_UP
  },
  {
    EL_BUG,					-1, MV_BIT_UP,
    IMG_BUG_UP
  },
  {
    EL_BUG_LEFT,				-1, -1,
    IMG_BUG_LEFT
  },
  {
    EL_BUG,					-1, MV_BIT_LEFT,
    IMG_BUG_LEFT
  },
  {
    EL_BUG_DOWN,				-1, -1,
    IMG_BUG_DOWN
  },
  {
    EL_BUG,					-1, MV_BIT_DOWN,
    IMG_BUG_DOWN
  },
  {
    EL_SPACESHIP_RIGHT,				-1, -1,
    IMG_SPACESHIP_RIGHT
  },
  {
    EL_SPACESHIP,				-1, MV_BIT_RIGHT,
    IMG_SPACESHIP_RIGHT
  },
  {
    EL_SPACESHIP_UP,				-1, -1,
    IMG_SPACESHIP_UP
  },
  {
    EL_SPACESHIP,				-1, MV_BIT_UP,
    IMG_SPACESHIP_UP
  },
  {
    EL_SPACESHIP_LEFT,				-1, -1,
    IMG_SPACESHIP_LEFT
  },
  {
    EL_SPACESHIP,				-1, MV_BIT_LEFT,
    IMG_SPACESHIP_LEFT
  },
  {
    EL_SPACESHIP_DOWN,				-1, -1,
    IMG_SPACESHIP_DOWN
  },
  {
    EL_SPACESHIP,				-1, MV_BIT_DOWN,
    IMG_SPACESHIP_DOWN
  },
  {
    EL_YAMYAM,					-1, -1,
    IMG_YAMYAM
  },
  {
    EL_YAMYAM,					ACTION_MOVING, -1,
    IMG_YAMYAM_MOVING
  },
  {
    EL_ROBOT,					-1, -1,
    IMG_ROBOT
  },
  {
    EL_ROBOT,					ACTION_MOVING, -1,
    IMG_ROBOT_MOVING
  },
  {
    EL_ROBOT_WHEEL,				-1, -1,
    IMG_ROBOT_WHEEL
  },
  {
    EL_ROBOT_WHEEL_ACTIVE,			-1, -1,
    IMG_ROBOT_WHEEL_ACTIVE
  },
  {
    EL_ROBOT_WHEEL,				ACTION_ACTIVE, -1,
    IMG_ROBOT_WHEEL_ACTIVE
  },
  {
    EL_MAGIC_WALL,				-1, -1,
    IMG_MAGIC_WALL
  },
  {
    EL_MAGIC_WALL_ACTIVE,			-1, -1,
    IMG_MAGIC_WALL_ACTIVE
  },
  {
    EL_MAGIC_WALL,				ACTION_ACTIVE, -1,
    IMG_MAGIC_WALL_ACTIVE
  },
  {
    EL_MAGIC_WALL_FILLING,			-1, -1,
    IMG_MAGIC_WALL_FILLING
  },
  {
    EL_MAGIC_WALL_FULL,				-1, -1,
    IMG_MAGIC_WALL_FULL
  },
  {
    EL_MAGIC_WALL_EMPTYING,			-1, -1,
    IMG_MAGIC_WALL_EMPTYING
  },
  {
    EL_MAGIC_WALL_DEAD,				-1, -1,
    IMG_MAGIC_WALL_DEAD
  },
  {
    EL_QUICKSAND_EMPTY,				-1, -1,
    IMG_QUICKSAND_EMPTY
  },
  {
    EL_QUICKSAND_FILLING,			-1, -1,
    IMG_QUICKSAND_FILLING
  },
  {
    EL_QUICKSAND_FULL,				-1, -1,
    IMG_QUICKSAND_FULL
  },
  {
    EL_QUICKSAND_EMPTYING,			-1, -1,
    IMG_QUICKSAND_EMPTYING
  },
  {
    EL_ACIDPOOL_TOPLEFT,			-1, -1,
    IMG_ACIDPOOL_TOPLEFT
  },
  {
    EL_ACIDPOOL_TOPRIGHT,			-1, -1,
    IMG_ACIDPOOL_TOPRIGHT
  },
  {
    EL_ACIDPOOL_BOTTOMLEFT,			-1, -1,
    IMG_ACIDPOOL_BOTTOMLEFT
  },
  {
    EL_ACIDPOOL_BOTTOM,				-1, -1,
    IMG_ACIDPOOL_BOTTOM
  },
  {
    EL_ACIDPOOL_BOTTOMRIGHT,			-1, -1,
    IMG_ACIDPOOL_BOTTOMRIGHT
  },
  {
    EL_ACID,					-1, -1,
    IMG_ACID
  },
  {
    EL_ACID_SPLASH_LEFT,			-1, -1,
    IMG_ACID_SPLASH_LEFT
  },
  {
    EL_ACID_SPLASH_RIGHT,			-1, -1,
    IMG_ACID_SPLASH_RIGHT
  },
  {
    EL_AMOEBA_DROP,				-1, -1,
    IMG_AMOEBA_DROP
  },
  {
    EL_AMOEBA_CREATING,				-1, -1,
    IMG_AMOEBA_CREATING
  },
  {
    EL_AMOEBA_SHRINKING,			-1, -1,
    IMG_AMOEBA_SHRINKING
  },
  {
    EL_AMOEBA_WET,				-1, -1,
    IMG_AMOEBA_WET
  },
  {
    EL_AMOEBA_DRIPPING,				-1, -1,
    IMG_AMOEBA_DRIPPING
  },
  {
    EL_AMOEBA_DRY,				-1, -1,
    IMG_AMOEBA_DRY
  },
  {
    EL_AMOEBA_FULL,				-1, -1,
    IMG_AMOEBA_FULL
  },
  {
    EL_AMOEBA_DEAD,				-1, -1,
    IMG_AMOEBA_DEAD
  },
  {
    EL_EM_KEY1,					-1, -1,
    IMG_EM_KEY1
  },
  {
    EL_EM_KEY2,					-1, -1,
    IMG_EM_KEY2
  },
  {
    EL_EM_KEY3,					-1, -1,
    IMG_EM_KEY3
  },
  {
    EL_EM_KEY4,					-1, -1,
    IMG_EM_KEY4
  },
  {
    EL_EM_GATE1,				-1, -1,
    IMG_EM_GATE1
  },
  {
    EL_EM_GATE2,				-1, -1,
    IMG_EM_GATE2
  },
  {
    EL_EM_GATE3,				-1, -1,
    IMG_EM_GATE3
  },
  {
    EL_EM_GATE4,				-1, -1,
    IMG_EM_GATE4
  },
  {
    EL_EM_GATE1_GRAY,				-1, -1,
    IMG_EM_GATE1_GRAY
  },
  {
    EL_EM_GATE2_GRAY,				-1, -1,
    IMG_EM_GATE2_GRAY
  },
  {
    EL_EM_GATE3_GRAY,				-1, -1,
    IMG_EM_GATE3_GRAY
  },
  {
    EL_EM_GATE4_GRAY,				-1, -1,
    IMG_EM_GATE4_GRAY
  },
  {
    EL_EXIT_CLOSED,				-1, -1,
    IMG_EXIT_CLOSED
  },
  {
    EL_EXIT_OPENING,				-1, -1,
    IMG_EXIT_OPENING
  },
  {
    EL_EXIT_OPEN,				-1, -1,
    IMG_EXIT_OPEN
  },
  {
    EL_BALLOON,					-1, -1,
    IMG_BALLOON
  },
  {
    EL_BALLOON,					ACTION_MOVING, -1,
    IMG_BALLOON_MOVING
  },
  {
    EL_BALLOON_SEND_LEFT,			-1, -1,
    IMG_BALLOON_SEND_LEFT
  },
  {
    EL_BALLOON_SEND_RIGHT,			-1, -1,
    IMG_BALLOON_SEND_RIGHT
  },
  {
    EL_BALLOON_SEND_UP,				-1, -1,
    IMG_BALLOON_SEND_UP
  },
  {
    EL_BALLOON_SEND_DOWN,			-1, -1,
    IMG_BALLOON_SEND_DOWN
  },
  {
    EL_BALLOON_SEND_ANY_DIRECTION,		-1, -1,
    IMG_BALLOON_SEND_ANY_DIRECTION
  },
  {
    EL_SPRING,					-1, -1,
    IMG_SPRING
  },
  {
    EL_SPRING,					ACTION_MOVING, -1,
    IMG_SPRING_MOVING
  },
  {
    EL_EMC_STEELWALL1,				-1, -1,
    IMG_EMC_STEELWALL1
  },
  {
    EL_EMC_STEELWALL2,				-1, -1,
    IMG_EMC_STEELWALL2
  },
  {
    EL_EMC_STEELWALL3,				-1, -1,
    IMG_EMC_STEELWALL3
  },
  {
    EL_EMC_STEELWALL4,				-1, -1,
    IMG_EMC_STEELWALL4
  },
  {
    EL_EMC_WALL_PILLAR_UPPER,			-1, -1,
    IMG_EMC_WALL_PILLAR_UPPER
  },
  {
    EL_EMC_WALL_PILLAR_MIDDLE,			-1, -1,
    IMG_EMC_WALL_PILLAR_MIDDLE
  },
  {
    EL_EMC_WALL_PILLAR_LOWER,			-1, -1,
    IMG_EMC_WALL_PILLAR_LOWER
  },
  {
    EL_EMC_WALL4,				-1, -1,
    IMG_EMC_WALL4
  },
  {
    EL_EMC_WALL5,				-1, -1,
    IMG_EMC_WALL5
  },
  {
    EL_EMC_WALL6,				-1, -1,
    IMG_EMC_WALL6
  },
  {
    EL_EMC_WALL7,				-1, -1,
    IMG_EMC_WALL7
  },
  {
    EL_EMC_WALL8,				-1, -1,
    IMG_EMC_WALL8
  },
  {
    EL_INVISIBLE_STEELWALL,			-1, -1,
    IMG_INVISIBLE_STEELWALL
  },
  {
    EL_INVISIBLE_STEELWALL_ACTIVE,		-1, -1,
    IMG_INVISIBLE_STEELWALL_ACTIVE
  },
  {
    EL_INVISIBLE_STEELWALL,			ACTION_ACTIVE, -1,
    IMG_INVISIBLE_STEELWALL_ACTIVE
  },
  {
    EL_INVISIBLE_WALL,				-1, -1,
    IMG_INVISIBLE_WALL
  },
  {
    EL_INVISIBLE_WALL_ACTIVE,			-1, -1,
    IMG_INVISIBLE_WALL_ACTIVE
  },
  {
    EL_INVISIBLE_WALL,				ACTION_ACTIVE, -1,
    IMG_INVISIBLE_WALL_ACTIVE
  },
  {
    EL_INVISIBLE_SAND,				-1, -1,
    IMG_INVISIBLE_SAND
  },
  {
    EL_INVISIBLE_SAND_ACTIVE,			-1, -1,
    IMG_INVISIBLE_SAND_ACTIVE
  },
  {
    EL_INVISIBLE_SAND,				ACTION_ACTIVE, -1,
    IMG_INVISIBLE_SAND_ACTIVE
  },
  {
    EL_CONVEYOR_BELT1_MIDDLE,			-1, -1,
    IMG_CONVEYOR_BELT1_MIDDLE
  },
  {
    EL_CONVEYOR_BELT1_MIDDLE_ACTIVE,		-1, -1,
    IMG_CONVEYOR_BELT1_MIDDLE_ACTIVE
  },
  {
    EL_CONVEYOR_BELT1_MIDDLE,			ACTION_ACTIVE, -1,
    IMG_CONVEYOR_BELT1_MIDDLE_ACTIVE
  },
  {
    EL_CONVEYOR_BELT1_LEFT,			-1, -1,
    IMG_CONVEYOR_BELT1_LEFT
  },
  {
    EL_CONVEYOR_BELT1_LEFT_ACTIVE,		-1, -1,
    IMG_CONVEYOR_BELT1_LEFT_ACTIVE
  },
  {
    EL_CONVEYOR_BELT1_LEFT,			ACTION_ACTIVE, -1,
    IMG_CONVEYOR_BELT1_LEFT_ACTIVE
  },
  {
    EL_CONVEYOR_BELT1_RIGHT,			-1, -1,
    IMG_CONVEYOR_BELT1_RIGHT
  },
  {
    EL_CONVEYOR_BELT1_RIGHT_ACTIVE,		-1, -1,
    IMG_CONVEYOR_BELT1_RIGHT_ACTIVE
  },
  {
    EL_CONVEYOR_BELT1_RIGHT,			ACTION_ACTIVE, -1,
    IMG_CONVEYOR_BELT1_RIGHT_ACTIVE
  },
  {
    EL_CONVEYOR_BELT1_SWITCH_LEFT,		-1, -1,
    IMG_CONVEYOR_BELT1_SWITCH_LEFT
  },
  {
    EL_CONVEYOR_BELT1_SWITCH_MIDDLE,		-1, -1,
    IMG_CONVEYOR_BELT1_SWITCH_MIDDLE
  },
  {
    EL_CONVEYOR_BELT1_SWITCH_RIGHT,		-1, -1,
    IMG_CONVEYOR_BELT1_SWITCH_RIGHT
  },
  {
    EL_CONVEYOR_BELT2_MIDDLE,			-1, -1,
    IMG_CONVEYOR_BELT2_MIDDLE
  },
  {
    EL_CONVEYOR_BELT2_MIDDLE_ACTIVE,		-1, -1,
    IMG_CONVEYOR_BELT2_MIDDLE_ACTIVE
  },
  {
    EL_CONVEYOR_BELT2_MIDDLE,			ACTION_ACTIVE, -1,
    IMG_CONVEYOR_BELT2_MIDDLE_ACTIVE
  },
  {
    EL_CONVEYOR_BELT2_LEFT,			-1, -1,
    IMG_CONVEYOR_BELT2_LEFT
  },
  {
    EL_CONVEYOR_BELT2_LEFT_ACTIVE,		-1, -1,
    IMG_CONVEYOR_BELT2_LEFT_ACTIVE
  },
  {
    EL_CONVEYOR_BELT2_LEFT,			ACTION_ACTIVE, -1,
    IMG_CONVEYOR_BELT2_LEFT_ACTIVE
  },
  {
    EL_CONVEYOR_BELT2_RIGHT,			-1, -1,
    IMG_CONVEYOR_BELT2_RIGHT
  },
  {
    EL_CONVEYOR_BELT2_RIGHT_ACTIVE,		-1, -1,
    IMG_CONVEYOR_BELT2_RIGHT_ACTIVE
  },
  {
    EL_CONVEYOR_BELT2_RIGHT,			ACTION_ACTIVE, -1,
    IMG_CONVEYOR_BELT2_RIGHT_ACTIVE
  },
  {
    EL_CONVEYOR_BELT2_SWITCH_LEFT,		-1, -1,
    IMG_CONVEYOR_BELT2_SWITCH_LEFT
  },
  {
    EL_CONVEYOR_BELT2_SWITCH_MIDDLE,		-1, -1,
    IMG_CONVEYOR_BELT2_SWITCH_MIDDLE
  },
  {
    EL_CONVEYOR_BELT2_SWITCH_RIGHT,		-1, -1,
    IMG_CONVEYOR_BELT2_SWITCH_RIGHT
  },
  {
    EL_CONVEYOR_BELT3_MIDDLE,			-1, -1,
    IMG_CONVEYOR_BELT3_MIDDLE
  },
  {
    EL_CONVEYOR_BELT3_MIDDLE_ACTIVE,		-1, -1,
    IMG_CONVEYOR_BELT3_MIDDLE_ACTIVE
  },
  {
    EL_CONVEYOR_BELT3_MIDDLE,			ACTION_ACTIVE, -1,
    IMG_CONVEYOR_BELT3_MIDDLE_ACTIVE
  },
  {
    EL_CONVEYOR_BELT3_LEFT,			-1, -1,
    IMG_CONVEYOR_BELT3_LEFT
  },
  {
    EL_CONVEYOR_BELT3_LEFT_ACTIVE,		-1, -1,
    IMG_CONVEYOR_BELT3_LEFT_ACTIVE
  },
  {
    EL_CONVEYOR_BELT3_LEFT,			ACTION_ACTIVE, -1,
    IMG_CONVEYOR_BELT3_LEFT_ACTIVE
  },
  {
    EL_CONVEYOR_BELT3_RIGHT,			-1, -1,
    IMG_CONVEYOR_BELT3_RIGHT
  },
  {
    EL_CONVEYOR_BELT3_RIGHT_ACTIVE,		-1, -1,
    IMG_CONVEYOR_BELT3_RIGHT_ACTIVE
  },
  {
    EL_CONVEYOR_BELT3_RIGHT,			ACTION_ACTIVE, -1,
    IMG_CONVEYOR_BELT3_RIGHT_ACTIVE
  },
  {
    EL_CONVEYOR_BELT3_SWITCH_LEFT,		-1, -1,
    IMG_CONVEYOR_BELT3_SWITCH_LEFT
  },
  {
    EL_CONVEYOR_BELT3_SWITCH_MIDDLE,		-1, -1,
    IMG_CONVEYOR_BELT3_SWITCH_MIDDLE
  },
  {
    EL_CONVEYOR_BELT3_SWITCH_RIGHT,		-1, -1,
    IMG_CONVEYOR_BELT3_SWITCH_RIGHT
  },
  {
    EL_CONVEYOR_BELT4_MIDDLE,			-1, -1,
    IMG_CONVEYOR_BELT4_MIDDLE
  },
  {
    EL_CONVEYOR_BELT4_MIDDLE_ACTIVE,		-1, -1,
    IMG_CONVEYOR_BELT4_MIDDLE_ACTIVE
  },
  {
    EL_CONVEYOR_BELT4_MIDDLE,			ACTION_ACTIVE, -1,
    IMG_CONVEYOR_BELT4_MIDDLE_ACTIVE
  },
  {
    EL_CONVEYOR_BELT4_LEFT,			-1, -1,
    IMG_CONVEYOR_BELT4_LEFT
  },
  {
    EL_CONVEYOR_BELT4_LEFT_ACTIVE,		-1, -1,
    IMG_CONVEYOR_BELT4_LEFT_ACTIVE
  },
  {
    EL_CONVEYOR_BELT4_LEFT,			ACTION_ACTIVE, -1,
    IMG_CONVEYOR_BELT4_LEFT_ACTIVE
  },
  {
    EL_CONVEYOR_BELT4_RIGHT,			-1, -1,
    IMG_CONVEYOR_BELT4_RIGHT
  },
  {
    EL_CONVEYOR_BELT4_RIGHT_ACTIVE,		-1, -1,
    IMG_CONVEYOR_BELT4_RIGHT_ACTIVE
  },
  {
    EL_CONVEYOR_BELT4_RIGHT,			ACTION_ACTIVE, -1,
    IMG_CONVEYOR_BELT4_RIGHT_ACTIVE
  },
  {
    EL_CONVEYOR_BELT4_SWITCH_LEFT,		-1, -1,
    IMG_CONVEYOR_BELT4_SWITCH_LEFT
  },
  {
    EL_CONVEYOR_BELT4_SWITCH_MIDDLE,		-1, -1,
    IMG_CONVEYOR_BELT4_SWITCH_MIDDLE
  },
  {
    EL_CONVEYOR_BELT4_SWITCH_RIGHT,		-1, -1,
    IMG_CONVEYOR_BELT4_SWITCH_RIGHT
  },
  {
    EL_SWITCHGATE_SWITCH_UP,			-1, -1,
    IMG_SWITCHGATE_SWITCH_UP
  },
  {
    EL_SWITCHGATE_SWITCH_DOWN,			-1, -1,
    IMG_SWITCHGATE_SWITCH_DOWN
  },
  {
    EL_LIGHT_SWITCH,				-1, -1,
    IMG_LIGHT_SWITCH
  },
  {
    EL_LIGHT_SWITCH_ACTIVE,			-1, -1,
    IMG_LIGHT_SWITCH_ACTIVE
  },
  {
    EL_LIGHT_SWITCH,				ACTION_ACTIVE, -1,
    IMG_LIGHT_SWITCH_ACTIVE
  },
  {
    EL_TIMEGATE_SWITCH,				-1, -1,
    IMG_TIMEGATE_SWITCH
  },
  {
    EL_TIMEGATE_SWITCH_ACTIVE,			-1, -1,
    IMG_TIMEGATE_SWITCH_ACTIVE
  },
  {
    EL_TIMEGATE_SWITCH,				ACTION_ACTIVE, -1,
    IMG_TIMEGATE_SWITCH_ACTIVE
  },
  {
    EL_ENVELOPE,				-1, -1,
    IMG_ENVELOPE
  },
  {
    EL_SIGN_EXCLAMATION,			-1, -1,
    IMG_SIGN_EXCLAMATION
  },
  {
    EL_SIGN_STOP,				-1, -1,
    IMG_SIGN_STOP
  },
  {
    EL_LANDMINE,				-1, -1,
    IMG_LANDMINE
  },
  {
    EL_STEELWALL_SLANTED,			-1, -1,
    IMG_STEELWALL_SLANTED
  },
  {
    EL_EXTRA_TIME,				-1, -1,
    IMG_EXTRA_TIME
  },
  {
    EL_SHIELD_NORMAL,				-1, -1,
    IMG_SHIELD_NORMAL
  },
  {
    EL_SHIELD_NORMAL_ACTIVE,			-1, -1,
    IMG_SHIELD_NORMAL_ACTIVE
  },
  {
    EL_SHIELD_NORMAL,				ACTION_ACTIVE, -1,
    IMG_SHIELD_NORMAL_ACTIVE
  },
  {
    EL_SHIELD_DEADLY,				-1, -1,
    IMG_SHIELD_DEADLY
  },
  {
    EL_SHIELD_DEADLY_ACTIVE,			-1, -1,
    IMG_SHIELD_DEADLY_ACTIVE
  },
  {
    EL_SHIELD_DEADLY,				ACTION_ACTIVE, -1,
    IMG_SHIELD_DEADLY_ACTIVE
  },
  {
    EL_SWITCHGATE_CLOSED,			-1, -1,
    IMG_SWITCHGATE_CLOSED
  },
  {
    EL_SWITCHGATE_OPENING,			-1, -1,
    IMG_SWITCHGATE_OPENING
  },
  {
    EL_SWITCHGATE_OPEN,				-1, -1,
    IMG_SWITCHGATE_OPEN
  },
  {
    EL_SWITCHGATE_CLOSING,			-1, -1,
    IMG_SWITCHGATE_CLOSING
  },
  {
    EL_TIMEGATE_CLOSED,				-1, -1,
    IMG_TIMEGATE_CLOSED
  },
  {
    EL_TIMEGATE_OPENING,			-1, -1,
    IMG_TIMEGATE_OPENING
  },
  {
    EL_TIMEGATE_OPEN,				-1, -1,
    IMG_TIMEGATE_OPEN
  },
  {
    EL_TIMEGATE_CLOSING,			-1, -1,
    IMG_TIMEGATE_CLOSING
  },
  {
    EL_PEARL,					-1, -1,
    IMG_PEARL
  },
  {
    EL_PEARL_BREAKING,				-1, -1,
    IMG_PEARL_BREAKING
  },
  {
    EL_PEARL,					ACTION_BREAKING, -1,
    IMG_PEARL_BREAKING
  },
  {
    EL_CRYSTAL,					-1, -1,
    IMG_CRYSTAL
  },
  {
    EL_WALL_PEARL,				-1, -1,
    IMG_WALL_PEARL
  },
  {
    EL_WALL_CRYSTAL,				-1, -1,
    IMG_WALL_CRYSTAL
  },
  {
    EL_TUBE_RIGHT_DOWN,				-1, -1,
    IMG_TUBE_RIGHT_DOWN
  },
  {
    EL_TUBE_HORIZONTAL_DOWN,			-1, -1,
    IMG_TUBE_HORIZONTAL_DOWN
  },
  {
    EL_TUBE_LEFT_DOWN,				-1, -1,
    IMG_TUBE_LEFT_DOWN
  },
  {
    EL_TUBE_HORIZONTAL,				-1, -1,
    IMG_TUBE_HORIZONTAL
  },
  {
    EL_TUBE_VERTICAL_RIGHT,			-1, -1,
    IMG_TUBE_VERTICAL_RIGHT
  },
  {
    EL_TUBE_ALL,				-1, -1,
    IMG_TUBE_ALL
  },
  {
    EL_TUBE_VERTICAL_LEFT,			-1, -1,
    IMG_TUBE_VERTICAL_LEFT
  },
  {
    EL_TUBE_VERTICAL,				-1, -1,
    IMG_TUBE_VERTICAL
  },
  {
    EL_TUBE_RIGHT_UP,				-1, -1,
    IMG_TUBE_RIGHT_UP
  },
  {
    EL_TUBE_HORIZONTAL_UP,			-1, -1,
    IMG_TUBE_HORIZONTAL_UP
  },
  {
    EL_TUBE_LEFT_UP,				-1, -1,
    IMG_TUBE_LEFT_UP
  },
  {
    EL_TRAP,					-1, -1,
    IMG_TRAP
  },
  {
    EL_TRAP_ACTIVE,				-1, -1,
    IMG_TRAP_ACTIVE
  },
  {
    EL_TRAP,					ACTION_ACTIVE, -1,
    IMG_TRAP_ACTIVE
  },
  {
    EL_DX_SUPABOMB,				-1, -1,
    IMG_DX_SUPABOMB
  },
  {
    EL_KEY1,					-1, -1,
    IMG_KEY1
  },
  {
    EL_KEY2,					-1, -1,
    IMG_KEY2
  },
  {
    EL_KEY3,					-1, -1,
    IMG_KEY3
  },
  {
    EL_KEY4,					-1, -1,
    IMG_KEY4
  },
  {
    EL_GATE1,					-1, -1,
    IMG_GATE1
  },
  {
    EL_GATE2,					-1, -1,
    IMG_GATE2
  },
  {
    EL_GATE3,					-1, -1,
    IMG_GATE3
  },
  {
    EL_GATE4,					-1, -1,
    IMG_GATE4
  },
  {
    EL_GATE1_GRAY,				-1, -1,
    IMG_GATE1_GRAY
  },
  {
    EL_GATE2_GRAY,				-1, -1,
    IMG_GATE2_GRAY
  },
  {
    EL_GATE3_GRAY,				-1, -1,
    IMG_GATE3_GRAY
  },
  {
    EL_GATE4_GRAY,				-1, -1,
    IMG_GATE4_GRAY
  },
  {
    EL_GAMEOFLIFE,				-1, -1,
    IMG_GAMEOFLIFE
  },
  {
    EL_BIOMAZE,					-1, -1,
    IMG_BIOMAZE
  },
  {
    EL_PACMAN_RIGHT,				-1, -1,
    IMG_PACMAN_RIGHT
  },
  {
    EL_PACMAN,					-1, MV_BIT_RIGHT,
    IMG_PACMAN_RIGHT
  },
  {
    EL_PACMAN_UP,				-1, -1,
    IMG_PACMAN_UP
  },
  {
    EL_PACMAN,					-1, MV_BIT_UP,
    IMG_PACMAN_UP
  },
  {
    EL_PACMAN_LEFT,				-1, -1,
    IMG_PACMAN_LEFT
  },
  {
    EL_PACMAN,					-1, MV_BIT_LEFT,
    IMG_PACMAN_LEFT
  },
  {
    EL_PACMAN_DOWN,				-1, -1,
    IMG_PACMAN_DOWN
  },
  {
    EL_PACMAN,					-1, MV_BIT_DOWN,
    IMG_PACMAN_DOWN
  },
  {
    EL_LAMP,					-1, -1,
    IMG_LAMP
  },
  {
    EL_LAMP_ACTIVE,				-1, -1,
    IMG_LAMP_ACTIVE
  },
  {
    EL_LAMP,					ACTION_ACTIVE, -1,
    IMG_LAMP_ACTIVE
  },
  {
    EL_TIME_ORB_FULL,				-1, -1,
    IMG_TIME_ORB_FULL
  },
  {
    EL_TIME_ORB_EMPTY,				-1, -1,
    IMG_TIME_ORB_EMPTY
  },
  {
    EL_EMERALD_YELLOW,				-1, -1,
    IMG_EMERALD_YELLOW
  },
  {
    EL_EMERALD_YELLOW,				ACTION_MOVING, -1,
    IMG_EMERALD_YELLOW_MOVING
  },
  {
    EL_EMERALD_YELLOW,				ACTION_FALLING, -1,
    IMG_EMERALD_YELLOW_FALLING
  },
  {
    EL_EMERALD_RED,				-1, -1,
    IMG_EMERALD_RED
  },
  {
    EL_EMERALD_RED,				ACTION_MOVING, -1,
    IMG_EMERALD_RED_MOVING
  },
  {
    EL_EMERALD_RED,				ACTION_FALLING, -1,
    IMG_EMERALD_RED_FALLING
  },
  {
    EL_EMERALD_PURPLE,				-1, -1,
    IMG_EMERALD_PURPLE
  },
  {
    EL_EMERALD_PURPLE,				ACTION_MOVING, -1,
    IMG_EMERALD_PURPLE_MOVING
  },
  {
    EL_EMERALD_PURPLE,				ACTION_FALLING, -1,
    IMG_EMERALD_PURPLE_FALLING
  },
  {
    EL_WALL_EMERALD_YELLOW,			-1, -1,
    IMG_WALL_EMERALD_YELLOW
  },
  {
    EL_WALL_EMERALD_RED,			-1, -1,
    IMG_WALL_EMERALD_RED
  },
  {
    EL_WALL_EMERALD_PURPLE,			-1, -1,
    IMG_WALL_EMERALD_PURPLE
  },
  {
    EL_WALL_BD_DIAMOND,				-1, -1,
    IMG_WALL_BD_DIAMOND
  },
  {
    EL_WALL_GROWING,				-1, -1,
    IMG_WALL_GROWING
  },
  {
    EL_WALL_GROWING_XY,				-1, -1,
    IMG_WALL_GROWING_XY
  },
  {
    EL_WALL_GROWING_X,				-1, -1,
    IMG_WALL_GROWING_X
  },
  {
    EL_WALL_GROWING_Y,				-1, -1,
    IMG_WALL_GROWING_Y
  },
  {
    EL_WALL_GROWING,				ACTION_ACTIVE, MV_BIT_LEFT,
    IMG_WALL_GROWING_ACTIVE_LEFT
  },
  {
    EL_WALL_GROWING_ACTIVE,			-1, MV_BIT_LEFT,
    IMG_WALL_GROWING_ACTIVE_LEFT
  },
  {
    EL_WALL_GROWING,				ACTION_ACTIVE, MV_BIT_RIGHT,
    IMG_WALL_GROWING_ACTIVE_RIGHT
  },
  {
    EL_WALL_GROWING_ACTIVE,			-1, MV_BIT_RIGHT,
    IMG_WALL_GROWING_ACTIVE_RIGHT
  },
  {
    EL_WALL_GROWING,				ACTION_ACTIVE, MV_BIT_UP,
    IMG_WALL_GROWING_ACTIVE_UP
  },
  {
    EL_WALL_GROWING_ACTIVE,			-1, MV_BIT_UP,
    IMG_WALL_GROWING_ACTIVE_UP
  },
  {
    EL_WALL_GROWING,				ACTION_ACTIVE, MV_BIT_DOWN,
    IMG_WALL_GROWING_ACTIVE_DOWN
  },
  {
    EL_WALL_GROWING_ACTIVE,			-1, MV_BIT_DOWN,
    IMG_WALL_GROWING_ACTIVE_DOWN
  },
  {
    EL_BLACK_ORB,				-1, -1,
    IMG_BLACK_ORB
  },
  {
    EL_SPEED_PILL,				-1, -1,
    IMG_SPEED_PILL
  },
  {
    EL_DARK_YAMYAM,				-1, -1,
    IMG_DARK_YAMYAM
  },
  {
    EL_DYNABOMB_ACTIVE,				-1, -1,
    IMG_DYNABOMB_ACTIVE
  },
  {
    EL_DYNABOMB_PLAYER1_ACTIVE,			-1, -1,
    IMG_DYNABOMB_PLAYER1_ACTIVE
  },
  {
    EL_DYNABOMB_PLAYER2_ACTIVE,			-1, -1,
    IMG_DYNABOMB_PLAYER2_ACTIVE
  },
  {
    EL_DYNABOMB_PLAYER3_ACTIVE,			-1, -1,
    IMG_DYNABOMB_PLAYER3_ACTIVE
  },
  {
    EL_DYNABOMB_PLAYER4_ACTIVE,			-1, -1,
    IMG_DYNABOMB_PLAYER4_ACTIVE
  },
  {
    EL_DYNABOMB_NR,				-1, -1,
    IMG_DYNABOMB_NR
  },
  {
    EL_DYNABOMB_SZ,				-1, -1,
    IMG_DYNABOMB_SZ
  },
  {
    EL_DYNABOMB_XL,				-1, -1,
    IMG_DYNABOMB_XL
  },
  {
    EL_PIG,					-1, -1,
    IMG_PIG
  },
  {
    EL_PIG,					-1, MV_BIT_DOWN,
    IMG_PIG_DOWN
  },
  {
    EL_PIG,					-1, MV_BIT_UP,
    IMG_PIG_UP
  },
  {
    EL_PIG,					-1, MV_BIT_LEFT,
    IMG_PIG_LEFT
  },
  {
    EL_PIG,					-1, MV_BIT_RIGHT,
    IMG_PIG_RIGHT
  },
  {
    EL_PIG,					ACTION_MOVING, MV_BIT_DOWN,
    IMG_PIG_MOVING_DOWN
  },
  {
    EL_PIG,					ACTION_MOVING, MV_BIT_UP,
    IMG_PIG_MOVING_UP
  },
  {
    EL_PIG,					ACTION_MOVING, MV_BIT_LEFT,
    IMG_PIG_MOVING_LEFT
  },
  {
    EL_PIG,					ACTION_MOVING, MV_BIT_RIGHT,
    IMG_PIG_MOVING_RIGHT
  },
  {
    EL_PIG,					ACTION_EATING, MV_BIT_DOWN,
    IMG_PIG_EATING_DOWN
  },
  {
    EL_PIG,					ACTION_EATING, MV_BIT_UP,
    IMG_PIG_EATING_UP
  },
  {
    EL_PIG,					ACTION_EATING, MV_BIT_LEFT,
    IMG_PIG_EATING_LEFT
  },
  {
    EL_PIG,					ACTION_EATING, MV_BIT_RIGHT,
    IMG_PIG_EATING_RIGHT
  },
  {
    EL_DRAGON,					-1, -1,
    IMG_DRAGON
  },
  {
    EL_DRAGON,					-1, MV_BIT_DOWN,
    IMG_DRAGON_DOWN
  },
  {
    EL_DRAGON,					-1, MV_BIT_UP,
    IMG_DRAGON_UP
  },
  {
    EL_DRAGON,					-1, MV_BIT_LEFT,
    IMG_DRAGON_LEFT
  },
  {
    EL_DRAGON,					-1, MV_BIT_RIGHT,
    IMG_DRAGON_RIGHT
  },
  {
    EL_DRAGON,					ACTION_MOVING, MV_BIT_DOWN,
    IMG_DRAGON_MOVING_DOWN
  },
  {
    EL_DRAGON,					ACTION_MOVING, MV_BIT_UP,
    IMG_DRAGON_MOVING_UP
  },
  {
    EL_DRAGON,					ACTION_MOVING, MV_BIT_LEFT,
    IMG_DRAGON_MOVING_LEFT
  },
  {
    EL_DRAGON,					ACTION_MOVING, MV_BIT_RIGHT,
    IMG_DRAGON_MOVING_RIGHT
  },
  {
    EL_DRAGON,					ACTION_ATTACKING, MV_BIT_DOWN,
    IMG_DRAGON_ATTACKING_DOWN
  },
  {
    EL_DRAGON,					ACTION_ATTACKING, MV_BIT_UP,
    IMG_DRAGON_ATTACKING_UP
  },
  {
    EL_DRAGON,					ACTION_ATTACKING, MV_BIT_LEFT,
    IMG_DRAGON_ATTACKING_LEFT
  },
  {
    EL_DRAGON,					ACTION_ATTACKING, MV_BIT_RIGHT,
    IMG_DRAGON_ATTACKING_RIGHT
  },
  {
    EL_MOLE,					-1, -1,
    IMG_MOLE
  },
  {
    EL_MOLE_DOWN,				-1, -1,
    IMG_MOLE_DOWN
  },
  {
    EL_MOLE,					-1, MV_BIT_DOWN,
    IMG_MOLE_DOWN
  },
  {
    EL_MOLE_UP,					-1, -1,
    IMG_MOLE_UP
  },
  {
    EL_MOLE,					-1, MV_BIT_UP,
    IMG_MOLE_UP
  },
  {
    EL_MOLE_LEFT,				-1, -1,
    IMG_MOLE_LEFT
  },
  {
    EL_MOLE,					-1, MV_BIT_LEFT,
    IMG_MOLE_LEFT
  },
  {
    EL_MOLE_RIGHT,				-1, -1,
    IMG_MOLE_RIGHT
  },
  {
    EL_MOLE,					-1, MV_BIT_RIGHT,
    IMG_MOLE_RIGHT
  },
  {
    EL_MOLE,					ACTION_MOVING, MV_BIT_DOWN,
    IMG_MOLE_MOVING_DOWN
  },
  {
    EL_MOLE,					ACTION_MOVING, MV_BIT_UP,
    IMG_MOLE_MOVING_UP
  },
  {
    EL_MOLE,					ACTION_MOVING, MV_BIT_LEFT,
    IMG_MOLE_MOVING_LEFT
  },
  {
    EL_MOLE,					ACTION_MOVING, MV_BIT_RIGHT,
    IMG_MOLE_MOVING_RIGHT
  },
  {
    EL_MOLE,					ACTION_DIGGING, MV_BIT_DOWN,
    IMG_MOLE_DIGGING_DOWN
  },
  {
    EL_MOLE,					ACTION_DIGGING, MV_BIT_UP,
    IMG_MOLE_DIGGING_UP
  },
  {
    EL_MOLE,					ACTION_DIGGING, MV_BIT_LEFT,
    IMG_MOLE_DIGGING_LEFT
  },
  {
    EL_MOLE,					ACTION_DIGGING, MV_BIT_RIGHT,
    IMG_MOLE_DIGGING_RIGHT
  },
  {
    EL_PENGUIN,					-1, -1,
    IMG_PENGUIN
  },
  {
    EL_PENGUIN,					-1, MV_BIT_DOWN,
    IMG_PENGUIN_DOWN
  },
  {
    EL_PENGUIN,					-1, MV_BIT_UP,
    IMG_PENGUIN_UP
  },
  {
    EL_PENGUIN,					-1, MV_BIT_LEFT,
    IMG_PENGUIN_LEFT
  },
  {
    EL_PENGUIN,					-1, MV_BIT_RIGHT,
    IMG_PENGUIN_RIGHT
  },
  {
    EL_PENGUIN,					ACTION_MOVING, MV_BIT_DOWN,
    IMG_PENGUIN_MOVING_DOWN
  },
  {
    EL_PENGUIN,					ACTION_MOVING, MV_BIT_UP,
    IMG_PENGUIN_MOVING_UP
  },
  {
    EL_PENGUIN,					ACTION_MOVING, MV_BIT_LEFT,
    IMG_PENGUIN_MOVING_LEFT
  },
  {
    EL_PENGUIN,					ACTION_MOVING, MV_BIT_RIGHT,
    IMG_PENGUIN_MOVING_RIGHT
  },
  {
    EL_SATELLITE,				-1, -1,
    IMG_SATELLITE
  },
  {
    EL_SATELLITE,				ACTION_MOVING, -1,
    IMG_SATELLITE_MOVING
  },
  {
    EL_STONEBLOCK,				-1, -1,
    IMG_STONEBLOCK
  },
  {
    EL_PLAYER1,					-1, -1,
    IMG_PLAYER1
  },
  {
    EL_PLAYER1,					-1, MV_BIT_DOWN,
    IMG_PLAYER1_DOWN
  },
  {
    EL_PLAYER1,					-1, MV_BIT_UP,
    IMG_PLAYER1_UP
  },
  {
    EL_PLAYER1,					-1, MV_BIT_LEFT,
    IMG_PLAYER1_LEFT
  },
  {
    EL_PLAYER1,					-1, MV_BIT_RIGHT,
    IMG_PLAYER1_RIGHT
  },
  {
    EL_PLAYER1,					ACTION_MOVING, MV_BIT_DOWN,
    IMG_PLAYER1_MOVING_DOWN
  },
  {
    EL_PLAYER1,					ACTION_MOVING, MV_BIT_UP,
    IMG_PLAYER1_MOVING_UP
  },
  {
    EL_PLAYER1,					ACTION_MOVING, MV_BIT_LEFT,
    IMG_PLAYER1_MOVING_LEFT
  },
  {
    EL_PLAYER1,					ACTION_MOVING, MV_BIT_RIGHT,
    IMG_PLAYER1_MOVING_RIGHT
  },
  {
    EL_PLAYER1,					ACTION_DIGGING, MV_BIT_DOWN,
    IMG_PLAYER1_DIGGING_DOWN
  },
  {
    EL_PLAYER1,					ACTION_DIGGING, MV_BIT_UP,
    IMG_PLAYER1_DIGGING_UP
  },
  {
    EL_PLAYER1,					ACTION_DIGGING, MV_BIT_LEFT,
    IMG_PLAYER1_DIGGING_LEFT
  },
  {
    EL_PLAYER1,					ACTION_DIGGING, MV_BIT_RIGHT,
    IMG_PLAYER1_DIGGING_RIGHT
  },
  {
    EL_PLAYER1,					ACTION_PUSHING, MV_BIT_DOWN,
    IMG_PLAYER1_PUSHING_DOWN
  },
  {
    EL_PLAYER1,					ACTION_PUSHING, MV_BIT_UP,
    IMG_PLAYER1_PUSHING_UP
  },
  {
    EL_PLAYER1,					ACTION_PUSHING, MV_BIT_LEFT,
    IMG_PLAYER1_PUSHING_LEFT
  },
  {
    EL_PLAYER1,					ACTION_PUSHING, MV_BIT_RIGHT,
    IMG_PLAYER1_PUSHING_RIGHT
  },
  {
    EL_PLAYER1,					ACTION_SNAPPING, MV_BIT_DOWN,
    IMG_PLAYER1_SNAPPING_DOWN
  },
  {
    EL_PLAYER1,					ACTION_SNAPPING, MV_BIT_UP,
    IMG_PLAYER1_SNAPPING_UP
  },
  {
    EL_PLAYER1,					ACTION_SNAPPING, MV_BIT_LEFT,
    IMG_PLAYER1_SNAPPING_LEFT
  },
  {
    EL_PLAYER1,					ACTION_SNAPPING, MV_BIT_RIGHT,
    IMG_PLAYER1_SNAPPING_RIGHT
  },
  {
    EL_PLAYER2,					-1, -1,
    IMG_PLAYER2
  },
  {
    EL_PLAYER2,					-1, MV_BIT_DOWN,
    IMG_PLAYER2_DOWN
  },
  {
    EL_PLAYER2,					-1, MV_BIT_UP,
    IMG_PLAYER2_UP
  },
  {
    EL_PLAYER2,					-1, MV_BIT_LEFT,
    IMG_PLAYER2_LEFT
  },
  {
    EL_PLAYER2,					-1, MV_BIT_RIGHT,
    IMG_PLAYER2_RIGHT
  },
  {
    EL_PLAYER2,					ACTION_MOVING, MV_BIT_DOWN,
    IMG_PLAYER2_MOVING_DOWN
  },
  {
    EL_PLAYER2,					ACTION_MOVING, MV_BIT_UP,
    IMG_PLAYER2_MOVING_UP
  },
  {
    EL_PLAYER2,					ACTION_MOVING, MV_BIT_LEFT,
    IMG_PLAYER2_MOVING_LEFT
  },
  {
    EL_PLAYER2,					ACTION_MOVING, MV_BIT_RIGHT,
    IMG_PLAYER2_MOVING_RIGHT
  },
  {
    EL_PLAYER2,					ACTION_DIGGING, MV_BIT_DOWN,
    IMG_PLAYER2_DIGGING_DOWN
  },
  {
    EL_PLAYER2,					ACTION_DIGGING, MV_BIT_UP,
    IMG_PLAYER2_DIGGING_UP
  },
  {
    EL_PLAYER2,					ACTION_DIGGING, MV_BIT_LEFT,
    IMG_PLAYER2_DIGGING_LEFT
  },
  {
    EL_PLAYER2,					ACTION_DIGGING, MV_BIT_RIGHT,
    IMG_PLAYER2_DIGGING_RIGHT
  },
  {
    EL_PLAYER2,					ACTION_PUSHING, MV_BIT_DOWN,
    IMG_PLAYER2_PUSHING_DOWN
  },
  {
    EL_PLAYER2,					ACTION_PUSHING, MV_BIT_UP,
    IMG_PLAYER2_PUSHING_UP
  },
  {
    EL_PLAYER2,					ACTION_PUSHING, MV_BIT_LEFT,
    IMG_PLAYER2_PUSHING_LEFT
  },
  {
    EL_PLAYER2,					ACTION_PUSHING, MV_BIT_RIGHT,
    IMG_PLAYER2_PUSHING_RIGHT
  },
  {
    EL_PLAYER2,					ACTION_SNAPPING, MV_BIT_DOWN,
    IMG_PLAYER2_SNAPPING_DOWN
  },
  {
    EL_PLAYER2,					ACTION_SNAPPING, MV_BIT_UP,
    IMG_PLAYER2_SNAPPING_UP
  },
  {
    EL_PLAYER2,					ACTION_SNAPPING, MV_BIT_LEFT,
    IMG_PLAYER2_SNAPPING_LEFT
  },
  {
    EL_PLAYER2,					ACTION_SNAPPING, MV_BIT_RIGHT,
    IMG_PLAYER2_SNAPPING_RIGHT
  },
  {
    EL_PLAYER3,					-1, -1,
    IMG_PLAYER3
  },
  {
    EL_PLAYER3,					-1, MV_BIT_DOWN,
    IMG_PLAYER3_DOWN
  },
  {
    EL_PLAYER3,					-1, MV_BIT_UP,
    IMG_PLAYER3_UP
  },
  {
    EL_PLAYER3,					-1, MV_BIT_LEFT,
    IMG_PLAYER3_LEFT
  },
  {
    EL_PLAYER3,					-1, MV_BIT_RIGHT,
    IMG_PLAYER3_RIGHT
  },
  {
    EL_PLAYER3,					ACTION_MOVING, MV_BIT_DOWN,
    IMG_PLAYER3_MOVING_DOWN
  },
  {
    EL_PLAYER3,					ACTION_MOVING, MV_BIT_UP,
    IMG_PLAYER3_MOVING_UP
  },
  {
    EL_PLAYER3,					ACTION_MOVING, MV_BIT_LEFT,
    IMG_PLAYER3_MOVING_LEFT
  },
  {
    EL_PLAYER3,					ACTION_MOVING, MV_BIT_RIGHT,
    IMG_PLAYER3_MOVING_RIGHT
  },
  {
    EL_PLAYER3,					ACTION_DIGGING, MV_BIT_DOWN,
    IMG_PLAYER3_DIGGING_DOWN
  },
  {
    EL_PLAYER3,					ACTION_DIGGING, MV_BIT_UP,
    IMG_PLAYER3_DIGGING_UP
  },
  {
    EL_PLAYER3,					ACTION_DIGGING, MV_BIT_LEFT,
    IMG_PLAYER3_DIGGING_LEFT
  },
  {
    EL_PLAYER3,					ACTION_DIGGING, MV_BIT_RIGHT,
    IMG_PLAYER3_DIGGING_RIGHT
  },
  {
    EL_PLAYER3,					ACTION_PUSHING, MV_BIT_DOWN,
    IMG_PLAYER3_PUSHING_DOWN
  },
  {
    EL_PLAYER3,					ACTION_PUSHING, MV_BIT_UP,
    IMG_PLAYER3_PUSHING_UP
  },
  {
    EL_PLAYER3,					ACTION_PUSHING, MV_BIT_LEFT,
    IMG_PLAYER3_PUSHING_LEFT
  },
  {
    EL_PLAYER3,					ACTION_PUSHING, MV_BIT_RIGHT,
    IMG_PLAYER3_PUSHING_RIGHT
  },
  {
    EL_PLAYER3,					ACTION_SNAPPING, MV_BIT_DOWN,
    IMG_PLAYER3_SNAPPING_DOWN
  },
  {
    EL_PLAYER3,					ACTION_SNAPPING, MV_BIT_UP,
    IMG_PLAYER3_SNAPPING_UP
  },
  {
    EL_PLAYER3,					ACTION_SNAPPING, MV_BIT_LEFT,
    IMG_PLAYER3_SNAPPING_LEFT
  },
  {
    EL_PLAYER3,					ACTION_SNAPPING, MV_BIT_RIGHT,
    IMG_PLAYER3_SNAPPING_RIGHT
  },
  {
    EL_PLAYER4,					-1, -1,
    IMG_PLAYER4
  },
  {
    EL_PLAYER4,					-1, MV_BIT_DOWN,
    IMG_PLAYER4_DOWN
  },
  {
    EL_PLAYER4,					-1, MV_BIT_UP,
    IMG_PLAYER4_UP
  },
  {
    EL_PLAYER4,					-1, MV_BIT_LEFT,
    IMG_PLAYER4_LEFT
  },
  {
    EL_PLAYER4,					-1, MV_BIT_RIGHT,
    IMG_PLAYER4_RIGHT
  },
  {
    EL_PLAYER4,					ACTION_MOVING, MV_BIT_DOWN,
    IMG_PLAYER4_MOVING_DOWN
  },
  {
    EL_PLAYER4,					ACTION_MOVING, MV_BIT_UP,
    IMG_PLAYER4_MOVING_UP
  },
  {
    EL_PLAYER4,					ACTION_MOVING, MV_BIT_LEFT,
    IMG_PLAYER4_MOVING_LEFT
  },
  {
    EL_PLAYER4,					ACTION_MOVING, MV_BIT_RIGHT,
    IMG_PLAYER4_MOVING_RIGHT
  },
  {
    EL_PLAYER4,					ACTION_DIGGING, MV_BIT_DOWN,
    IMG_PLAYER4_DIGGING_DOWN
  },
  {
    EL_PLAYER4,					ACTION_DIGGING, MV_BIT_UP,
    IMG_PLAYER4_DIGGING_UP
  },
  {
    EL_PLAYER4,					ACTION_DIGGING, MV_BIT_LEFT,
    IMG_PLAYER4_DIGGING_LEFT
  },
  {
    EL_PLAYER4,					ACTION_DIGGING, MV_BIT_RIGHT,
    IMG_PLAYER4_DIGGING_RIGHT
  },
  {
    EL_PLAYER4,					ACTION_PUSHING, MV_BIT_DOWN,
    IMG_PLAYER4_PUSHING_DOWN
  },
  {
    EL_PLAYER4,					ACTION_PUSHING, MV_BIT_UP,
    IMG_PLAYER4_PUSHING_UP
  },
  {
    EL_PLAYER4,					ACTION_PUSHING, MV_BIT_LEFT,
    IMG_PLAYER4_PUSHING_LEFT
  },
  {
    EL_PLAYER4,					ACTION_PUSHING, MV_BIT_RIGHT,
    IMG_PLAYER4_PUSHING_RIGHT
  },
  {
    EL_PLAYER4,					ACTION_SNAPPING, MV_BIT_DOWN,
    IMG_PLAYER4_SNAPPING_DOWN
  },
  {
    EL_PLAYER4,					ACTION_SNAPPING, MV_BIT_UP,
    IMG_PLAYER4_SNAPPING_UP
  },
  {
    EL_PLAYER4,					ACTION_SNAPPING, MV_BIT_LEFT,
    IMG_PLAYER4_SNAPPING_LEFT
  },
  {
    EL_PLAYER4,					ACTION_SNAPPING, MV_BIT_RIGHT,
    IMG_PLAYER4_SNAPPING_RIGHT
  },
  {
    EL_EXPLOSION,				-1, -1,
    IMG_EXPLOSION
  },
  {
    EL_STEELWALL_TOPLEFT,			-1, -1,
    IMG_STEELWALL_TOPLEFT
  },
  {
    EL_STEELWALL_TOPRIGHT,			-1, -1,
    IMG_STEELWALL_TOPRIGHT
  },
  {
    EL_STEELWALL_BOTTOMLEFT,			-1, -1,
    IMG_STEELWALL_BOTTOMLEFT
  },
  {
    EL_STEELWALL_BOTTOMRIGHT,			-1, -1,
    IMG_STEELWALL_BOTTOMRIGHT
  },
  {
    EL_STEELWALL_HORIZONTAL,			-1, -1,
    IMG_STEELWALL_HORIZONTAL
  },
  {
    EL_STEELWALL_VERTICAL,			-1, -1,
    IMG_STEELWALL_VERTICAL
  },
  {
    EL_INVISIBLE_STEELWALL_TOPLEFT,		-1, -1,
    IMG_INVISIBLE_STEELWALL_TOPLEFT
  },
  {
    EL_INVISIBLE_STEELWALL_TOPRIGHT,		-1, -1,
    IMG_INVISIBLE_STEELWALL_TOPRIGHT
  },
  {
    EL_INVISIBLE_STEELWALL_BOTTOMLEFT,		-1, -1,
    IMG_INVISIBLE_STEELWALL_BOTTOMLEFT
  },
  {
    EL_INVISIBLE_STEELWALL_BOTTOMRIGHT,		-1, -1,
    IMG_INVISIBLE_STEELWALL_BOTTOMRIGHT
  },
  {
    EL_INVISIBLE_STEELWALL_HORIZONTAL,		-1, -1,
    IMG_INVISIBLE_STEELWALL_HORIZONTAL
  },
  {
    EL_INVISIBLE_STEELWALL_VERTICAL,		-1, -1,
    IMG_INVISIBLE_STEELWALL_VERTICAL
  },
  {
    EL_ARROW_BLUE_LEFT,				-1, -1,
    IMG_ARROW_BLUE_LEFT
  },
  {
    EL_ARROW_BLUE_RIGHT,			-1, -1,
    IMG_ARROW_BLUE_RIGHT
  },
  {
    EL_ARROW_BLUE_UP,				-1, -1,
    IMG_ARROW_BLUE_UP
  },
  {
    EL_ARROW_BLUE_DOWN,				-1, -1,
    IMG_ARROW_BLUE_DOWN
  },
  {
    EL_ARROW_RED_LEFT,				-1, -1,
    IMG_ARROW_RED_LEFT
  },
  {
    EL_ARROW_RED_RIGHT,				-1, -1,
    IMG_ARROW_RED_RIGHT
  },
  {
    EL_ARROW_RED_UP,				-1, -1,
    IMG_ARROW_RED_UP
  },
  {
    EL_ARROW_RED_DOWN,				-1, -1,
    IMG_ARROW_RED_DOWN
  },
  {
    EL_BUG,					-1, -1,
    IMG_BUG_RIGHT
  },
  {
    EL_DOOR_WHITE,				-1, -1,
    IMG_CHAR_QUESTION
  },
  {
    EL_DOOR_WHITE_GRAY,				-1, -1,
    IMG_CHAR_QUESTION
  },
  {
    EL_DX_UNKNOWN_15,				-1, -1,
    IMG_CHAR_QUESTION
  },
  {
    EL_DX_UNKNOWN_42,				-1, -1,
    IMG_CHAR_QUESTION
  },
  {
    EL_EM_KEY1_FILE,				-1, -1,
    IMG_EM_KEY1
  },
  {
    EL_EM_KEY2_FILE,				-1, -1,
    IMG_EM_KEY2
  },
  {
    EL_EM_KEY3_FILE,				-1, -1,
    IMG_EM_KEY3
  },
  {
    EL_EM_KEY4_FILE,				-1, -1,
    IMG_EM_KEY4
  },
  {
    EL_KEY_WHITE,				-1, -1,
    IMG_CHAR_QUESTION
  },
  {
    EL_PACMAN,					-1, -1,
    IMG_PACMAN_RIGHT
  },
  {
    EL_SIGN_EXIT,				-1, -1,
    IMG_CHAR_QUESTION
  },
  {
    EL_SIGN_HEART,				-1, -1,
    IMG_CHAR_QUESTION
  },
  {
    EL_SIGN_ONEWAY,				-1, -1,
    IMG_CHAR_QUESTION
  },
  {
    EL_SIGN_OTHER,				-1, -1,
    IMG_CHAR_QUESTION
  },
  {
    EL_SIGN_PARKING,				-1, -1,
    IMG_CHAR_QUESTION
  },
  {
    EL_SIGN_RADIOACTIVITY,			-1, -1,
    IMG_CHAR_QUESTION
  },
  {
    EL_SIGN_ROUND,				-1, -1,
    IMG_CHAR_QUESTION
  },
  {
    EL_SIGN_TRIANGLE,				-1, -1,
    IMG_CHAR_QUESTION
  },
  {
    EL_SIGN_WHEELCHAIR,				-1, -1,
    IMG_CHAR_QUESTION
  },
  {
    EL_SIGN_YINYANG,				-1, -1,
    IMG_CHAR_QUESTION
  },
  {
    EL_SPACESHIP,				-1, -1,
    IMG_SPACESHIP_RIGHT
  },
  {
    EL_CHAR_SPACE,				-1, -1,
    IMG_CHAR_SPACE
  },
  {
    EL_CHAR_EXCLAM,				-1, -1,
    IMG_CHAR_EXCLAM
  },
  {
    EL_CHAR_QUOTEDBL,				-1, -1,
    IMG_CHAR_QUOTEDBL
  },
  {
    EL_CHAR_NUMBERSIGN,				-1, -1,
    IMG_CHAR_NUMBERSIGN
  },
  {
    EL_CHAR_DOLLAR,				-1, -1,
    IMG_CHAR_DOLLAR
  },
  {
    EL_CHAR_PROCENT,				-1, -1,
    IMG_CHAR_PROCENT
  },
  {
    EL_CHAR_AMPERSAND,				-1, -1,
    IMG_CHAR_AMPERSAND
  },
  {
    EL_CHAR_APOSTROPHE,				-1, -1,
    IMG_CHAR_APOSTROPHE
  },
  {
    EL_CHAR_PARENLEFT,				-1, -1,
    IMG_CHAR_PARENLEFT
  },
  {
    EL_CHAR_PARENRIGHT,				-1, -1,
    IMG_CHAR_PARENRIGHT
  },
  {
    EL_CHAR_ASTERISK,				-1, -1,
    IMG_CHAR_ASTERISK
  },
  {
    EL_CHAR_PLUS,				-1, -1,
    IMG_CHAR_PLUS
  },
  {
    EL_CHAR_COMMA,				-1, -1,
    IMG_CHAR_COMMA
  },
  {
    EL_CHAR_MINUS,				-1, -1,
    IMG_CHAR_MINUS
  },
  {
    EL_CHAR_PERIOD,				-1, -1,
    IMG_CHAR_PERIOD
  },
  {
    EL_CHAR_SLASH,				-1, -1,
    IMG_CHAR_SLASH
  },
  {
    EL_CHAR_0,					-1, -1,
    IMG_CHAR_0
  },
  {
    EL_CHAR_1,					-1, -1,
    IMG_CHAR_1
  },
  {
    EL_CHAR_2,					-1, -1,
    IMG_CHAR_2
  },
  {
    EL_CHAR_3,					-1, -1,
    IMG_CHAR_3
  },
  {
    EL_CHAR_4,					-1, -1,
    IMG_CHAR_4
  },
  {
    EL_CHAR_5,					-1, -1,
    IMG_CHAR_5
  },
  {
    EL_CHAR_6,					-1, -1,
    IMG_CHAR_6
  },
  {
    EL_CHAR_7,					-1, -1,
    IMG_CHAR_7
  },
  {
    EL_CHAR_8,					-1, -1,
    IMG_CHAR_8
  },
  {
    EL_CHAR_9,					-1, -1,
    IMG_CHAR_9
  },
  {
    EL_CHAR_COLON,				-1, -1,
    IMG_CHAR_COLON
  },
  {
    EL_CHAR_SEMICOLON,				-1, -1,
    IMG_CHAR_SEMICOLON
  },
  {
    EL_CHAR_LESS,				-1, -1,
    IMG_CHAR_LESS
  },
  {
    EL_CHAR_EQUAL,				-1, -1,
    IMG_CHAR_EQUAL
  },
  {
    EL_CHAR_GREATER,				-1, -1,
    IMG_CHAR_GREATER
  },
  {
    EL_CHAR_QUESTION,				-1, -1,
    IMG_CHAR_QUESTION
  },
  {
    EL_CHAR_AT,					-1, -1,
    IMG_CHAR_AT
  },
  {
    EL_CHAR_A,					-1, -1,
    IMG_CHAR_A
  },
  {
    EL_CHAR_B,					-1, -1,
    IMG_CHAR_B
  },
  {
    EL_CHAR_C,					-1, -1,
    IMG_CHAR_C
  },
  {
    EL_CHAR_D,					-1, -1,
    IMG_CHAR_D
  },
  {
    EL_CHAR_E,					-1, -1,
    IMG_CHAR_E
  },
  {
    EL_CHAR_F,					-1, -1,
    IMG_CHAR_F
  },
  {
    EL_CHAR_G,					-1, -1,
    IMG_CHAR_G
  },
  {
    EL_CHAR_H,					-1, -1,
    IMG_CHAR_H
  },
  {
    EL_CHAR_I,					-1, -1,
    IMG_CHAR_I
  },
  {
    EL_CHAR_J,					-1, -1,
    IMG_CHAR_J
  },
  {
    EL_CHAR_K,					-1, -1,
    IMG_CHAR_K
  },
  {
    EL_CHAR_L,					-1, -1,
    IMG_CHAR_L
  },
  {
    EL_CHAR_M,					-1, -1,
    IMG_CHAR_M
  },
  {
    EL_CHAR_N,					-1, -1,
    IMG_CHAR_N
  },
  {
    EL_CHAR_O,					-1, -1,
    IMG_CHAR_O
  },
  {
    EL_CHAR_P,					-1, -1,
    IMG_CHAR_P
  },
  {
    EL_CHAR_Q,					-1, -1,
    IMG_CHAR_Q
  },
  {
    EL_CHAR_R,					-1, -1,
    IMG_CHAR_R
  },
  {
    EL_CHAR_S,					-1, -1,
    IMG_CHAR_S
  },
  {
    EL_CHAR_T,					-1, -1,
    IMG_CHAR_T
  },
  {
    EL_CHAR_U,					-1, -1,
    IMG_CHAR_U
  },
  {
    EL_CHAR_V,					-1, -1,
    IMG_CHAR_V
  },
  {
    EL_CHAR_W,					-1, -1,
    IMG_CHAR_W
  },
  {
    EL_CHAR_X,					-1, -1,
    IMG_CHAR_X
  },
  {
    EL_CHAR_Y,					-1, -1,
    IMG_CHAR_Y
  },
  {
    EL_CHAR_Z,					-1, -1,
    IMG_CHAR_Z
  },
  {
    EL_CHAR_AE,					-1, -1,
    IMG_CHAR_AE
  },
  {
    EL_CHAR_OE,					-1, -1,
    IMG_CHAR_OE
  },
  {
    EL_CHAR_UE,					-1, -1,
    IMG_CHAR_UE
  },
  {
    EL_CHAR_COPYRIGHT,				-1, -1,
    IMG_CHAR_COPYRIGHT
  },
  {
    EL_CHAR_UNDERSCORE,				-1, -1,
    IMG_CHAR_UNDERSCORE
  },
  {
    EL_CHAR_EMPTY,				-1, -1,
    IMG_CHAR_EMPTY
  },
  {
    EL_CHAR_DEGREE,				-1, -1,
    IMG_CHAR_DEGREE
  },
  {
    EL_CHAR_TM,					-1, -1,
    IMG_CHAR_TM
  },
  {
    EL_CHAR_CURSOR,				-1, -1,
    IMG_CHAR_CURSOR
  },
  {
    EL_CUSTOM_1,				-1, -1,
    IMG_CUSTOM_1
  },
  {
    EL_CUSTOM_2,				-1, -1,
    IMG_CUSTOM_2
  },
  {
    EL_CUSTOM_3,				-1, -1,
    IMG_CUSTOM_3
  },
  {
    EL_CUSTOM_4,				-1, -1,
    IMG_CUSTOM_4
  },
  {
    EL_CUSTOM_5,				-1, -1,
    IMG_CUSTOM_5
  },
  {
    EL_CUSTOM_6,				-1, -1,
    IMG_CUSTOM_6
  },
  {
    EL_CUSTOM_7,				-1, -1,
    IMG_CUSTOM_7
  },
  {
    EL_CUSTOM_8,				-1, -1,
    IMG_CUSTOM_8
  },
  {
    EL_CUSTOM_9,				-1, -1,
    IMG_CUSTOM_9
  },
  {
    EL_CUSTOM_10,				-1, -1,
    IMG_CUSTOM_10
  },
  {
    EL_CUSTOM_11,				-1, -1,
    IMG_CUSTOM_11
  },
  {
    EL_CUSTOM_12,				-1, -1,
    IMG_CUSTOM_12
  },
  {
    EL_CUSTOM_13,				-1, -1,
    IMG_CUSTOM_13
  },
  {
    EL_CUSTOM_14,				-1, -1,
    IMG_CUSTOM_14
  },
  {
    EL_CUSTOM_15,				-1, -1,
    IMG_CUSTOM_15
  },
  {
    EL_CUSTOM_16,				-1, -1,
    IMG_CUSTOM_16
  },
  {
    EL_CUSTOM_17,				-1, -1,
    IMG_CUSTOM_17
  },
  {
    EL_CUSTOM_18,				-1, -1,
    IMG_CUSTOM_18
  },
  {
    EL_CUSTOM_19,				-1, -1,
    IMG_CUSTOM_19
  },
  {
    EL_CUSTOM_20,				-1, -1,
    IMG_CUSTOM_20
  },
  {
    EL_CUSTOM_21,				-1, -1,
    IMG_CUSTOM_21
  },
  {
    EL_CUSTOM_22,				-1, -1,
    IMG_CUSTOM_22
  },
  {
    EL_CUSTOM_23,				-1, -1,
    IMG_CUSTOM_23
  },
  {
    EL_CUSTOM_24,				-1, -1,
    IMG_CUSTOM_24
  },
  {
    EL_CUSTOM_25,				-1, -1,
    IMG_CUSTOM_25
  },
  {
    EL_CUSTOM_26,				-1, -1,
    IMG_CUSTOM_26
  },
  {
    EL_CUSTOM_27,				-1, -1,
    IMG_CUSTOM_27
  },
  {
    EL_CUSTOM_28,				-1, -1,
    IMG_CUSTOM_28
  },
  {
    EL_CUSTOM_29,				-1, -1,
    IMG_CUSTOM_29
  },
  {
    EL_CUSTOM_30,				-1, -1,
    IMG_CUSTOM_30
  },
  {
    EL_CUSTOM_31,				-1, -1,
    IMG_CUSTOM_31
  },
  {
    EL_CUSTOM_32,				-1, -1,
    IMG_CUSTOM_32
  },
  {
    EL_CUSTOM_33,				-1, -1,
    IMG_CUSTOM_33
  },
  {
    EL_CUSTOM_34,				-1, -1,
    IMG_CUSTOM_34
  },
  {
    EL_CUSTOM_35,				-1, -1,
    IMG_CUSTOM_35
  },
  {
    EL_CUSTOM_36,				-1, -1,
    IMG_CUSTOM_36
  },
  {
    EL_CUSTOM_37,				-1, -1,
    IMG_CUSTOM_37
  },
  {
    EL_CUSTOM_38,				-1, -1,
    IMG_CUSTOM_38
  },
  {
    EL_CUSTOM_39,				-1, -1,
    IMG_CUSTOM_39
  },
  {
    EL_CUSTOM_40,				-1, -1,
    IMG_CUSTOM_40
  },
  {
    EL_CUSTOM_41,				-1, -1,
    IMG_CUSTOM_41
  },
  {
    EL_CUSTOM_42,				-1, -1,
    IMG_CUSTOM_42
  },
  {
    EL_CUSTOM_43,				-1, -1,
    IMG_CUSTOM_43
  },
  {
    EL_CUSTOM_44,				-1, -1,
    IMG_CUSTOM_44
  },
  {
    EL_CUSTOM_45,				-1, -1,
    IMG_CUSTOM_45
  },
  {
    EL_CUSTOM_46,				-1, -1,
    IMG_CUSTOM_46
  },
  {
    EL_CUSTOM_47,				-1, -1,
    IMG_CUSTOM_47
  },
  {
    EL_CUSTOM_48,				-1, -1,
    IMG_CUSTOM_48
  },
  {
    EL_CUSTOM_49,				-1, -1,
    IMG_CUSTOM_49
  },
  {
    EL_CUSTOM_50,				-1, -1,
    IMG_CUSTOM_50
  },
  {
    EL_CUSTOM_51,				-1, -1,
    IMG_CUSTOM_51
  },
  {
    EL_CUSTOM_52,				-1, -1,
    IMG_CUSTOM_52
  },
  {
    EL_CUSTOM_53,				-1, -1,
    IMG_CUSTOM_53
  },
  {
    EL_CUSTOM_54,				-1, -1,
    IMG_CUSTOM_54
  },
  {
    EL_CUSTOM_55,				-1, -1,
    IMG_CUSTOM_55
  },
  {
    EL_CUSTOM_56,				-1, -1,
    IMG_CUSTOM_56
  },
  {
    EL_CUSTOM_57,				-1, -1,
    IMG_CUSTOM_57
  },
  {
    EL_CUSTOM_58,				-1, -1,
    IMG_CUSTOM_58
  },
  {
    EL_CUSTOM_59,				-1, -1,
    IMG_CUSTOM_59
  },
  {
    EL_CUSTOM_60,				-1, -1,
    IMG_CUSTOM_60
  },
  {
    EL_CUSTOM_61,				-1, -1,
    IMG_CUSTOM_61
  },
  {
    EL_CUSTOM_62,				-1, -1,
    IMG_CUSTOM_62
  },
  {
    EL_CUSTOM_63,				-1, -1,
    IMG_CUSTOM_63
  },
  {
    EL_CUSTOM_64,				-1, -1,
    IMG_CUSTOM_64
  },
  {
    EL_CUSTOM_65,				-1, -1,
    IMG_CUSTOM_65
  },
  {
    EL_CUSTOM_66,				-1, -1,
    IMG_CUSTOM_66
  },
  {
    EL_CUSTOM_67,				-1, -1,
    IMG_CUSTOM_67
  },
  {
    EL_CUSTOM_68,				-1, -1,
    IMG_CUSTOM_68
  },
  {
    EL_CUSTOM_69,				-1, -1,
    IMG_CUSTOM_69
  },
  {
    EL_CUSTOM_70,				-1, -1,
    IMG_CUSTOM_70
  },
  {
    EL_CUSTOM_71,				-1, -1,
    IMG_CUSTOM_71
  },
  {
    EL_CUSTOM_72,				-1, -1,
    IMG_CUSTOM_72
  },
  {
    EL_CUSTOM_73,				-1, -1,
    IMG_CUSTOM_73
  },
  {
    EL_CUSTOM_74,				-1, -1,
    IMG_CUSTOM_74
  },
  {
    EL_CUSTOM_75,				-1, -1,
    IMG_CUSTOM_75
  },
  {
    EL_CUSTOM_76,				-1, -1,
    IMG_CUSTOM_76
  },
  {
    EL_CUSTOM_77,				-1, -1,
    IMG_CUSTOM_77
  },
  {
    EL_CUSTOM_78,				-1, -1,
    IMG_CUSTOM_78
  },
  {
    EL_CUSTOM_79,				-1, -1,
    IMG_CUSTOM_79
  },
  {
    EL_CUSTOM_80,				-1, -1,
    IMG_CUSTOM_80
  },
  {
    EL_CUSTOM_81,				-1, -1,
    IMG_CUSTOM_81
  },
  {
    EL_CUSTOM_82,				-1, -1,
    IMG_CUSTOM_82
  },
  {
    EL_CUSTOM_83,				-1, -1,
    IMG_CUSTOM_83
  },
  {
    EL_CUSTOM_84,				-1, -1,
    IMG_CUSTOM_84
  },
  {
    EL_CUSTOM_85,				-1, -1,
    IMG_CUSTOM_85
  },
  {
    EL_CUSTOM_86,				-1, -1,
    IMG_CUSTOM_86
  },
  {
    EL_CUSTOM_87,				-1, -1,
    IMG_CUSTOM_87
  },
  {
    EL_CUSTOM_88,				-1, -1,
    IMG_CUSTOM_88
  },
  {
    EL_CUSTOM_89,				-1, -1,
    IMG_CUSTOM_89
  },
  {
    EL_CUSTOM_90,				-1, -1,
    IMG_CUSTOM_90
  },
  {
    EL_CUSTOM_91,				-1, -1,
    IMG_CUSTOM_91
  },
  {
    EL_CUSTOM_92,				-1, -1,
    IMG_CUSTOM_92
  },
  {
    EL_CUSTOM_93,				-1, -1,
    IMG_CUSTOM_93
  },
  {
    EL_CUSTOM_94,				-1, -1,
    IMG_CUSTOM_94
  },
  {
    EL_CUSTOM_95,				-1, -1,
    IMG_CUSTOM_95
  },
  {
    EL_CUSTOM_96,				-1, -1,
    IMG_CUSTOM_96
  },
  {
    EL_CUSTOM_97,				-1, -1,
    IMG_CUSTOM_97
  },
  {
    EL_CUSTOM_98,				-1, -1,
    IMG_CUSTOM_98
  },
  {
    EL_CUSTOM_99,				-1, -1,
    IMG_CUSTOM_99
  },
  {
    EL_CUSTOM_100,				-1, -1,
    IMG_CUSTOM_100
  },
  {
    EL_CUSTOM_101,				-1, -1,
    IMG_CUSTOM_101
  },
  {
    EL_CUSTOM_102,				-1, -1,
    IMG_CUSTOM_102
  },
  {
    EL_CUSTOM_103,				-1, -1,
    IMG_CUSTOM_103
  },
  {
    EL_CUSTOM_104,				-1, -1,
    IMG_CUSTOM_104
  },
  {
    EL_CUSTOM_105,				-1, -1,
    IMG_CUSTOM_105
  },
  {
    EL_CUSTOM_106,				-1, -1,
    IMG_CUSTOM_106
  },
  {
    EL_CUSTOM_107,				-1, -1,
    IMG_CUSTOM_107
  },
  {
    EL_CUSTOM_108,				-1, -1,
    IMG_CUSTOM_108
  },
  {
    EL_CUSTOM_109,				-1, -1,
    IMG_CUSTOM_109
  },
  {
    EL_CUSTOM_110,				-1, -1,
    IMG_CUSTOM_110
  },
  {
    EL_CUSTOM_111,				-1, -1,
    IMG_CUSTOM_111
  },
  {
    EL_CUSTOM_112,				-1, -1,
    IMG_CUSTOM_112
  },
  {
    EL_CUSTOM_113,				-1, -1,
    IMG_CUSTOM_113
  },
  {
    EL_CUSTOM_114,				-1, -1,
    IMG_CUSTOM_114
  },
  {
    EL_CUSTOM_115,				-1, -1,
    IMG_CUSTOM_115
  },
  {
    EL_CUSTOM_116,				-1, -1,
    IMG_CUSTOM_116
  },
  {
    EL_CUSTOM_117,				-1, -1,
    IMG_CUSTOM_117
  },
  {
    EL_CUSTOM_118,				-1, -1,
    IMG_CUSTOM_118
  },
  {
    EL_CUSTOM_119,				-1, -1,
    IMG_CUSTOM_119
  },
  {
    EL_CUSTOM_120,				-1, -1,
    IMG_CUSTOM_120
  },
  {
    EL_CUSTOM_121,				-1, -1,
    IMG_CUSTOM_121
  },
  {
    EL_CUSTOM_122,				-1, -1,
    IMG_CUSTOM_122
  },
  {
    EL_CUSTOM_123,				-1, -1,
    IMG_CUSTOM_123
  },
  {
    EL_CUSTOM_124,				-1, -1,
    IMG_CUSTOM_124
  },
  {
    EL_CUSTOM_125,				-1, -1,
    IMG_CUSTOM_125
  },
  {
    EL_CUSTOM_126,				-1, -1,
    IMG_CUSTOM_126
  },
  {
    EL_CUSTOM_127,				-1, -1,
    IMG_CUSTOM_127
  },
  {
    EL_CUSTOM_128,				-1, -1,
    IMG_CUSTOM_128
  },
  {
    -1,						-1, -1,
    -1
  },
};

#endif	/* CONF_E2G_C */
