/***********************************************************
* Rocks'n'Diamonds -- McDuffin Strikes Back!               *
*----------------------------------------------------------*
* (c) 1995-2002 Artsoft Entertainment                      *
*               Holger Schemel                             *
*               Detmolder Strasse 189                      *
*               33604 Bielefeld                            *
*               Germany                                    *
*               e-mail: info@artsoft.org                   *
*----------------------------------------------------------*
* conf_snd.h                                               *
***********************************************************/

/* ----- this file was automatically generated -- do not edit by hand ----- */

#ifndef CONF_SND_H
#define CONF_SND_H

/* values for sounds configuration */

#define SND_CLASS_DEFAULT_DIGGING				0
#define SND_CLASS_DEFAULT_COLLECTING				1
#define SND_CLASS_DEFAULT_SNAPPING				2
#define SND_CLASS_DEFAULT_PUSHING				3
#define SND_CLASS_DEFAULT_IMPACT				4
#define SND_CLASS_DEFAULT_PASSING				5
#define SND_CLASS_DEFAULT_EXPLODING				6
#define SND_BD_DIAMOND_COLLECTING				7
#define SND_BD_DIAMOND_IMPACT				8
#define SND_BD_ROCK_PUSHING					9
#define SND_BD_ROCK_IMPACT					10
#define SND_BD_MAGIC_WALL_ACTIVATING			11
#define SND_BD_MAGIC_WALL_ACTIVE				12
#define SND_BD_MAGIC_WALL_FILLING				13
#define SND_BD_AMOEBA_WAITING				14
#define SND_BD_AMOEBA_GROWING				15
#define SND_BD_AMOEBA_TURNING_TO_GEM			16
#define SND_BD_AMOEBA_TURNING_TO_ROCK			17
#define SND_BD_BUTTERFLY_MOVING				18
#define SND_BD_BUTTERFLY_WAITING				19
#define SND_BD_FIREFLY_MOVING				20
#define SND_BD_FIREFLY_WAITING				21
#define SND_SP_BASE_DIGGING					22
#define SND_SP_BUGGY_BASE_DIGGING				23
#define SND_SP_BUGGY_BASE_ACTIVE				24
#define SND_SP_INFOTRON_COLLECTING				25
#define SND_SP_INFOTRON_IMPACT				26
#define SND_SP_ZONK_PUSHING					27
#define SND_SP_ZONK_IMPACT					28
#define SND_SP_DISK_RED_COLLECTING				29
#define SND_SP_DISK_ORANGE_PUSHING				30
#define SND_SP_DISK_YELLOW_PUSHING				31
#define SND_CLASS_SP_PORT_PASSING				32
#define SND_CLASS_SP_EXIT_PASSING				33
#define SND_CLASS_SP_EXIT_OPENING				34
#define SND_SP_SNIKSNAK_MOVING				35
#define SND_SP_SNIKSNAK_WAITING				36
#define SND_SP_ELECTRON_MOVING				37
#define SND_SP_ELECTRON_WAITING				38
#define SND_SP_TERMINAL_ACTIVATING				39
#define SND_SP_TERMINAL_ACTIVE				40
#define SND_CLASS_SOKOBAN_PUSHING				41
#define SND_CLASS_SOKOBAN_FILLING				42
#define SND_CLASS_SOKOBAN_EMPTYING				43
#define SND_EMPTY_SPACE_DIGGING				44
#define SND_SAND_DIGGING					45
#define SND_EMERALD_COLLECTING				46
#define SND_EMERALD_IMPACT					47
#define SND_DIAMOND_COLLECTING				48
#define SND_DIAMOND_IMPACT					49
#define SND_DIAMOND_BREAKING				50
#define SND_ROCK_PUSHING					51
#define SND_ROCK_IMPACT					52
#define SND_BOMB_PUSHING					53
#define SND_NUT_PUSHING					54
#define SND_NUT_BREAKING					55
#define SND_NUT_IMPACT					56
#define SND_CLASS_DYNAMITE_COLLECTING				57
#define SND_CLASS_DYNAMITE_DROPPING				58
#define SND_CLASS_DYNAMITE_ACTIVE				59
#define SND_CLASS_KEY_COLLECTING				60
#define SND_CLASS_GATE_PASSING					61
#define SND_BUG_MOVING					62
#define SND_BUG_WAITING					63
#define SND_SPACESHIP_MOVING				64
#define SND_SPACESHIP_WAITING				65
#define SND_YAMYAM_MOVING					66
#define SND_YAMYAM_WAITING					67
#define SND_YAMYAM_DIGGING					68
#define SND_ROBOT_MOVING					69
#define SND_ROBOT_WAITING					70
#define SND_ROBOT_WHEEL_ACTIVATING				71
#define SND_ROBOT_WHEEL_ACTIVE				72
#define SND_MAGIC_WALL_ACTIVATING				73
#define SND_MAGIC_WALL_ACTIVE				74
#define SND_MAGIC_WALL_FILLING				75
#define SND_CLASS_AMOEBA_WAITING				76
#define SND_CLASS_AMOEBA_GROWING				77
#define SND_CLASS_AMOEBA_DROPPING				78
#define SND_ACID_SPLASHING					79
#define SND_CLASS_QUICKSAND_FILLING				80
#define SND_CLASS_QUICKSAND_EMPTYING				81
#define SND_CLASS_EXIT_OPENING					82
#define SND_CLASS_EXIT_PASSING					83
#define SND_PENGUIN_PASSING					84
#define SND_BALLOON_MOVING					85
#define SND_BALLOON_WAITING					86
#define SND_BALLOON_PUSHING					87
#define SND_CLASS_BALLOON_SWITCH_ACTIVATING			88
#define SND_SPRING_MOVING					89
#define SND_SPRING_PUSHING					90
#define SND_SPRING_IMPACT					91
#define SND_CLASS_WALL_GROWING					92
#define SND_PEARL_COLLECTING				93
#define SND_PEARL_BREAKING					94
#define SND_PEARL_IMPACT					95
#define SND_CRYSTAL_COLLECTING				96
#define SND_CRYSTAL_IMPACT					97
#define SND_ENVELOPE_COLLECTING				98
#define SND_INVISIBLE_SAND_DIGGING				99
#define SND_SHIELD_NORMAL_COLLECTING			100
#define SND_SHIELD_NORMAL_ACTIVE				101
#define SND_SHIELD_DEADLY_COLLECTING			102
#define SND_SHIELD_DEADLY_ACTIVE				103
#define SND_EXTRA_TIME_COLLECTING				104
#define SND_MOLE_MOVING					105
#define SND_MOLE_WAITING					106
#define SND_MOLE_DIGGING					107
#define SND_CLASS_SWITCHGATE_SWITCH_ACTIVATING			108
#define SND_CLASS_SWITCHGATE_OPENING				109
#define SND_CLASS_SWITCHGATE_CLOSING				110
#define SND_CLASS_SWITCHGATE_PASSING				111
#define SND_TIMEGATE_SWITCH_ACTIVATING			112
#define SND_TIMEGATE_SWITCH_ACTIVE				113
#define SND_TIMEGATE_SWITCH_DEACTIVATING			114
#define SND_TIMEGATE_OPENING				115
#define SND_CLASS_TIMEGATE_CLOSING				116
#define SND_CLASS_TIMEGATE_PASSING				117
#define SND_CLASS_CONVEYOR_BELT_SWITCH_ACTIVATING		118
#define SND_CLASS_CONVEYOR_BELT_ACTIVE				119
#define SND_CLASS_CONVEYOR_BELT_SWITCH_DEACTIVATING		120
#define SND_LIGHT_SWITCH_ACTIVATING				121
#define SND_LIGHT_SWITCH_DEACTIVATING			122
#define SND_DX_SUPABOMB_PUSHING				123
#define SND_TRAP_DIGGING					124
#define SND_TRAP_ACTIVATING					125
#define SND_CLASS_TUBE_PASSING					126
#define SND_AMOEBA_TURNING_TO_GEM				127
#define SND_AMOEBA_TURNING_TO_ROCK				128
#define SND_SPEED_PILL_COLLECTING				129
#define SND_DYNABOMB_INCREASE_NUMBER_COLLECTING		130
#define SND_DYNABOMB_INCREASE_SIZE_COLLECTING		131
#define SND_DYNABOMB_INCREASE_POWER_COLLECTING		132
#define SND_CLASS_DYNABOMB_DROPPING				133
#define SND_CLASS_DYNABOMB_ACTIVE				134
#define SND_SATELLITE_MOVING				135
#define SND_SATELLITE_WAITING				136
#define SND_SATELLITE_PUSHING				137
#define SND_LAMP_ACTIVATING					138
#define SND_LAMP_DEACTIVATING				139
#define SND_TIME_ORB_FULL_COLLECTING			140
#define SND_TIME_ORB_FULL_IMPACT				141
#define SND_TIME_ORB_EMPTY_PUSHING				142
#define SND_TIME_ORB_EMPTY_IMPACT				143
#define SND_GAME_OF_LIFE_WAITING				144
#define SND_GAME_OF_LIFE_GROWING				145
#define SND_BIOMAZE_WAITING					146
#define SND_BIOMAZE_GROWING					147
#define SND_PACMAN_MOVING					148
#define SND_PACMAN_WAITING					149
#define SND_PACMAN_DIGGING					150
#define SND_DARK_YAMYAM_MOVING				151
#define SND_DARK_YAMYAM_WAITING				152
#define SND_DARK_YAMYAM_DIGGING				153
#define SND_PENGUIN_MOVING					154
#define SND_PENGUIN_WAITING					155
#define SND_PIG_MOVING					156
#define SND_PIG_WAITING					157
#define SND_PIG_DIGGING					158
#define SND_DRAGON_MOVING					159
#define SND_DRAGON_WAITING					160
#define SND_DRAGON_ATTACKING				161
#define SND_CLASS_PLAYER_DYING					162
#define SND_ELEMENT_EXPLODING				163
#define SND_SP_ELEMENT_EXPLODING				164
#define SND_GAME_STARTING					165
#define SND_GAME_RUNNING_OUT_OF_TIME			166
#define SND_GAME_LEVELTIME_BONUS				167
#define SND_GAME_LOSING					168
#define SND_GAME_WINNING					169
#define SND_GAME_SOKOBAN_SOLVING				170
#define SND_DOOR_OPENING					171
#define SND_DOOR_CLOSING					172
#define SND_BACKGROUND_SCORES				173
#define SND_BACKGROUND_INFO					174

#define NUM_SOUND_FILES				175

#endif	/* CONF_SND_H */
